### ISSUE TITLE
BGP IPv6 high CPU use

### ISSUE THREAD

**Issue by adamcharnock** [metallb/metallb#1029]
**Given the work on FRR integration (#1014 et al), I'm not really expecting this to be addressed**. But hopefully it will at least help someone Googling for "MetalLB BGP high CPU" like I was!

Feel free to close without resolution. Of course, if anyone knows a quick fix then do let me know.

## The problem

I'm seeing very high CPU use by `cilium-agent` when using BGP with an IPv6 prefix in my `address-pools`.

I'm running MetalLB via Cilium 1.10, running MetalLB 0.10 (according to Cilium's release notes). Kubernetes version `v1.21.5+rke2r2` (k8s via RKE2)

## Cilium BGP config

```
    peers:

      # Keep the above blank line. Fixes indentation issue
      - peer-address: "10.40.0.1"
        peer-asn: 65001
        my-asn: 65001
        password: "redacted"

    address-pools:
      - name: default
        avoid-buggy-ips: true
        protocol: bgp
        addresses:
          - "10.45.0.0/24"
          - "1234:1234:1234:2023:ff00::/112"
```

## Evidence

`cilium-agent` reliably consumes around 120% CPU an all nodes. Network traffic is minimal, so I don't think this is any kind of network loop.

Removing the IPv6 prefix from the pool remedies this problem. I can not see anything useful in the logs for `cilium-agent`.

<img width="721" alt="Screenshot 2021-11-07 at 11 11 20" src="https://user-images.githubusercontent.com/138215/140642605-014c0541-bef6-4ab2-a82b-b06f90db708f.png">
