### ISSUE TITLE
Assign static IP using FQDN

### ISSUE THREAD

**Issue by jamessewell** [metallb/metallb#1038]
Is this currently possible?

Something like this (which doesn't work, but you get the idea):

```
apiVersion: v1
kind: Service
metadata:
  name: thanos-query-local
  namespace: monitoring
spec:
  loadBalancerIP: thanos-query.com
```
