### ISSUE TITLE
New LoadBalancer service fails with: user requested a different IP than the one currently assigned

### ISSUE THREAD

**Issue by jforman** [metallb/metallb#1081]
Summary: I've tried two create two new LoadBalancer services on my bare-metal k8s cluster, but receive the error in the metallb log, and the service on the new requested IP is not listened on.

I've created two services as specified below to share the same IP 10.10.2.214. These are new services to the cluster, and have never existed previously in the cluster:
```
---
apiVersion: v1
kind: Service
metadata:
  name: gitea-metallb-https
  annotations:
    metallb.universe.tf/allow-shared-ip: "foobar"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.10.2.214
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: nginx-ingress
    app.kubernetes.io/component: controller
    release: nginx-ingress-release
---
---
apiVersion: v1
kind: Service
metadata:
  name: gitea-metallb-ssh
  annotations:
    metallb.universe.tf/allow-shared-ip: "foobar"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.10.2.214
  ports:
  - port: 22
    protocol: TCP
    targetPort: 22
  selector:
    app: gitea
```

The logs of metallb have these relevant snippets:
```
{"caller":"level.go:63","event":"clearAssignment","level":"info","msg":"user requested a different IP than the one currently assigned","reason":"differentIPRequested","service":"default/gitea-metallb-https","ts":"2021-11-25T19:40:00.712364589Z"}
{"caller":"level.go:63","event":"ipAllocated","ip":"10.10.2.214","level":"info","msg":"IP address assigned by controller","service":"default/gitea-metallb-https","ts":"2021-11-25T19:40:00.712943196Z"}
{"caller":"level.go:63","event":"serviceUpdated","level":"info","msg":"updated service object","service":"default/gitea-metallb-https","ts":"2021-11-25T19:40:00.752350039Z"}
{"caller":"level.go:63","event":"clearAssignment","level":"info","msg":"user requested a different IP than the one currently assigned","reason":"differentIPRequested","service":"default/gitea-metallb-ssh","ts":"2021-11-25T19:40:00.799038537Z"}
{"caller":"level.go:63","event":"ipAllocated","ip":"10.10.2.214","level":"info","msg":"IP address assigned by controller","service":"default/gitea-metallb-ssh","ts":"2021-11-25T19:40:00.800340317Z"}
{"caller":"level.go:63","event":"serviceUpdated","level":"info","msg":"updated service object","service":"default/gitea-metallb-ssh","ts":"2021-11-25T19:40:00.835144442Z"}

```    
     - Version of MetalLB:
```
Containers:
  speaker:
    Container ID:  containerd://934fdd7765b2a057672e16b4e0a53e191f51dc174feabd41329a6fc8d7b6eb2a
    Image:         quay.io/metallb/speaker:main
    Image ID:      quay.io/metallb/speaker@sha256:2ac76b56f78ae8161b5c685f615be2597c483accbd1c38abad262b7a94573657
    Ports:         7472/TCP, 7946/TCP, 7946/UDP
```
     - Version of Kubernetes: v.1.20.12
     - Name and version of network addon: flannel. 
     - Whether you've configured kube-proxy for iptables or ipvs mode: iptables

metallb configmap:
```
data:
  config: |
    address-pools:
    - addresses:
      - 10.10.2.211-10.10.2.231
      name: default
      protocol: layer2
```
