### ISSUE TITLE
LoadBalancer route advertised multiple times but routable via a single node only

### ISSUE THREAD

**Issue by aureq** [metallb/metallb#1104]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

(I understand the problem described below is at the edge of a question and a possible bug. However, not being able to tell, I'd rather ask the question here. If this is a user / lack of understanding on my part, feel free to close this issue. Thank you.)

I have a k3s cluster comprised of 3 master (also acting as worker) nodes deployed (`192.168.2.5(1,2,3)`). Externally, I have a BGP capable router (`192.168.2.254`, Debian 11 + FRR) used to receive BGP announcements. When I deploy `metallb` via its Chart (`values.yaml` is unchanged except for the `existingConfigMap`), 3 pods (speakers) and 1 operator are deployed across this cluster.

When I deploy `deployment.yaml`, the allocated IP address is advertised but *each* speaker announces the route *via their own node* resulting in 3 possible path to reach the said `LoadBalancer`. However, the `LoadBalancer` IP can only be reached via the node it is deployed onto.

1. Is it expected to have the 3 route advertisements made given only 1 node can serve the traffic? (Bug or expected behavior?)
2. If yes, since the LoadBalancer IP is only reachable via the node that hosts it, shouldn't the route be advertised through the node that has the pod only? (Bug or expected behavior?)
3. How to either, instruct MetalLB to tell Flannel how to route the traffic to the correct node when it's received via other nodes, *or*, get only the route advertised via the node that hosts the pod? (Question)

#### `metallb-config`
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: metallb-config
  namespace: metallb-system
data:
  config: |
    address-pools:
    - name: default
      protocol: bgp
      avoid-buggy-ips: true
      addresses:
      - 10.0.255.0/24
    peers:
    - my-asn: 64501
      peer-address: 192.168.2.254
      peer-asn: 64501
```

#### `deployment.yaml`
```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
```

#### `show ip route`
```
eris# show ip route
Codes: K - kernel route, C - connected, S - static, R - RIP,
       O - OSPF, I - IS-IS, B - BGP, E - EIGRP, N - NHRP,
       T - Table, v - VNC, V - VNC-Direct, A - Babel, F - PBR,
       f - OpenFabric,
       > - selected route, * - FIB route, q - queued, r - rejected, b - backup
       t - trapped, o - offload failure

K>* 0.0.0.0/0 [0/0] via 192.168.1.1, inet0 onlink, 00:01:16
B>* 10.0.255.1/32 [200/0] via 192.168.2.51, eth0, weight 1, 00:00:05
  *                       via 192.168.2.52, eth0, weight 1, 00:00:05
  *                       via 192.168.2.53, eth0, weight 1, 00:00:05
K>* 169.254.0.0/16 [0/1000] is directly connected, eth0, 00:01:16
C>* 192.168.1.0/24 is directly connected, inet0, 00:01:16
C>* 192.168.2.0/24 is directly connected, eth0, 00:01:16
```

#### `kubectl get nodes -o wide`
```NAME    STATUS   ROLES                       AGE   VERSION        INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                         KERNEL-VERSION   CONTAINER-RUNTIME
k3s-1   Ready    control-plane,etcd,master   22h   v1.21.5+k3s2   192.168.2.51   <none>        Debian GNU/Linux 11 (bullseye)   5.10.0-9-amd64   containerd://1.4.11-k3s1
k3s-2   Ready    control-plane,etcd,master   22h   v1.21.5+k3s2   192.168.2.52   <none>        Debian GNU/Linux 11 (bullseye)   5.10.0-9-amd64   containerd://1.4.11-k3s1
k3s-3   Ready    control-plane,etcd,master   22h   v1.21.5+k3s2   192.168.2.53   <none>        Debian GNU/Linux 11 (bullseye)   5.10.0-9-amd64   containerd://1.4.11-k3s1
```

#### `kubectl get svc -A`
```
NAMESPACE     NAME         TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                  AGE
default       kubernetes   ClusterIP      10.43.0.1      <none>        443/TCP                  22h
default       nginx        LoadBalancer   10.43.209.31   10.0.255.1    80:32594/TCP             22m
kube-system   kube-dns     ClusterIP      10.43.0.10     <none>        53/UDP,53/TCP,9153/TCP   22h
```

#### `kubectl get pods -n default -o wide`
```
NAME                    READY   STATUS    RESTARTS   AGE   IP           NODE    NOMINATED NODE   READINESS GATES
nginx-8c9df995d-zxwp7   1/1     Running   0          22m   10.42.2.12   k3s-3   <none>           <none>
```

## Environment

* k3s `k3s version v1.21.5+k3s2 (724ef700)`
* `servicelb`, `traefik5`, and `metrics-server` are not installed
* `flannel` in VXLAN mode is used for the network layer
* MetalLB `0.11.0` is used for this deployment (Helm Chart)

Thank you.
