### ISSUE TITLE
Using password in peer config seems to break bgp advertisements

### ISSUE THREAD

**Issue by jeremybusk** [metallb/metallb#1125]
metallb: v0.11.0
kubernetes: minikube latest v1.24.0 (though I had an issue on microk8s 1.23. as well)
I did set arpstrict in kubeproxy bug that shouldn't make a difference. I included frr for example even though the tcp/179 syn packet isn't even leaving the k8s node when using password line.

If I  remove the password lines below in configs for  frr and metallb config it works  but I want to use password.

If I use the password line like below it is written below bgp packets on tcp port 179 via tcpdump pcap don't even leave the k8s node from metallb speaker
and I get a line  like below in logs
```
{"caller":"level.go:63","error":"dial \"10.1.2.1:179\": setsockopt: protocol not available","level":"error","localASN":65552,"msg":"failed to connect to peer","op":"connect","peer":"10.1.2.1:179","peerASN":65551,"ts":"2021-12-15T02:20:55.866005919Z"}
```

Here are demo configs

metallb config.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
    - # a test
      peer-address: 10.1.2.1
      my-asn: 65552
      peer-asn: 65551
      password: "yourPassword"
    address-pools:
    - name: my-ip-space
      protocol: bgp
      addresses:
      - 198.51.100.0/24
```

frr.conf
```
frr version 8.1
frr defaults traditional
hostname demogw
log syslog informational
service integrated-vtysh-config
!
ip router-id 10.1.2.1
!
router bgp 65551
 bgp log-neighbor-changes
 neighbor metallb peer-group
 neighbor metallb remote-as 65552
 neighbor metallb password yourPassword
 !
 bgp listen range 10.0.0.0/8 peer-group metallb
 !
 address-family ipv4 unicast
  aggregate-address 198.51.100.0/24 summary-only
  redistribute connected
 exit-address-family
exit
!
```

Maybe there is a format issue within speaker binary code or maybe it is the way I'm setting it up. Maybe someone can help me out. Thanks for all the excellent work. Love this project.
