### ISSUE TITLE
Custom annotation for pinning ips (single and dual stack)

### ISSUE THREAD

**Issue by fedepaol** [metallb/metallb#1155]
The loadbalancerip field is gonna be deprecated (see https://github.com/kubernetes/kubernetes/pull/107235)

That has two implications:
- we need to have an alternative way to pin to a specific ip (the suggested way is to implement custom annotations on the service, see https://github.com/kubernetes/enhancements/pull/1992)
- that will enable us to pin both v6 and v4 addresses to the service (currently, only one is possible)

So, this issue is about having a custom annotation handled by metallb, that declares the user's will to use a specific ip (or ips).
See also https://github.com/kubernetes/enhancements/pull/1992#issuecomment-1000113208 for reference.

**Comment by markkrj** [comment]
@fedepaol There was also #727 that implemented an annotation like:
`metallb.universe.tf/load-balancer-ips: "10.0.0.20,1000::20"` ([#727(comment)](https://github.com/metallb/metallb/pull/727#issuecomment-698273081)).
IMO it would be better if you implemented it this way and not like azure where you have to pre-allocate the IP, assigning it a name, so that you can refer to it in the service's annotations... In metallb the IP already has to be assigned to a pool, so having to pre-allocate it in yet another place before assigning it to the actual service is bad UX IMO...

I know that there is no proposal for this yet. Just wanted to share my thoughts to maybe influence someone who might come with one, or at least generate discussion 🤗

**Comment by fedepaol** [comment]
@markkrj thanks for raising the point, and I totally agree having the explicit ips makes total sense in metallb context.

**Comment by pperiyasamy** [comment]
I'll work on this.

**Comment by fedepaol** [comment]
Thanks @pperiyasamy , assigning this to you

**Comment by muhlba91** [comment]
with dual stack services support now released in `0.12.0`, is this also included?
are there docs or an example on how such setup (dual stack service + assigned ip addresses) can look?

**Comment by fedepaol** [comment]
@muhlba91 here: https://metallb.universe.tf/usage/#requesting-specific-ips

**Comment by muhlba91** [comment]
thanks for the link! :)

hence, if i want to assign a specific ip address to my service in dual stack mode, i currently have to create a separate pool containing 1 IPv4 and 1 IPv6 address for the controller to assign those when selecting the pool.

is there any ETA available for this annotation to be released which will make such assignments and management easier?

**Comment by fedepaol** [comment]
It's already released

**Comment by adamcharnock** [comment]
I've also been following this and I'll try to deploy it this week. My interpretation of the above link is that we can now do this (untested):

```
        address-pools:
          - name: my-pool
            avoid-buggy-ips: true
            protocol: bgp
            addresses:
              - "10.1.2.0/24"
              - "db8::/112"
```

```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    metallb.universe.tf/address-pool: my-pool
    metallb.universe.tf/loadBalancerIPs: 10.1.2.3,2001:db8::1
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
```

Does that look about right to you @fedepaol?
