### ISSUE TITLE
metalb not release ip when service is deleted

### ISSUE THREAD

**Issue by dalei2019** [metallb/metallb#1184]
### Description 
 1.  deploy MetalLB use helm

install
```
helm install metallb public/metallb -f overrides.yaml
```
overrides.yaml
```
configInline:
  address-pools:
   - name: default
     protocol: layer2
     addresses:
     - 10.11.20.250-10.11.20.251
``` 
 2. create service A with LoadBalancer type.
 2.  MetalLB auto assign ip **10.11.20.250** to this service.
 3. service A is ok.
 4. delete service A.
 4. create service B with LoadBalancer type.
 5. MetalLB auto assign ip **10.11.20.251** to this service.
 6. service B is ok.

### Question
How to release **10.11.20.250**  ,and then let service B reuse it , not assign new ip .

### Environment Info

- Version of MetalLB
  
    helm chart version :  **metallb-0.11.0**
 
- Version of Kubernetes
  
   **v1.22.1**

 - addon

   **flannel**

 - Whether you've configured kube-proxy for iptables or ipvs mode
I have on idea, config is : 
```
    iptables:
      masqueradeAll: false
      masqueradeBit: null
      minSyncPeriod: 0s
      syncPeriod: 0s
    ipvs:
      excludeCIDRs: null
      minSyncPeriod: 0s
      scheduler: ""
      strictARP: true
      syncPeriod: 0s
      tcpFinTimeout: 0s
      tcpTimeout: 0s
      udpTimeout: 0s
```
