### ISSUE TITLE
config-watcher Role/Rolebinding missing from kustomization manifests from version >=0.10

### ISSUE THREAD

**Issue by brokenjacobs** [metallb/metallb#1255]
Deployments fail using the kustomization manifests because the speaker and controller can't read the configmap in the metallb-system namespace. Here are the missing manifests:
```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: metallb
  name: config-watcher
  namespace: metallb-system
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: metallb
  name: config-watcher
  namespace: metallb-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: config-watcher
subjects:
- kind: ServiceAccount
  name: controller
- kind: ServiceAccount
  name: speaker
```
