### ISSUE TITLE
[cilium] metallb does not work in remote subnet

### ISSUE THREAD

**Issue by schmitch** [metallb/metallb#1261]
hello, somehow I have this strange issue that metallb works on the same subnet but not on a different subnet. (but I'm not sure if thats because of cilium, because arping from a kubernetes node does not work, while `curl`-ing the service works)

currently my configuration is as follow:
- 3 bare metal linux nodes (mellanox connectx-5 network card)
- flatcar-linux 3033.2.3
- k3s  v1.23.4+k3s1
- cilium 1.11.1 (can also post the configuration of it)
- no kube-proxy (we use kube-vip to have a vip address on all the nodes which we than use for kube-proxyless mode)

If I do a arping, all 3 nodes have the following tcpdump logs (but nothing more, there is no reply, it's just a request):

`tcpdump -n -i eno12399np0 arp src host 192.168.179.51` from `10.10.30.11`, `10.10.30.12`, `10.10.30.13` (same reply of all 3 nodes, 
```
dropped privs to tcpdump
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eno12399np0, link-type EN10MB (Ethernet), capture size 262144 bytes
08:20:43.390937 ARP, Request who-has 10.10.30.20 (ff:ff:ff:ff:ff:ff) tell 192.168.179.51, length 46
```

`arping -I ens224 10.10.30.20` output from `192.168.179.51`:
```
arping -I ens224 10.10.30.20
ARPING 10.10.30.20 from 192.168.179.51 ens224
Sent 457 probes (457 broadcast(s))
Received 0 response(s)
```

I also attached the speaker logs (in debug mode):

[speaker-logs.txt](https://github.com/metallb/metallb/files/8251446/speaker-logs.txt)

somebody got an idea? (btw. I got redirected from slack that I should raise an issue)

here is my cilium helm values file (maybe that helps aswell):
```
autoDirectNodeRoutes: true
externalIPs:
  enabled: true
hostServices:
  enabled: true
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
ipam:
  operator:
    clusterPoolIPv4PodCIDR: 10.42.0.0/16
    clusterPoolIPv4PodCIDRList:
    - 10.42.0.0/16
ipv4NativeRoutingCIDR: 10.10.30.0/24
k8sServiceHost: 10.10.30.10
k8sServicePort: 6443
kubeProxyReplacement: strict
loadBalancer:
  acceleration: native
  mode: dsr
masquerade: true
nativeRoutingCIDR: 10.10.30.0/24
operator:
  rollOutPods: true
rollOutCiliumPods: true
tunnel: disabled
```

and I needed to set:
```
ManageForeignRoutingPolicyRules=no
ManageForeignRoutes=no
```
inside `/etc/systemd/networkd.conf` (systemd) because of https://github.com/flatcar-linux/Flatcar/issues/659 (I suspected that the most, since it basically already worked, but I upgraded some stuff and also did this config so I can't track down the error)
