### ISSUE TITLE
metallb controller fails to allocate IP address to dual stack services if only IPv4 is available

### ISSUE THREAD

**Issue by johanfleury** [metallb/metallb#1339]
## Description

Hi

With metallb versions 0.12.0 and higher, the controller fails to allocate IP address to a dual stack service if only IPv4 addresses is available, **breaking backward compatibility**.

The controller prints the following log messages:

```
{"caller":"level.go:63","event":"startUpdate","level":"debug","msg":"start of service update","service":"nginx-ingress/nginx-ingress","ts":"2022-04-25T22:29:12.12940356Z"}
{"caller":"level.go:63","error":"no available IPs","level":"error","msg":"IP allocation failed","op":"allocateIPs","service":"nginx-ingress/nginx-ingress","ts":"2022-04-25T22:29:12.129441323Z"}
{"caller":"level.go:63","event":"serviceUpdated","level":"info","msg":"updated service object","service":"nginx-ingress/nginx-ingress","ts":"2022-04-25T22:29:12.14483344Z"}
{"caller":"level.go:63","event":"endUpdate","level":"debug","msg":"end of service update","service":"nginx-ingress/nginx-ingress","ts":"2022-04-25T22:29:12.144889261Z"}
```

Here is metallb configuration:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: metallb-config
  namespace: kube-system
data:
  config: |
    address-pools:
    - addresses:
      - <IPv4>/32
      bgp-advertisements:
      - communities:
        - no-advertise
      name: default
      protocol: bgp
    bgp-communities:
      no-advertise: 65535:65282
    peers:
    - my-asn: 64545
      peer-address: 192.168.163.128
      peer-asn: 64545
```

And here is the service:

```
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.0.0.79
  clusterIPs:
  - 10.0.0.79
  - fd00::d899
  externalTrafficPolicy: Local
  healthCheckNodePort: 30272
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  - IPv6
  ipFamilyPolicy: PreferDualStack
  ports:
  - name: http
    nodePort: 30122
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: 32678
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/instance: nginx-ingress
    app.kubernetes.io/name: nginx-ingress
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
```

Because the service is dual stack, but metallb has no IPv6 configured in any pool, the controller fails to allocate an IPv6 address and stops there. This was confirmed by making the service single stack (IPv4 only) which “fixed” the issue.

My opinion is that the controller should only “soft fail” in such case: if it can allocate an IP address for one of the IP families it should do it.

Also, the log message is not really clear, it doesn’t really explain what’s failing.

## Installation details

* Version of MetalLB: works with 0.11.0, *doesn’t* work with 0.12.0 and 0.12.1
* Version of Kubernetes: 1.23
* Name and version of network addon (e.g. Calico, Weave...): no network addon, I’m using default CNI plugins
* Whether you've configured kube-proxy for iptables or ipvs mode: iptables

**Comment by fedepaol** [comment]
I agree, would make the logs more explicit about the failure, but I think the behaviour is the right one, preventing from mis configurations and making users think that the service is dual stack while it's not.

**Comment by johanfleury** [comment]
I disagree, I feel like a good log message and event/status would be better than just failing and breaking connectivity to the service.

I added a mention in the issue that this breaks backward compatibility.

**Comment by fedepaol** [comment]
> I disagree, I feel like a good log message and event/status would be better than just failing and breaking connectivity to the service.
> 
> I added a mention in the issue that this breaks backward compatibility.

I (now) understand it. The thing is, before we did not support dual stack and we were treating dual stack services as single stack ones. We then added support, putting the constraint of the need of both ips to come from the same addresspool.

I need to think how big is the impact to remove this constraint, especially considering all the extra configuration degrees we are putting into the advertisements such as node selector, peer selector, which ultimately end up being tied to the addresspool, and if it's worth the effort.

Keeping this issue open for now, and thanks again for taking the time to open it

**Comment by gwvandesteeg** [comment]
Just ran into this, still an issue.
Really easy to reproduce using kind.

* create kind cluster
  ```yaml
  ---
  kind: Cluster
  apiVersion: kind.x-k8s.io/v1alpha4
  networking:
    ipFamily: dual
  ```
* install metallb as per https://kind.sigs.k8s.io/docs/user/loadbalancer/
* setup an address pool

```yaml
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: loadbalancer
  namespace: metallb-system
spec:
  addresses:
  - 172.20.254.200-172.20.254.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system
```
* create a Service of type LoadBalancer with `ipFamilyPolicy: "PreferDualStack", and `ipFamilies: [IPv4]`

You should see an error like:
```
  Type     Reason            Age    From                Message
  ----     ------            ----   ----                -------
  Warning  AllocationFailed  2m56s  metallb-controller  Failed to allocate IP for "ingress-nginx/nginx-ingress-controller": no available IPs
```
