### ISSUE TITLE
metric does not updated when service  is deleted 

### ISSUE THREAD

**Issue by sebihiy** [metallb/metallb#1342]
**Problem description**
metallb still  shows metric when  services type LoadBlancer are deleted ( no assigned External IPs).

**Installation steps**
```
helm repo add metallb https://metallb.github.io/metallb
helm upgrade metallb metallb/metallb --install --wait --namespace metallb-system   -f values.yaml  --version 0.12.1

kubectl get po -n metallb-system -o wide
NAME                                READY   STATUS    RESTARTS   AGE   IP              NODE       NOMINATED NODE   READINESS GATES
metallb-controller-d4964cff-xwb9h   1/1     Running   0          13d   10.233.69.146   worker01   <none>           <none>
metallb-speaker-bj9qx               1/1     Running   0          13d   192.168.1.74    worker01   <none>           <none>
metallb-speaker-dxrnh               1/1     Running   0          13d   192.168.1.76    worker03   <none>           <none>
metallb-speaker-p8v2w               1/1     Running   0          13d   192.168.1.75    worker02   <none>           <none>
metallb-speaker-q8kwb               1/1     Running   0          13d   192.168.1.77    worker04   <none>           <none>
```
**Steps to reproduce**
Configmap (metallb.yaml) and service manifests (service1.yaml and service2.yaml) in bleow :  

Configmap : 
```
apiVersion: v1
data:
  config: |
    address-pools:
    - addresses:
      - 192.168.1.133-192.168.1.137
      name: default
      protocol: layer2
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: metallb
    meta.helm.sh/release-namespace: metallb-system
  labels:
    app.kubernetes.io/instance: metallb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: metallb
    app.kubernetes.io/version: v0.12.1
    helm.sh/chart: metallb-0.12.1
  name: metallb
  namespace: metallb-system
```

The service1.yaml and service2.yaml typically have the same manifeste , only the name of the app that changes :  
``` 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment2
spec:
  selector:
    matchLabels:
      app: nginx2
  replicas: 4
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - name: nginx2
        image: nginx:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx2
spec:
  type: LoadBalancer
  selector:
    app: nginx2
  ports:
  - port: 80
    name: http
```
Deploy  service nginx.yaml on test-metallb namespace , after delete it and deploy seconde service (nginx2.yaml )  and delete it too 

```
$ kubectl apply -f nginx.yaml -n test-metallb

 $ kubectl get po -n test-metallb  -o wide
NAME                                READY   STATUS    RESTARTS   AGE   IP              NODE       NOMINATED NODE   READINESS GATES
nginx-deployment2-5bdc94ddb-2zlcd   1/1     Running   0          35m   10.233.69.219   worker01   <none>           <none>
nginx-deployment2-5bdc94ddb-6xqdg   1/1     Running   0          27m   10.233.70.80    worker02   <none>           <none>
nginx-deployment2-5bdc94ddb-jmh2j   1/1     Running   0          32m   10.233.68.167   worker03   <none>           <none>
nginx-deployment2-5bdc94ddb-w947m   1/1     Running   0          32m   10.233.67.30    worker04   <none>           <none

$  kubectl get svc  -n test-metallb
NAME     TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)        AGE
nginx2   LoadBalancer   10.233.43.200   192.168.1.134   80:30808/TCP   36m

$  kubectl delete  -f nginx.yaml -n test-metallb
$  kubectl apply -f nginx2.yaml -n test-metallb
$  kubectl delete  -f  nginx2.yaml -n test-metallb
$  kubectl get svc  -n test-metallb
No resources found in test-metallb namespace.

the current state: I only have the ingress-controller service of type LoadBalancer
 $ kubectl get svc  -A  | grep LoadBalancer
ingress-nginx       ingress-nginx-controller          LoadBalancer   10.233.49.97    192.168.1.133   80:31719/TCP,443:31952/TCP     237d
``` 

**BUG :** 
We still have the metrics of 2 services knowing that we have deleted the 2 service type loadbalancer. These metrics will be gone when metallb-speaker pods restart.

```
# HELP metallb_layer2_gratuitous_sent Number of gratuitous layer2 packets sent for owned IPs as a result of failovers
# TYPE metallb_layer2_gratuitous_sent counter
metallb_layer2_gratuitous_sent{ip="192.168.1.133"} 24
metallb_layer2_gratuitous_sent{ip="192.168.1.134"} 592
# HELP metallb_layer2_requests_received Number of layer2 requests received for owned IPs
# TYPE metallb_layer2_requests_received counter
metallb_layer2_requests_received{ip="192.168.1.133"} 1
metallb_layer2_requests_received{ip="192.168.1.134"} 4
# HELP metallb_layer2_responses_sent Number of layer2 responses sent for owned IPs in response to requests
# TYPE metallb_layer2_responses_sent counter
metallb_layer2_responses_sent{ip="192.168.1.133"} 1
metallb_layer2_responses_sent{ip="192.168.1.134"} 4
# HELP metallb_speaker_announced Services being announced from this node. This is desired state, it does not guarantee that the routing protocols have converged.
# TYPE metallb_speaker_announced gauge
metallb_speaker_announced{ip="192.168.1.133",node="worker01",protocol="layer2",service="ingress-nginx/ingress-nginx-controller"} 1
metallb_speaker_announced{ip="192.168.1.134",node="worker01",protocol="layer2",service="test-metallb/nginx"} 1
metallb_speaker_announced{ip="192.168.1.134",node="worker01",protocol="layer2",service="test-metallb/nginx2"} 1
```
**System Information**

- Version of MetalLB: v0.12.1
- Version of Kubernetes: v1.22.8
- Name and version of network addon: Flannel
- Kube-proxy configuration: Not relevant (and issue seen in both ipvs and iptables mode)
