### ISSUE TITLE
BGP metric

### ISSUE THREAD

**Issue by duylong** [metallb/metallb#1388]
Hi,

Can we have the possibility to put a metric value with FRR? This value is always 0 on routers and I would like the route managed by metallb are not always priority.

So far it doesn't work with this example:
```
    - name: XXX
      protocol: bgp
      addresses:                  
      - XXX
      bgp-advertisements:           
      - metric: 10             
```
```
{"caller":"level.go:63","configmap":"metallb-system/config","error":"could not parse config: yaml: unmarshal errors:\n  line 68: field metric not found in type config.bgpAdvertisement\n  line 76: field metric not found in type config.bgpAdvertisement\n  line 84: field metric not found in type config.bgpAdvertisement","event":"configStale","level":"error","msg":"config (re)load failed, config marked stale","ts":"2022-05-25T13:06:10.581373859Z"}
```

Version of MetalLB : 0.0.12.1
