### ISSUE TITLE
Metallb not fowarding traffic

### ISSUE THREAD

**Issue by dblviking** [metallb/metallb#1395]
metallb v0.9.5
Client Version: 4.7.13
Server Version: 4.8.29
Kubernetes Version: v1.21.6+bb8d50a

- Whether you've configured kube-proxy for iptables or ipvs mode  - How do I confirm?

I've seen this behaviour on >4.7. Normally I have to install 4.7.X to get this working again. I'm now on 4.8.29 but I need to have this functional. I've tried metallb v10 and v11. Same behaviour.

I have a namespace that has a single external ip address 
10.10.10.160   31040:30853/TCP

Normally I can use nc to check the forwarding:
```
nc -zv 10.10.10.160 31041
Ncat: Version 7.50 ( https://nmap.org/ncat )
Ncat: Connected to 10.10.10.160:31041.
Ncat: 0 bytes sent, 0 bytes received in 0.01 seconds.
```

but when I install metallb with the same config and yamls on 4.8.X it just times out.

```
nc -zv 10.10.10.160 31040
nc: connect to 10.10.10.160port 31040 (tcp) failed: Connection timed out
```

Here's my simple layer2 config:

```
definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        namespace: metallb-system
        name: config
      data:
        config: |
          address-pools:
          - name: loadbalancer
            protocol: layer2
            addresses:
            - 10.10.10.140-10.10.10.160

```

pods etc:

```
NAME                              READY   STATUS    RESTARTS   AGE
pod/controller-7d66dbc86d-986c5   1/1     Running   0          37m
pod/speaker-c54pt                 1/1     Running   0          37m
pod/speaker-m69m6                 1/1     Running   0          37m
pod/speaker-zblwc                 1/1     Running   0          37m

NAME                     DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                 AGE
daemonset.apps/speaker   3         3         3       3            3           node-role.kubernetes.io/lb=   37m

NAME                         READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/controller   1/1     1            1           37m

NAME                                    DESIRED   CURRENT   READY   AGE
replicaset.apps/controller-7d66dbc86d   1         1         1       37m


```

here's a kubetail -l app=metallb,component=speaker -n metallb-system
I've bolded the error:

[speaker-c54pt] {"caller":"net.go:210","component":"Memberlist","msg":"[DEBUG] memberlist: Stream connection from=10.10.10.235:34906","ts":"2022-05-26T06:06:23.897907449Z"}
**[speaker-c54pt] W0526 06:06:35.420155       1 reflector.go:302] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: watch of *v1.ConfigMap ended with: too old resource version: 457083 (462522)**
[speaker-m69m6] {"caller":"net.go:210","component":"Memberlist","msg":"[DEBUG] memberlist: Stream connection from=10.10.10.233:51920","ts":"2022-05-26T06:06:36.126599446Z"}
[speaker-c54pt] {"caller":"net.go:785","component":"Memberlist","msg":"[DEBUG] memberlist: Initiating push/pull sync with: 10.10.10.235:7946","ts":"2022-05-26T06:06:36.126453414Z"}
[speaker-c54pt] {"caller":"main.go:318","configmap":"metallb-system/config","event":"startUpdate","msg":"start of config update","ts":"2022-05-26T06:06:36.421774918Z"}
[speaker-c54pt] {"caller":"main.go:342","configmap":"metallb-system/config","event":"endUpdate","msg":"end of config update","ts":"2022-05-26T06:06:36.421827135Z"}
[speaker-c54pt] {"caller":"k8s.go:402","configmap":"metallb-system/config","event":"configLoaded","msg":"config (re)loaded","ts":"2022-05-26T06:06:36.421838157Z"}

**Comment by oribon** [comment]
Hi, can you please share your full speakers logs and the service's (10.10.10.160) spec?
Have you tried using arping/tcpdump as described in https://metallb.universe.tf/configuration/troubleshooting/?

**Comment by fedepaol** [comment]
Also, try to change the loglevel parameter to debug before sending the logs.

**Comment by dblviking** [comment]
sorry 4.7 is the oc binary. I have copied over the 4.8.29 binary since.

This is interesting though. On a 4.7.42 cluster with metallb working, I'm getting a single mac of what I assume is the client pod.
For 4.8.29, I'm getting the mac response of all the nodes in my cluster.

4.7
```
sudo arping -I ens192 10.10.10.86
ARPING 10.10.10.86
60 bytes from 40:a6:b7:68:20:00 (10.10.10.86): index=0 time=185.382 usec
60 bytes from 40:a6:b7:68:20:00 (10.10.10.86): index=1 time=238.917 usec
60 bytes from 40:a6:b7:68:20:00 (10.10.10.86): index=2 time=246.703 usec
60 bytes from 40:a6:b7:68:20:00 (10.10.10.86): index=3 time=257.666 usec
60 bytes from 40:a6:b7:68:20:00 (10.10.10.86): index=4 time=203.778 usec
60 bytes from 40:a6:b7:68:20:00 (10.10.10.86): index=5 time=239.675 usec
60 bytes from 40:a6:b7:68:20:00 (10.10.10.86): index=6 time=258.630 usec
60 bytes from 40:a6:b7:68:20:00 (10.10.10.86): index=7 time=235.195 usec
60 bytes from 40:a6:b7:68:20:00 (10.10.10.86): index=8 time=251.229 usec
60 bytes from 40:a6:b7:68:20:00 (10.10.10.86): index=9 time=254.976 usec
60 bytes from 40:a6:b7:68:20:00 (10.10.10.86): index=10 time=282.795 usec
^C
--- 10.10.10.86 statistics ---
11 packets transmitted, 11 packets received,   0% unanswered (0 extra)
rtt min/avg/max/std-dev = 0.185/0.241/0.283/0.026 ms
```


4.8
```
sudo arping -I ens160 10.10.10.160
ARPING 10.10.10.160
60 bytes from 78:ac:44:3a:91:ba (10.10.10.160): index=0 time=446.215 usec
60 bytes from 78:ac:44:39:cc:44 (10.10.10.160): index=1 time=634.836 usec
60 bytes from 78:ac:44:35:bf:52 (10.10.10.160): index=2 time=727.994 usec
60 bytes from 78:ac:44:35:be:42 (10.10.10.160): index=3 time=787.692 usec
60 bytes from 78:ac:44:39:ea:ca (10.10.10.160): index=4 time=857.051 usec
60 bytes from 78:ac:44:39:fd:98 (10.10.10.160): index=5 time=892.125 usec
60 bytes from 78:ac:44:35:bf:52 (10.10.10.160): index=6 time=925.327 usec
60 bytes from 78:ac:44:35:bf:52 (10.10.10.160): index=7 time=370.391 usec
60 bytes from 78:ac:44:39:cc:44 (10.10.10.160): index=8 time=593.930 usec
60 bytes from 78:ac:44:39:fd:98 (10.10.10.160): index=9 time=686.193 usec
60 bytes from 78:ac:44:39:ea:ca (10.10.10.160): index=10 time=758.633 usec
60 bytes from 78:ac:44:35:bf:52 (10.10.10.160): index=11 time=833.306 usec
60 bytes from 78:ac:44:3a:91:ba (10.10.10.160): index=12 time=908.762 usec
60 bytes from 78:ac:44:35:be:42 (10.10.10.160): index=13 time=1.299 msec
60 bytes from 78:ac:44:35:bf:52 (10.10.10.160): index=14 time=302.291 usec
60 bytes from 78:ac:44:39:cc:44 (10.10.10.160): index=15 time=530.396 usec
60 bytes from 78:ac:44:3a:91:ba (10.10.10.160): index=16 time=598.954 usec
60 bytes from 78:ac:44:35:be:42 (10.10.10.160): index=17 time=656.176 usec
60 bytes from 78:ac:44:39:fd:98 (10.10.10.160): index=18 time=728.019 usec
60 bytes from 78:ac:44:35:bf:52 (10.10.10.160): index=19 time=788.271 usec
60 bytes from 78:ac:44:39:ea:ca (10.10.10.160): index=20 time=829.209 usec
^C
--- 10.10.10.160 statistics ---
3 packets transmitted, 21 packets received,   0% unanswered (18 extra)
```
Here's my specs:
```
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: metallb
    component: speaker
  name: speaker
  namespace: metallb-system
spec:
  selector:
    matchLabels:
      app: metallb
      component: speaker
  template:
    metadata:
      annotations:
        prometheus.io/port: '7472'
        prometheus.io/scrape: 'true'
      labels:
        app: metallb
        component: speaker
    spec:
      containers:
      - args:
        - --port=7472
        - --config=config
        env:
        - name: METALLB_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: METALLB_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: METALLB_ML_BIND_ADDR
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        # needed when another software is also using memberlist / port 7946
        #- name: METALLB_ML_BIND_PORT
        #  value: "7946"
        - name: METALLB_ML_LABELS
          value: "app=metallb,component=speaker"
        - name: METALLB_ML_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: METALLB_ML_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: memberlist
              key: secretkey
        image: quay.io/metallb/speaker:v0.9.5
        imagePullPolicy: Always
        name: speaker
        ports:
        - containerPort: 7472
          name: monitoring
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_ADMIN
            drop:
            - ALL
          readOnlyRootFilesystem: true
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/lb: ""
      serviceAccountName: speaker
      terminationGracePeriodSeconds: 2
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metallb
    component: controller
  name: controller
  namespace: metallb-system
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: metallb
      component: controller
  template:
    metadata:
      annotations:
        prometheus.io/port: '7472'
        prometheus.io/scrape: 'true'
      labels:
        app: metallb
        component: controller
    spec:
      containers:
      - args:
        - --port=7472
        - --config=config
        image: quay.io/metallb/controller:v0.9.5
        imagePullPolicy: Always
        name: controller
        ports:
        - containerPort: 7472
          name: monitoring
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          readOnlyRootFilesystem: true
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
      serviceAccountName: controller
      terminationGracePeriodSeconds: 0

```

Here's the speaker logs when I ran that arp ping from my helper node

```
Will tail 3 logs...
speaker-c54pt
speaker-m69m6
speaker-zblwc
[speaker-m69m6] {"caller":"net.go:785","component":"Memberlist","msg":"[DEBUG] memberlist: Initiating push/pull sync with: 10.10.12.234:7946","ts":"2022-05-26T14:23:30.606449089Z"}
[speaker-zblwc] {"caller":"net.go:210","component":"Memberlist","msg":"[DEBUG] memberlist: Stream connection from=10.10.12.235:36438","ts":"2022-05-26T14:23:30.60657245Z"}
[speaker-m69m6] {"caller":"arp.go:102","interface":"br-ex","ip":"10.10.10.160","msg":"got ARP request for service IP, sending response","responseMAC":"78:ac:44:35:bf:52","senderIP":"10.10.12.228","senderMAC":"00:50:56:85:96:68","ts":"2022-05-26T14:23:41.234537479Z"}
[speaker-m69m6] {"caller":"arp.go:102","interface":"br-ex","ip":"10.10.10.160","msg":"got ARP request for service IP, sending response","responseMAC":"78:ac:44:35:bf:52","senderIP":"10.10.12.228","senderMAC":"00:50:56:85:96:68","ts":"2022-05-26T14:23:42.19615876Z"}
[speaker-m69m6] {"caller":"net.go:210","component":"Memberlist","msg":"[DEBUG] memberlist: Stream connection from=10.10.12.233:45112","ts":"2022-05-26T14:23:42.245237911Z"}
[speaker-c54pt] {"caller":"net.go:785","component":"Memberlist","msg":"[DEBUG] memberlist: Initiating push/pull sync with: 10.10.12.235:7946","ts":"2022-05-26T14:23:42.245202172Z"}
[speaker-m69m6] {"caller":"arp.go:102","interface":"br-ex","ip":"10.10.10.160","msg":"got ARP request for service IP, sending response","responseMAC":"78:ac:44:35:bf:52","senderIP":"10.10.12.228","senderMAC":"00:50:56:85:96:68","ts":"2022-05-26T14:23:43.197192657Z"}
[speaker-m69m6] {"caller":"arp.go:102","interface":"br-ex","ip":"10.10.10.160","msg":"got ARP request for service IP, sending response","responseMAC":"78:ac:44:35:bf:52","senderIP":"10.10.12.228","senderMAC":"00:50:56:85:96:68","ts":"2022-05-26T14:23:44.198244278Z"}
[speaker-m69m6] {"caller":"arp.go:102","interface":"br-ex","ip":"10.10.10.160","msg":"got ARP request for service IP, sending response","responseMAC":"78:ac:44:35:bf:52","senderIP":"10.10.12.228","senderMAC":"00:50:56:85:96:68","ts":"2022-05-26T14:23:45.199041603Z"}
[speaker-m69m6] {"caller":"arp.go:102","interface":"br-ex","ip":"10.10.10.160","msg":"got ARP request for service IP, sending response","responseMAC":"78:ac:44:35:bf:52","senderIP":"10.10.12.228","senderMAC":"00:50:56:85:96:68","ts":"2022-05-26T14:23:46.200007621Z"}
[speaker-c54pt] {"caller":"speakerlist.go:272","msg":"triggering discovery","op":"memberDiscovery","ts":"2022-05-26T14:23:46.638891828Z"}
[speaker-m69m6] {"caller":"arp.go:102","interface":"br-ex","ip":"10.10.10.160","msg":"got ARP request for service IP, sending response","responseMAC":"78:ac:44:35:bf:52","senderIP":"10.10.12.228","senderMAC":"00:50:56:85:96:68","ts":"2022-05-26T14:23:47.201128368Z"}
[speaker-m69m6] {"caller":"arp.go:102","interface":"br-ex","ip":"10.10.10.160","msg":"got ARP request for service IP, sending response","responseMAC":"78:ac:44:35:bf:52","senderIP":"10.10.12.228","senderMAC":"00:50:56:85:96:68","ts":"2022-05-26T14:23:48.202161039Z"}
[speaker-m69m6] {"caller":"arp.go:102","interface":"br-ex","ip":"10.10.10.160","msg":"got ARP request for service IP, sending response","responseMAC":"78:ac:44:35:bf:52","senderIP":"10.10.12.228","senderMAC":"00:50:56:85:96:68","ts":"2022-05-26T14:23:49.203249564Z"}
[speaker-c54pt] {"caller":"net.go:210","component":"Memberlist","msg":"[DEBUG] memberlist: Stream connection from=10.10.12.234:59500","ts":"2022-05-26T14:23:49.425675894Z"}
[speaker-zblwc] {"caller":"net.go:785","component":"Memberlist","msg":"[DEBUG] memberlist: Initiating push/pull sync with: 10.10.12.233:7946","ts":"2022-05-26T14:23:49.425510852Z"}
[speaker-m69m6] {"caller":"arp.go:102","interface":"br-ex","ip":"10.10.10.160","msg":"got ARP request for service IP, sending response","responseMAC":"78:ac:44:35:bf:52","senderIP":"10.10.12.228","senderMAC":"00:50:56:85:96:68","ts":"2022-05-26T14:23:50.204266461Z"}
[speaker-m69m6] {"caller":"arp.go:102","interface":"br-ex","ip":"10.10.10.160","msg":"got ARP request for service IP, sending response","responseMAC":"78:ac:44:35:bf:52","senderIP":"10.10.12.228","senderMAC":"00:50:56:85:96:68","ts":"2022-05-26T14:23:51.20537243Z"}
[speaker-m69m6] {"caller":"arp.go:102","interface":"br-ex","ip":"10.10.10.160","msg":"got ARP request for service IP, sending response","responseMAC":"78:ac:44:35:bf:52","senderIP":"10.10.12.228","senderMAC":"00:50:56:85:96:68","ts":"2022-05-26T14:23:52.20653262Z"}
[speaker-m69m6] {"caller":"arp.go:102","interface":"br-ex","ip":"10.10.10.160","msg":"got ARP request for service IP, sending response","responseMAC":"78:ac:44:35:bf:52","senderIP":"10.10.12.228","senderMAC":"00:50:56:85:96:68","ts":"2022-05-26T14:23:53.20695475Z"}
[speaker-m69m6] {"caller":"arp.go:102","interface":"br-ex","ip":"10.10.10.160","msg":"got ARP request for service IP, sending response","responseMAC":"78:ac:44:35:bf:52","senderIP":"10.10.12.228","senderMAC":"00:50:56:85:96:68","ts":"2022-05-26T14:23:54.208014292Z"}
[speaker-m69m6] {"caller":"arp.go:102","interface":"br-ex","ip":"10.10.10.160","msg":"got ARP request for service IP, sending response","responseMAC":"78:ac:44:35:bf:52","senderIP":"10.10.12.228","senderMAC":"00:50:56:85:96:68","ts":"2022-05-26T14:23:55.209047558Z"}
[speaker-m69m6] {"caller":"arp.go:102","interface":"br-ex","ip":"10.10.10.160","msg":"got ARP request for service IP, sending response","responseMAC":"78:ac:44:35:bf:52","senderIP":"10.10.12.228","senderMAC":"00:50:56:85:96:68","ts":"2022-05-26T14:23:56.210093252Z"}
[speaker-m69m6] {"caller":"arp.go:102","interface":"br-ex","ip":"10.10.10.160","msg":"got ARP request for service IP, sending response","responseMAC":"78:ac:44:35:bf:52","senderIP":"10.10.12.228","senderMAC":"00:50:56:85:96:68","ts":"2022-05-26T14:23:57.210902692Z"}
[speaker-m69m6] {"caller":"arp.go:102","interface":"br-ex","ip":"10.10.10.160","msg":"got ARP request for service IP, sending response","responseMAC":"78:ac:44:35:bf:52","senderIP":"10.10.12.228","senderMAC":"00:50:56:85:96:68","ts":"2022-05-26T14:23:58.212079389Z"}
[speaker-m69m6] {"caller":"arp.go:102","interface":"br-ex","ip":"10.10.10.160","msg":"got ARP request for service IP, sending response","responseMAC":"78:ac:44:35:bf:52","senderIP":"10.10.12.228","senderMAC":"00:50:56:85:96:68","ts":"2022-05-26T14:23:59.213203512Z"}
[speaker-m69m6] {"caller":"arp.go:102","interface":"br-ex","ip":"10.10.10.160","msg":"got ARP request for service IP, sending response","responseMAC":"78:ac:44:35:bf:52","senderIP":"10.10.12.228","senderMAC":"00:50:56:85:96:68","ts":"2022-05-26T14:24:00.213447184Z"}
[speaker-c54pt] {"caller":"net.go:210","component":"Memberlist","msg":"[DEBUG] memberlist: Stream connection from=10.10.12.235:43976","ts":"2022-05-26T14:24:00.608095007Z"}
[speaker-m69m6] {"caller":"net.go:785","component":"Memberlist","msg":"[DEBUG] memberlist: Initiating push/pull sync with: 10.10.12.233:7946","ts":"2022-05-26T14:24:00.6079013Z"}
[speaker-m69m6] {"caller":"arp.go:102","interface":"br-ex","ip":"10.10.10.160","msg":"got ARP request for service IP, sending response","responseMAC":"78:ac:44:35:bf:52","senderIP":"10.10.12.228","senderMAC":"00:50:56:85:96:68","ts":"2022-05-26T14:24:01.214442158Z"}
[speaker-m69m6] {"caller":"arp.go:102","interface":"br-ex","ip":"10.10.10.160","msg":"got ARP request for service IP, sending response","responseMAC":"78:ac:44:35:bf:52","senderIP":"10.10.12.228","senderMAC":"00:50:56:85:96:68","ts":"2022-05-26T14:24:02.214879409Z"}
[speaker-m69m6] {"caller":"arp.go:102","interface":"br-ex","ip":"10.10.10.160","msg":"got ARP request for service IP, sending response","responseMAC":"78:ac:44:35:bf:52","senderIP":"10.10.12.228","senderMAC":"00:50:56:85:96:68","ts":"2022-05-26T14:24:03.215993827Z"}

```
