### ISSUE TITLE
when i install metallb and distribution the ip ，i can not contact the node whit ssh

### ISSUE THREAD

**Issue by JaminCui** [metallb/metallb#1397]
Kubernetes version： 1.21.5
metallb：0.9.6/0.12.1 （both tried）
network :Calico
kube-proxy : iptables
### my kubernetes cluster : 
  * master1:192.168.1.1
  * master2:192.168.1.2
  * work1: 192.168.1.3
  * work2: 192.168.1.4
  * work3: 192.168.1.5
### metallb config map：
```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.1.3-192.168.1.5
```
after install and config metallb，i deploy a service and it worked, using "kubectl get svc" can see "EXTERNAL-IP" is "192.168.1.3"
```
apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
```
now i can not contact the work1(192.168.1.3) with ssh
