### ISSUE TITLE
Deployment manifest contains the deprecated PodSecurityPolicy

### ISSUE THREAD

**Issue by oomichi** [metallb/metallb#1401]
**The bug itself, as detailed as you can.**:

https://metallb.universe.tf/installation/#installation-by-manifest shows how to install metallb with manifest like
```
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.12.1/manifests/namespace.yaml
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.12.1/manifests/metallb.yaml
```
The metallb.yaml contains PodSecurityPolicy which has been deprecated since Kubernetes v1.21 and will be removed Kubernetes v1.25 as https://kubernetes.io/docs/concepts/security/pod-security-policy/

I cannot find manifests/ directory on the latest master branch.
Does the community still maintain the manifest?
Or do users need to switch the helm chart?

**Comment by fedepaol** [comment]
The manifest folder was moved under `config/manifests` to keep `config` as the only entry point for the various configurations.

Manifests are still maintained, and we are now also exposing a kustomize friendly layout.

Regarding the PSP issue, the problem is, we are trying to offer compatibility with the current supported kubernetes versions, and my understanding is:

Pod security admission is beta in 1.23
The next kubernetes version that will obsoleted is 1.22, which will happen in October (see https://kubernetes.io/releases/)
So, my understanding is, if we want to support 1.22 and offer some kind of admission we need to have psp onboard.

Once 1.22 goes out of support and 1.25 is supported, we will switch to pod security admission. Hope it makes sense and my understand of the whole machinery is correct.

**Comment by oomichi** [comment]
@fedepaol Thank you so much for your answer.
That is perfect, I will follow the metallb changes on the Kubernetes deployment tool project(Kubespray).

**Comment by fedepaol** [comment]
> @fedepaol Thank you so much for your answer. That is perfect, I will follow the metallb changes on the Kubernetes deployment tool project(Kubespray).

nice, thanks!

**Comment by rikirolly** [comment]
Has someone found a solution for this?

**Comment by jbpratt** [comment]
Hey @rikirolly, while it is really just a workaround, you can use kustomize patches to do something like this which worked for me (for numerous projects):

```
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/metallb/metallb/v0.13.4/config/manifests/metallb-native.yaml
patchesStrategicMerge:
- |-
  $patch: delete
  apiVersion: policy/v1beta1
  kind: PodSecurityPolicy
  metadata:
    name: controller
- |-
  $patch: delete
  apiVersion: policy/v1beta1
  kind: PodSecurityPolicy
  metadata:
    name: speaker
```

then `kubectl kustomize mydir/` to build the manifests
