### ISSUE TITLE
Limit the address pool/ips that each namespace can receive from the LB

### ISSUE THREAD

**Issue by pablopardod** [metallb/metallb#1422]
After two weeks of searching I can't find a way to limit a namespace of my Kubernetes platform to only receive ip's from a certain range, either automatically or with the annotation:     
`metallb.universe.tf/address-pool: <address_pool_name>`

Context: 
My Kubernetes cluster is accessible by different users, which only have access to certain namespaces. 
I have configured the address pools in the metallb as follows:
```
- name: group1
  protocol: layer2
  addresses:
  - 10.0.1.10-10.0.1.80
- name: group2
  protocol: layer2
  addresses:
  - 10.0.2.10-10.0.2.80
- name: group3
  protocol: layer2
  addresses:
  - 10.0.3.10-10.0.3.80
```
And I would like that when an LB service is created in one of the namespaces of the cluster, it can only receive an ip from its range.

Thank you very much in advance for your help.

Pablo.
