### ISSUE TITLE
flag provided but not defined: -cert-service-name

### ISSUE THREAD

**Issue by wibed** [metallb/metallb#1468]
set up metallb:
1. install manifests -> this works fine
```
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.12.1/manifests/namespace.yaml
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.12.1/manifests/metallb.yaml
```

1.1 install manifests using helm -> this does not work fine
```
configInline:
  address-pools:
   - name: default
     protocol: layer2
     addresses:
     - 10.0.48.0/24

controller:
  image:
    tag: v0.12.1
    pullPolicy: Always

speaker:
  memberlist:
    enabled: false
  secretName: memberlist
  image:
    tag: v0.12.1
    pullPolicy: Always
```

2. add metallb-system namespace to exemptions
```
But now facing the follwing error message:
kubectl logs -n metallb-system pod/cluster0-metallb-controller-7b86769c5f-mqtz8

#Error
flag provided but not defined: -cert-service-name
```

google point to the only reference i could find https://github.com/metallb/metallb/blob/main/controller/main.go
i tried reinstalling, several times.
helm is inflated using kustomize helm inflator
`kustomize build . --enable-helm --load-restrictor=LoadRestrictionsNone  | kubectl apply -f-`

**Comment by fedepaol** [comment]
Can you give us the output of the controller pod's yaml?

k get pod -o yaml?

Also, where are you running kustomize from? Which branch?

**Comment by wibed** [comment]
i have reverted to use manifest installation path which works fine.

the cluster had nothing running on itself at that time except metallb, so it might be replicatable using any basic setup.

**Comment by fedepaol** [comment]
Just to make sure I understand, you think it's still replicable?
If so, can you tell me from which branch you ran ` kustomize build . --enable-helm --load-restrictor=LoadRestrictionsNone | kubectl apply -f-` and if that is the only command needed?

Thanks

**Comment by wibed** [comment]
> Just to make sure I understand, you think it's still replicable? If so, can you tell me from which branch you ran ` kustomize build . --enable-helm --load-restrictor=LoadRestrictionsNone | kubectl apply -f-` and if that is the only command needed?
> 
> Thanks

its the main branch.
thats the only command issued. given you have the files in place

**Comment by rogelio-o** [comment]
I faced the same problem. Unfortunately, the v13 versions are not being pushed to DockerHub, so I was using the new Helm Chart with the old container images (v12).

Changing your configuration to get the v13 versions of speakers and controller from quay will make the Helm Chart work.

```
controller:
  image:
    repository: quay.io/metallb/controller
    tag: v0.13.7

speaker:
  image:
    repository: quay.io/metallb/speaker
    tag: v0.13.7
```
