### ISSUE TITLE
Metallb installation Helm - values.yml: configInline is no longer supported

### ISSUE THREAD

**Issue by Pseudow** [metallb/metallb#1525]
# Problem
Hello, I found out that I could install **Metallb** on my cluster using **Helm**, however it is specified on the doc that I should add a `values.yml` files. But I couldn't find an example of it.

![image](https://user-images.githubusercontent.com/64150196/179808530-e72fd75e-5b5e-4743-937b-243d1f56df5e.png)

I followed a **tutorial** and created this:
```yml
configInline:
  address-pools:
  - name: stagging
    protocol: layer2
    addresses:
    - <my-address>
```

However I am getting this following **error**:
```
$ helm install metallb metallb/metallb -f values.yml

Error: INSTALLATION FAILED: execution error at (metallb/templates/deprecated_configInline.yaml:2:4): Starting from v0.13.0 configInline is no longer supported. Please see https://metallb.universe.tf/#backward-compatibility
```
