### ISSUE TITLE
LoadBalancer stays in pending state for ExternalIp

### ISSUE THREAD

**Issue by Pseudow** [metallb/metallb#1526]
# Problem
I am having my load balancer generated by `nginx` that stays stuck pending to be assigned an **ExternalIp**:
```
NAME                       TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
ingress-nginx-controller   LoadBalancer   10.99.247.242   <pending>     80:31682/TCP,443:31110/TCP   11m
```

# Logs
## Logs of metallb controller
```
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"ingress-nginx/ingress-nginx-controller-admission","ts":"2022-07-19T19:41:51Z"}
{"caller":"service_controller.go:95","controller":"ServiceReconciler","event":"force service reload","level":"info","ts":"2022-07-19T19:41:51Z"}
{"caller":"service_controller.go:97","controller":"ServiceReconciler","end reconcile":"ingress-nginx/ingress-nginx-controller-admission","level":"info","ts":"2022-07-19T19:41:51Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"ingress-nginx/ingress-nginx-controller","ts":"2022-07-19T19:41:51Z"}
{"caller":"service_controller.go:95","controller":"ServiceReconciler","event":"force service reload","level":"info","ts":"2022-07-19T19:41:51Z"}
{"caller":"service_controller.go:97","controller":"ServiceReconciler","end reconcile":"ingress-nginx/ingress-nginx-controller","level":"info","ts":"2022-07-19T19:41:51Z"}
{"caller":"service_controller_reload.go:61","controller":"ServiceReconciler - reprocessAll","level":"info","start reconcile":"metallbreload/reload","ts":"2022-07-19T19:41:51Z"}
{"caller":"service_controller_reload.go:103","controller":"ServiceReconciler - reprocessAll","end reconcile":"metallbreload/reload","level":"info","ts":"2022-07-19T19:41:51Z"}
{"caller":"service_controller_reload.go:61","controller":"ServiceReconciler - reprocessAll","level":"info","start reconcile":"metallbreload/reload","ts":"2022-07-19T19:41:51Z"}
{"caller":"service_controller_reload.go:103","controller":"ServiceReconciler - reprocessAll","end reconcile":"metallbreload/reload","level":"info","ts":"2022-07-19T19:41:51Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"ingress-nginx/ingress-nginx-controller-admission","ts":"2022-07-19T19:42:10Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"ingress-nginx/ingress-nginx-controller-admission","level":"info","ts":"2022-07-19T19:42:10Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"ingress-nginx/ingress-nginx-controller","ts":"2022-07-19T19:42:10Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"ingress-nginx/ingress-nginx-controller","level":"info","ts":"2022-07-19T19:42:10Z"}
```

# CR
## IPAddressPool
```yml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: altarise-pool
  namespace: metallb-system
spec:
  addresses:
  - 185.216.25.195/32
  ```
  
  ## L2Advertisement
  ```yml
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: altarise-pool-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - altarise-pool
  ```
