### ISSUE TITLE
Metallb crashing my master node

### ISSUE THREAD

**Issue by Pseudow** [metallb/metallb#1528]
# Situation
Hello, I recently installed `metallb` for my `nginx ingress controller`. However I found out that some minutes after setting un my ingress it happens that my machine was **crashing then booting**, and before the next crashing I had like **3seconds**. During this time I uninstalled helm metallb chart and everything then **worked**. I tried to reinstall it to be sure it was from that and I **uninstalled nginx and it worked as well**.

I first thought it would have been a problem with nginx and then I **installed** `traefik` and **uninstalled nginx**, but some minutes after setting up my ingress it **crashed again**.

I don't really know how to debug this problem.

# How to reproduce
### Installing metallb using helm charts:
```yml
cdrs:
  enabled: true

controller:
  logLevel: "all"

speaker:
  logLevel: "all"
```
### Adding basic CR
```yml
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: altarise-pool-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - altarise-pool
  ```
  
```yml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: altarise-pool
  namespace: metallb-system
spec:
  addresses:
  - 185.216.25.195/32
```

### Installing nginx
```
helm install nginx-ingress-controller -n nginx-ingress  nginx-stable/nginx-ingress --create-namespace
```
### Setting up ingress
```yml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: privateregistry
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"  # redirect port http -> https
  labels:
    app: privateregistry
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - altarise.net
    secretName: altarise-registry-cert
  rules:
  - host: altarise.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: privateregistry
            port:
              name: http-web
```

# Architecture
- **Debian 11**
- **Kubeadm**
- Kubectl Version: **v1.24.3**
- Helm Version: **v3.9.1**
