### ISSUE TITLE
Unable to assign 3 IPs to a lb svc from two different pools

### ISSUE THREAD

**Issue by samip5** [metallb/metallb#1557]
I tried creating an IPv4, IPv4, IPv6 LB IPs due to needing an private v4, public v4 and v6 on bare-metal install so that I can use the private v4 to forward from my router to cluster. The public IP has a totally different routing policy.

Error: 
```
5s          Warning   AllocationFailed    service/blocky                             Failed to allocate IP for "networking/blocky": ["192.168.10.54" "2001:67c:1104:<snip>:53::1"] is not allowed in config
```

Service annotation: `metallb.universe.tf/loadBalancerIPs: "192.168.10.54, 2001:67c:1104:<snip>:53::1"`

metallb config:
```
---
peers:
  - peer-address: 10.0.105.1
    peer-asn: 213021
    my-asn: 213021
address-pools:
  - name: default
    protocol: bgp
    avoid-buggy-ips: true
    addresses:
      - 10.96.69.0/24
      - 192.168.10.0/24
      - 2001:67c:<snip>::/112
  - name: public
    protocol: bgp
    avoid-buggy-ips: true
    addresses:
      - 185.218.<snip>.60/30
      - 2001:67c:<snip>:fc00::/64
```

     
Kubernetes version: v1.23.3+k3s1
Network addon: Cilium
MetalLB chart: 0.12.1 with FRR version 8.3.0.
Kube-proxy is disabled for Cilium.

Related Slack discussion: https://kubernetes.slack.com/archives/C8FSTGU56/p1660618498489979
Helm values: <https://github.com/samip5/k8s-cluster/blob/9cfe78b6ebe637cd62a40061e8871e7ccc1f9671/cluster/apps/kube-system/metallb/helm-release.yaml>
