### ISSUE TITLE
IP allocated by controller not allowed by config

### ISSUE THREAD

**Issue by zrav** [metallb/metallb#1572]
As per request in #1473 I'm opening a new issue for a mentioned bug:

I converted my very simple 0.12.1 config with a single IP to 0.13.x, but it fails with:

```
error: assigned IP not allowed by config, ips: ["10.10.1.163"], level: error, msg: IP allocated by controller not allowed by config.
```
The config:
```
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-ip
  namespace: metallb
spec:
  ipAddressPools:
  - default-pool
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb
spec:
  addresses:
  - 10.10.1.163/32
```
Additionally, I noted that with 0.13.x a metallb-speaker pod is deployed on all nodes instead of only worker nodes (how it works with the old version).

- Kubernetes 1.24.3 installed via kubdeadm on Ubuntu 22.04.1, three CP nodes and three worker nodes
- CNI: Flannel 0.19.1
- kube-proxy running in iptables mode

Due to this I had to downgrade back to 0.12.1, which will eventually prevent me from upgrading to newer Kubernetes versions due to PodSecurityPolicies use.

**Comment by fedepaol** [comment]
Regarding the nodes: did you deploy metallb via helm or via the manifests?

**Comment by zrav** [comment]
I installed 013.4 via helm, providing the edited metallb_values.yaml.

**Comment by fedepaol** [comment]
Ack, thanks! And thanks for taking the time to file the issue!

**Comment by liornoy** [comment]
@zrav can you please share the content of the metallb_values.yaml you used?

**Comment by zrav** [comment]
I just tried with 0.13.5 on our production cluster, but the problem did not reappear.
As for the speakers running on control plane nodes, that is of course because the DaemonSet definition has tolerations for the CP taints. For us it makes zero sense to run speakers on CP nodes, so I edited out the tolerations. I believe this should be default.

**Comment by liornoy** [comment]
@zrav are you sure that MetalLB deployed the speakers only on the worker nodes on older versions?
as you can see in this [ref](https://github.com/metallb/metallb/blob/v0.12/charts/metallb/values.yaml#L186) the default
was to deploy on the master nodes prior to 0.13.x

**Comment by zrav** [comment]
Yes I'm sure, just verified it on my test cluster. In the linked values file I see "tolerateMaster: true" but empty tolerations. Is it possible tolerateMaster does not handle the control-plane taint of recent version of Kubernetes?

**Comment by liornoy** [comment]
Thanks for the clarification!
After another look, it seems that MetalLB's default behavior was always to deploy the speaker pods on the master nodes.
However, the combination of Kubernetes version 1.24+ and MetalLB pre-v0.13 results in a bug where the speaker pods aren't being deployed on the master nodes. (as the new `node-role.kubernetes.io/control-plane` taint was introduced).

**Comment by penguineer** [comment]
I am using the helm chart as 
```yaml
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: metallb
  namespace: metallb-system
spec:
  chart: metallb
  version: 0.13.7
  repo: https://metallb.github.io/metallb
  targetNamespace: metallb-system
```
but I did not set any specific tolerations/taints. Did I miss something in the documentation?
I have spent a lot of time looking around for the proper resource definitions, but nothing else caught my eye.
