### ISSUE TITLE
Helmchart relabelings does not work correctly

### ISSUE THREAD

**Issue by felixhuettner** [metallb/metallb#1593]
Hi everyone,

when i configure `relabelings` in the prometheus section of the helmchart they are templated wrongly and therefor fail to apply.

Example to create a servicemonitor with relabel config:
```bash
helm template metallb/metallb --set 'prometheus.enabled=true,prometheus.serviceMonitor.enabled=true,prometheus.serviceAccount=someserviceaccount,prometheus.namespace=somenamespace,prometheus.serviceMonitor.relabelings[0].sourceLabels[0]=somesourcelabel,prometheus.serviceMonitor.relabelings[0].targetLabel=sometargetlabel'
```

this will output the following serviceMonitor:
```yaml
# Source: metallb/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: release-name-metallb-controller-monitor
  labels:
    helm.sh/chart: metallb-0.13.5
    app.kubernetes.io/name: metallb
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.13.5"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: speaker
spec:
  endpoints:
    - port: "metrics"
      honorLabels: true

  jobLabel: "app.kubernetes.io/name"
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      name: release-name-metallb-controller-monitor-service
  relabelings:
    - sourceLabels:
      - somesourcelabel
      targetLabel: sometargetlabel
```

however when trying to apply this to kubernetes i get the following error message: `unknown field "relabelings" in com.coreos.monitoring.v1.ServiceMonitor.spec`.

As per https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.ServiceMonitor this field also does not seem to exist. It seems to exist however under `endpoints`, so the following would work:

```yaml
# Source: metallb/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: release-name-metallb-controller-monitor
  labels:
    helm.sh/chart: metallb-0.13.5
    app.kubernetes.io/name: metallb
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.13.5"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: speaker
spec:
  endpoints:
    - port: "metrics"
      honorLabels: true
      relabelings:
        - sourceLabels:
          - somesourcelabel
          targetLabel: sometargetlabel

  jobLabel: "app.kubernetes.io/name"
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      name: release-name-metallb-controller-monitor-service
```

As far as i know the same applies to `metricRelabelings`. I would assume the fix would be to move https://github.com/metallb/metallb/blob/main/charts/metallb/templates/servicemonitor.yaml#L126-L133 a few lines above to the `endpoint` section.

Thank you
