### ISSUE TITLE
feature request: Support for counting assigned IPs in the status field of the IPAddressPool object

### ISSUE THREAD

**Issue by cyclinder** [metallb/metallb#1638]
something like:
```
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: kube-system
spec:
  addresses:
  - 10.6.168.140-10.6.168.150
  autoAssign: true
  avoidBuggyIPs: true
status:
  allocatedIPs:
    10.6.168.140:
       name: test-svc1
       namespace: default
    10.6.168.141:
       name: test-svc2
       namespace: default
     ...
```

@fedepaol any thoughts？ If it make sense, I'm interested in working on it :)
