### ISSUE TITLE
Metallb v0.13.7 - `webhook-service` unavailable

### ISSUE THREAD

**Issue by shanduur-dell** [metallb/metallb#1669]
- The bug itself, as detailed as you can:
  - When applying configuration, I receive an error:

**Error:**
```
Error from server (InternalError): error when creating "/tmp/MetallbConfig-1528688034.yaml": Internal error occurred: failed calling webhook "ipaddresspoolvalidationwebhook.metallb.io": Post "https://webhook-service.metallb-system.svc:443/validate-metallb-io-v1beta1-ipaddresspool?timeout=10s": no endpoints available for service "webhook-service"
```

**IPAddressPool:**
```yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.120-192.168.1.130
```
- Version of MetalLB: `v0.13.7` (installed by manifest)
- Version of Kubernetes: `v1.21.11+5cc9227` (OpenShift: `4.8.51`)
- Name and version of network addon (e.g. Calico, Weave...)
- Whether you've configured kube-proxy for iptables or ipvs mode
