### ISSUE TITLE
load balancer ip sharing doesn't always work the same way

### ISSUE THREAD

**Issue by anubisg1** [metallb/metallb#1682]
- Kubernetes version - v1.25.3 (microk8s)
- MetalLB version - v0.13.3 (official microk8s addon, enabled with "microk8s enable metallb)
- Network Addond - Calico (vxlan overlay mode) v3.23.3  (default version and default config of microk8s)
- Kube-Proxy setup - Not sure, defaullt microk8s setup

Bug / Strange Behaviour

I'm trying to share the same load balancer IP to different services but i find different behaviours.
I have two clusters. the first cluster is using metallb with ARP (i will call it arp cluster) , while the second is using BGP (i will call it bgp cluster).

If it matters in any way, ARP cluster is a mix of ARM64 and AMD64 (ubuntu 22.04) while the BGP cluster is AMD64 only (red hat 8.6) 

the CRD used for the arp cluster are the following:

```
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-addresspool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.0.40-192.168.0.49
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-advertise-all-pools
  namespace: metallb-system
```

The below is the configuration of the BGP cluster instead:

```
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: router1
  namespace: metallb-system
spec:
  myASN: 65012
  passwordSecret:
   name: bgp-password
  peerASN: 65011
  peerAddress: 192.168.223.12
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: router2
  namespace: metallb-system
spec:
  myASN: 65012
  passwordSecret:
    name: bgp-password
  peerASN: 65011
  peerAddress: 192.168.223.13
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-addresspool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.223.10-192.168.223.11
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: bgp-advertise-pool
  namespace: metallb-system
spec:
  ipAddressPools:
  - default-addresspool
```

Now, because of the lack of available ip addresses, i wanted to assign the same IP address to multiple services (of course using different ports).

According to the documentation, the following must be true:

- They both have the same sharing key.
- They request the use of different ports (e.g. tcp/80 for one and tcp/443 for the other).
- They both use the Cluster external traffic policy, or they both point to the exact same set of pods (i.e. the pod selectors are identical)

Based on the documentation, i understand that the "sharing key" is the value of the annotation `metallb.universe.tf/allow-shared-ip:` 

In the case of the ARP cluster, i successfully assign the same IP address to two services, **but i break the last requirement** , as you can see from the manifest below, the selectors are different! the LB does NOT point to the same pod .

Notice, i am not complaining, i am satisfied by being able to do that.

```
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: home-assistant
  annotations:
    metallb.universe.tf/allow-shared-ip: "192.168.0.40"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.40
  selector:
    app: mosquitto
  ports:
  - port: 1883
    targetPort: 1883
---
apiVersion: v1
kind: Service
metadata:
  name: deepstack-lb
  namespace: home-assistant
  annotations:
    metallb.universe.tf/allow-shared-ip: "192.168.0.40"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.40
  selector:
    app: deepstack
  ports:
  - port: 5000
    targetPort: 5000
```

Finally, looking at the "Describe" of the service, i see that the LB ip is announced by the same cluster node `czsrc-lan-srv03` , even if one of the two pods exist on a different node (one on czsrc-lan-srv01 and one on czsrc-lan-srv03) -  again, this is just for information, this is not a complain, but i want to give a full picture

```
anubisg1@czsrc-lan-srv01:~$ kubectl describe svc -n home-assistant mosquitto
Name:                     mosquitto
Namespace:                home-assistant
Labels:                   <none>
Annotations:              metallb.universe.tf/allow-shared-ip: 192.168.0.40
Selector:                 app=mosquitto
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.152.183.64
IPs:                      10.152.183.64
IP:                       192.168.0.40
LoadBalancer Ingress:     192.168.0.40
Port:                     <unset>  1883/TCP
TargetPort:               1883/TCP
NodePort:                 <unset>  32294/TCP
Endpoints:                10.1.152.171:1883
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type    Reason        Age                      From             Message
  ----    ------        ----                     ----             -------
  Normal  nodeAssigned  2m4s (x6503 over 5d18h)  metallb-speaker  announcing from node "czsrc-lan-srv03" with protocol "layer2"


anubisg1@czsrc-lan-srv01:~$ kubectl describe svc -n home-assistant deepstack-lb
Name:                     deepstack-lb
Namespace:                home-assistant
Labels:                   <none>
Annotations:              metallb.universe.tf/allow-shared-ip: 192.168.0.40
Selector:                 app=deepstack
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.152.183.159
IPs:                      10.152.183.159
IP:                       192.168.0.40
LoadBalancer Ingress:     192.168.0.40
Port:                     <unset>  5000/TCP
TargetPort:               5000/TCP
NodePort:                 <unset>  30000/TCP
Endpoints:                10.1.222.172:5000
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type    Reason        Age                       From             Message
  ----    ------        ----                      ----             -------
  Normal  nodeAssigned  2m14s (x3752 over 5d18h)  metallb-speaker  announcing from node "czsrc-lan-srv03" with protocol "layer2"


anubisg1@czsrc-lan-srv01:~$ kubectl get svc -n home-assistant
NAME             TYPE           CLUSTER-IP       EXTERNAL-IP    PORT(S)          AGE
deepstack        ClusterIP      10.152.183.148   <none>         5000/TCP         167d
mosquitto        LoadBalancer   10.152.183.64    192.168.0.40   1883:32294/TCP   167d
deepstack-lb     LoadBalancer   10.152.183.159   192.168.0.40   5000:30000/TCP   29d
deconz           ClusterIP      None             <none>         4080/TCP         46h
zigbee2mqtt      ClusterIP      10.152.183.20    <none>         8080/TCP         167d
node-red         ClusterIP      10.152.183.85    <none>         1880/TCP         167d
octoprint        ClusterIP      None             <none>         80/TCP           45h
home-assistant   ClusterIP      None             <none>         8123/TCP         44h


anubisg1@czsrc-lan-srv01:~$ kubectl get pod -n home-assistant -o wide
NAME                           READY   STATUS    RESTARTS   AGE     IP             NODE              NOMINATED NODE   READINESS GATES
deepstack-84c7bf858d-6ndm9     1/1     Running   0          2d13h   10.1.222.172   czsrc-lan-srv03   <none>           <none>
zigbee2mqtt-684488f576-84bgz   1/1     Running   0          2d11h   10.1.152.162   czsrc-lan-srv01   <none>           <none>
mosquitto-759c5c46f8-kngrd     1/1     Running   0          2d11h   10.1.152.171   czsrc-lan-srv01   <none>           <none>
node-red-54bddb79c8-xtxmp      1/1     Running   0          2d11h   10.1.152.161   czsrc-lan-srv01   <none>           <none>
```

Now, looking at the BGP cluster, this where things are different..

I have 3 services and i want them to have the same IP.

the first two services are logstash, and i want to expost port 514 UDP and TCP to the same pod.
This works fine, manifests are below

```
apiVersion: v1
kind: Service
metadata:
  name: logstash-udp
  namespace: opensearch
  labels:
    app.kubernetes.io/name: eck-logstash
    app.kubernetes.io/component: logstash
  annotations:
    metallb.universe.tf/allow-shared-ip: 192.168.223.10
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.223.10
  externalTrafficPolicy: Local
  ports:
    - name: "udp-syslog"
      port: 514
      targetPort: 8514
      protocol: UDP
  selector:
    app.kubernetes.io/name: eck-logstash
    app.kubernetes.io/component: logstash
---
apiVersion: v1
kind: Service
metadata:
  name: logstash-tcp
  namespace: opensearch
  labels:
    app.kubernetes.io/name: eck-logstash
    app.kubernetes.io/component: logstash
  annotations:
    metallb.universe.tf/allow-shared-ip: 192.168.223.10
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.223.10
  externalTrafficPolicy: Local
  ports:
    - name: "tcp-syslog"
      port: 514
      targetPort: 8514
      protocol: TCP
  selector:
    app.kubernetes.io/name: eck-logstash
    app.kubernetes.io/component: logstash
```

```
NAME                            TYPE           CLUSTER-IP       EXTERNAL-IP      PORT(S)                               AGE
logstash-udp                    LoadBalancer   10.152.183.67    192.168.223.10   514:32648/UDP                         13d
logstash-tcp                    LoadBalancer   10.152.183.21    192.168.223.10   514:31502/TCP                         13d
opensearch-cluster              ClusterIP      10.152.183.117   <none>           9200/TCP,9300/TCP,9600/TCP,9650/TCP   4d4h
opensearch-cluster-discovery    ClusterIP      None             <none>           9300/TCP                              4d4h
opensearch-cluster-masters      ClusterIP      None             <none>           9200/TCP,9300/TCP                     4d4h
opensearch-cluster-nodes        ClusterIP      None             <none>           9200/TCP,9300/TCP                     4d4h
opensearch-cluster-dashboards   ClusterIP      10.152.183.62    <none>           5601/TCP                              4d4h
```

When i try to also configure the third service though, this fails. Manifest below:

```
apiVersion: v1
kind: Service
metadata:
  name: forti-beat
  namespace: opensearch
  annotations:
    metallb.universe.tf/allow-shared-ip: 192.168.223.10
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.223.10
  selector:
    opster.io/name: forti-beat
    opster.io/type: beat
  ports:
    - name: fortinet
      port: 5514
      targetPort: 5514
      protocol: UDP
    - name: fortimanager
      port: 5515
      targetPort: 5515
      protocol: UDP
```

According to the documentation, this should NOT work, because of the different selector. but error logs tells another story, it actually complains about the sharing key

```
 Warning  AllocationFailed  34s   metallb-controller  Failed to allocate IP for "opensearch/forti-beat": can't change sharing key for "opensearch/forti-beat", address also in use by opensearch/logstash-udp,opensearch/logstash-tcp: services can't share key
```

the questions then are:

1. why does one works and the other doesn't? 
2. Why is the requirement about pointing to the same selector is there, and could it be relaxed? 
3. is there anyway i can achieve what i am after with the BGP cluster ?
