### ISSUE TITLE
Support IPAddressPool, L2Advertisiment and BGPAdvertisement CRD configuration in the helm chart

### ISSUE THREAD

**Issue by janaurka** [metallb/metallb#1691]
Since the change from `configmaps` to `CRDs` with `0.13` the helm chart itself cannot configure a very simple configuration using `IPAddressPool` and then either `L2Advertisement` or `BGPAdvertisement`.

In `<0.13` this was supported by setting:

```
configInline:
  address-pools:
  - name: <name>
    protocol: [layer2|bgp]
    addresses:
    - <IP/IPRange>
```

Adding this functionality would allow a proper (non-complicated) deployment which purely rely on the helm chart.
