### ISSUE TITLE
The metallb does not work ok  with both “shared IP” and  "externalTrafficPolicy".

### ISSUE THREAD

**Issue by qiaoenxin** [metallb/metallb#1696]
3. If you're reporting a bug, please specify all of the following:
     - The bug itself, as detailed as you can.
     - Version of MetalLB
     - Version of Kubernetes
     - Name and version of network addon (e.g. Calico, Weave...)
     - Whether you've configured kube-proxy for iptables or ipvs mode

The MetalLB version is v0.13.7. The kubernetes version is "v1.21.4". The network addon is kuber-router(v1.5.2, --run-service-proxy=false).

### The service A:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: test-nginx
  annotations:
    metallb.universe.tf/allow-shared: "test-shareip"
spec:
  ports:
    - port: 80
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: nginx

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
   replicas: 1
   selector:
     app: nginx
   template:
     metadata:
       labels:
         app: nginx
     spec:
       containers:
       - name: nginx
         image: nginx
```
### The service B:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: test-nginx2
  annotations:
    metallb.universe.tf/allow-shared: "test-shareip"
spec:
  ports:
    - port: 83
      targetPort: 80
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: nginx2

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx2
spec:
   replicas: 1
   selector:
     app: nginx2
   template:
     metadata:
       labels:
         app: nginx2
     spec:
       containers:
       - name: nginx
         image: nginx
```
The metallb configuration :
```yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.11.110-192.168.11.110
  
  
---

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool
  interfaces:
    - ens33
```

### The issue:
**The two pods is running on the different nodes, but the "External IP" is in pending.** 
![image](https://user-images.githubusercontent.com/9695147/200989334-7ab92c50-2a77-400a-9776-e366fa637bf8.png)

### NOTE:
Step1, I manually add the same external IP for the two services. 
![image](https://user-images.githubusercontent.com/9695147/200993031-2bfea64a-2b48-4d74-be11-98329c853f22.png)

Step2, I manually add ipvs for the two services on the external LB server.  It works ok.
![image](https://user-images.githubusercontent.com/9695147/200993071-a8f2da82-5bbe-4f81-ab4f-9b71a84a4e15.png)

![image](https://user-images.githubusercontent.com/9695147/200993333-a0e5ba4c-bea9-4061-937d-a09843a04177.png)
