### ISSUE TITLE
Cannot access service from outside of cluster

### ISSUE THREAD

**Issue by MartinPham** [metallb/metallb#1699]
Hi everyone, thanks for your awesome contribution!
I'm having a weird problem that I couldn't solve it. Where I deployed MetalLB (L2), it assigned IP to my service. But I can only access this service if I'm inside the cluster network.

- K8s version: v1.25.3
- MetalLB version: 0.13.7
- Network: Flannel v0.20.1

I've configured IP pool and advertisement like this
```
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-pool
  namespace: metallb-system
spec:
  addresses:
  - 144.24.239.60-144.24.239.60
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-adv
  namespace: metallb-system
spec:
  ipAddressPools:
  - ip-pool
```

Then deloyment & service like this
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
```

kubectl get svc gave me:

```
NAME            TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)        AGE
kubernetes      ClusterIP      10.96.0.1       <none>          443/TCP        29m
nginx-service   LoadBalancer   10.105.231.93   144.24.239.60   80:32038/TCP   11m
```

Now when I try to access the service, on nodes, it works:
```
curl 144.24.239.60
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

But if I try from outside, it gave me error
```
curl 144.24.239.60
curl: (7) Failed to connect to 144.24.239.60 port 80 after 27 ms: Connection refused
```

Could you please help me to check maybe I was wrong somewhere?

Thank you very much!
