### ISSUE TITLE
CriticalAddonsOnly toleration

### ISSUE THREAD

**Issue by carlocorradini** [metallb/metallb#1737]
Context: issue #814 and K3s issue https://github.com/k3s-io/k3s/issues/1402

What do you think if we add `CriticalAddonsOnly` to `tolerations`?
```yaml
spec:
  template:
    spec:
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        # ...
```

Note: The `master` (controller) node has been tainted with `CriticalAddonsOnly=true:NoExecute`
