### ISSUE TITLE
Cannot get ipv6 address

### ISSUE THREAD

**Issue by withinboredom** [metallb/metallb#1742]
Problem:

Customer requires ipv6 connectivity

Setup:

- cilium (ipv4, ipv6) [v1.12.2]
- kubernetes [v1.24.8+k3s1]
- metallb [docker.io/bitnami/metallb-controller:0.13.7-debian-11-r0]

Verified:

- ipv6 connectivity to/from pods
- ipv6 connectivity outside the cluster
- speakers have ipv6 connectivity

Related

- #1589 -- can just remove ipv6 address as a workaround for now
- #157 -- utilizing an ipam, but doesn't impact bug

Applied a service with:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: example
  namespace: example
annotations:
    metallb.universe.tf/loadBalancerIPs: XX.XX.XX.XX,XXXX:XXX:XX:XXXX::1000
spec:
  type: LoadBalancer
  ipFamilyPolicy: PreferDualStack
```

I see the following error:
```
2022-12-12 11:44:33 | {"caller":"service.go:140","error":"requested loadBalancer IP(s) [\"XX.XX.XX.XX\" \"XXXX:XXX:XX:XXXX::1000\"] does not match the ipFamily of the service","level":"error","msg":"IP allocation failed","op":"allocateIPs","ts":"2022-12-12T10:44:33Z"}
```

May impact bug:

- underlying kubernetes cluster is ancient, and only configured for ipv4. We're utilizing cilium to get ipv6 connectivity.

Possible workarounds:

- Can fallback to ipv4 addresses for external communications, as mentioned earlier
- IPv6 addresses are global addresses in this cluster, so theoretically can add DNS entries directly to the pods, though that sounds like a terrible idea.
