### ISSUE TITLE
Unable to access minikube cluster from external ip

### ISSUE THREAD

**Issue by entrymon** [metallb/metallb#1763]
Steps to reproduce.

- Setup minikube cluster with 2 nodes
 ```minikube start --memory=4096 --cpus=2 --nodes=4 --driver=docker```

- Edit kube-proxy config map
```kubectl get configmap kube-proxy -n kube-system -o yaml | sed -e "s/strictARP: false/strictARP: true/" | kubectl apply -f - -n kube-system```

- Setup metallb 
```
    - helm repo add metallb https://metallb.github.io/metallb
    - helm repo update
    - kubectl create namespace metallb
    - helm install my-metallb metallb/metallb --version 0.13.7
```

- Setup configmap to set external ip 
```
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: production
  namespace: metallb
spec:
  # Production services will go here. Public IPs are expensive, so we leased
  # just 4 of them.
  addresses:
  - 192.168.49.2/32
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: external
  namespace: metallb
spec:
  ipAddressPools:
  - production
 ```

- Setup istio
```
    - helm repo add istio https://istio-release.storage.googleapis.com/charts
    - helm repo update
    - kubectl get ns | grep -c "^istio-system " || kubectl create namespace istio-system
    - helm upgrade --install istio-base istio/base -n istio-system --create-namespace --wait
    - helm upgrade --install istiod istio/istiod -n istio-system --create-namespace --wait
    - kubectl get ns | grep -c "^istio-ingress " || kubectl create namespace istio-ingress
    - kubectl label namespace istio-ingress istio-injection=enabled
    - helm upgrade --install istio-ingressgateway istio/gateway -n istio-ingress --wait
 ```

- Observer IP address on istio srv shows up
 
```
kubectl get svc -n istio-ingress

NAME                              TYPE               CLUSTER-IP       EXTERNAL-IP    PORT(S)                                      AGE
istio-ingressgateway   LoadBalancer   10.100.159.184   192.168.49.2   15021:31299/TCP,80:30497/TCP,443:31846/TCP   91m
```

- minikube ip is same as EXTERNAL-IP
```
192.168.49.2
```

- Now setup any test app edit /etc/hosts to point 
``` 
192.168.49.2 test.sampledomain.com
```

- try to curl 
```
curl http://test.sampledomain.com
```
And it works **but when I try to access it from other machine using DNS it does not work.**

I have a static public ip on this server and have configured DNS pointing to the IP of this server but it does not seem to work. This is not a public cloud but this is bare metal server with static ip. 

Do we need to route and change IPTables to make this work? Any other elegant solution?

Appreciate help to fix the issue.
