### ISSUE TITLE
ERROR: No installed keys could decrypt the message

### ISSUE THREAD

**Issue by willkara** [metallb/metallb#1768]
Installed on Ubuntu 22.04 on an RPi

`Linux pleiades-1.willkara 5.15.0-1021-raspi #23-Ubuntu SMP PREEMPT Fri Nov 25 15:27:43 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux`

microk8s with Kubernetes version 1.25.4

When I try installing Metallb through the manifest file and then apply an L2 IP Address pool config, I never have luck in metallb connecting to LoadBalancer services and generating an ExternalIP.

After some debugging, I started looking at the logs for the speaker pod and saw this issue:

`{"caller":"net.go:268","component":"Memberlist","level":"error","msg":"memberlist: failed to receive: No installed keys could decrypt the message from=192.168.1.119:55534","ts":"2023-01-05T18:22:33Z"}`

After some Google-Fu, it seems like there's a common issue on metallb configs. I've tried searching for solutions and even tried recreating the pods to hopefully regenerate a cert connection (give from another GitHub issue), but no luck,.

**Comment by darkmuggle** [comment]
I'm hitting the same problem on Ubuntu 20.04 and Ubuntu 22.04 on ARM64 (not RPi - 80 cores, 256GB RAM hosts) and AMD64 on Ubuntu 20.04. I have seen this problem on Kubernetes 1.23.5 and 1.26.0. All environments are using Calico. 

The only work around I've found is to have a cronjob to delete the pods in the `metallb-system` namespace. Each cluster has 18 or so hosts and there doesn't seem to be a reason. 

```
│ {"caller":"config_controller.go:150","controller":"ConfigReconciler","event":"config reloaded","level":"info","ts":"2023-01-06T16:42:05Z"}                   │
│ {"caller":"config_controller.go:151","controller":"ConfigReconciler","end reconcile":"/ampere-kv-12","level":"info","ts":"2023-01-06T16:42:05Z"}             │
│ {"caller":"main.go:344","event":"serviceAnnounced","ips":["10.25.116.94"],"level":"info","msg":"service has IP, announcing","pool":"kubert","protocol":"laye │
│ {"caller":"main.go:344","event":"serviceAnnounced","ips":["10.25.116.51"],"level":"info","msg":"service has IP, announcing","pool":"kubert","protocol":"laye │
│ {"caller":"main.go:344","event":"serviceAnnounced","ips":["10.25.116.98"],"level":"info","msg":"service has IP, announcing","pool":"kubert","protocol":"laye │
│ {"caller":"service_controller_reload.go:103","controller":"ServiceReconciler - reprocessAll","end reconcile":"metallbreload/reload","level":"info","ts":"202 │
│ {"caller":"service_controller_reload.go:61","controller":"ServiceReconciler - reprocessAll","level":"info","start reconcile":"metallbreload/reload","ts":"20 │
│ {"caller":"main.go:344","event":"serviceAnnounced","ips":["10.25.116.94"],"level":"info","msg":"service has IP, announcing","pool":"kubert","protocol":"laye │
│ {"caller":"main.go:344","event":"serviceAnnounced","ips":["10.25.116.51"],"level":"info","msg":"service has IP, announcing","pool":"kubert","protocol":"laye │
│ {"caller":"main.go:344","event":"serviceAnnounced","ips":["10.25.116.98"],"level":"info","msg":"service has IP, announcing","pool":"kubert","protocol":"laye │
│ {"caller":"service_controller_reload.go:103","controller":"ServiceReconciler - reprocessAll","end reconcile":"metallbreload/reload","level":"info","ts":"202 │
│ {"caller":"speakerlist.go:310","level":"info","msg":"node event - forcing sync","node addr":"10.25.58.22","node event":"NodeJoin","node name":"ampere-kv-14" │
│ {"caller":"service_controller_reload.go:61","controller":"ServiceReconciler - reprocessAll","level":"info","start reconcile":"metallbreload/reload","ts":"20 │
│ {"caller":"main.go:344","event":"serviceAnnounced","ips":["10.25.116.98"],"level":"info","msg":"service has IP, announcing","pool":"kubert","protocol":"laye │
│ {"caller":"main.go:344","event":"serviceAnnounced","ips":["10.25.116.94"],"level":"info","msg":"service has IP, announcing","pool":"kubert","protocol":"laye │
│ {"caller":"main.go:344","event":"serviceAnnounced","ips":["10.25.116.51"],"level":"info","msg":"service has IP, announcing","pool":"kubert","protocol":"laye │
│ {"caller":"service_controller_reload.go:103","controller":"ServiceReconciler - reprocessAll","end reconcile":"metallbreload/reload","level":"info","ts":"202 │
│ {"caller":"node_controller.go:42","controller":"NodeReconciler","level":"info","start reconcile":"/ampere-kv-09","ts":"2023-01-06T16:42:07Z"}                │
│ {"caller":"speakerlist.go:271","level":"info","msg":"triggering discovery","op":"memberDiscovery","ts":"2023-01-06T16:42:07Z"}                               │
│ {"caller":"node_controller.go:64","controller":"NodeReconciler","end reconcile":"/ampere-kv-09","level":"info","ts":"2023-01-06T16:42:07Z"}                  │
│ {"caller":"memberlist.go:268","component":"Memberlist","level":"warn","msg":"memberlist: Failed to resolve : lookup : no such host","ts":"2023-01-06T16:42:0 │
│ {"caller":"speakerlist.go:256","error":"1 error occurred:\n\t* Failed to resolve : lookup : no such host\n\n","expected":1,"joined":0,"level":"error","msg": │
│ W0106 16:42:18.854718       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool                                     │
│ W0106 16:42:19.779405       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool                                     │
│ W0106 16:42:19.780254       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
```

My configs:
```
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: metallb-system
spec:
  ipAddressPools:
   - default

---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb-system
spec:
  addresses:
   - 10.25.59.50-10.25.59.200


---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: kubert
  namespace: metallb-system
spec:
  ipAddressPools:
   - kubert

---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: kubert
  namespace: metallb-system
spec:
  addresses:
   - 10.25.118.50-10.25.119.200
```
