### ISSUE TITLE
advertise multiple ip's, through several nodes?

### ISSUE THREAD

**Issue by migs35323** [metallb/metallb#1800]
I have 4 machines. each one has a single "external ip" provided by the server provider
is there a way to make metal lb advertise through the 4 external ip at the same time?
the k3s default load balancer kinda does this but in a very limited way
i tried to setup several address pools and specify each address for each node but the service is allocating only one ip in one single node, i'd like to reach the service trough any of the 4 public ip's

i also tried to use the metallb.universe.tf/loadBalancerIPs label but it happears its only for dual stack?

**Comment by fedepaol** [comment]
what you can do is to have multiple services baked by the same set of endpoints (meaning, having the same pod selector). By doing that, you'll be able to specify different properties for each service, including the node selector from where to announce it and the ip to announce to it.

Closing this as not an issue.

**Comment by ginn13** [comment]
hello, team. Say I have a single IPAddressPool with 3 addresses and L2Advertisement
```
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: proj-dev-pool
  namespace: operators
spec:
  addresses:
    - 10.120.188.219/32
    - 10.120.188.220/32
    - 10.120.188.221/32
```
```
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: proj-dev
  namespace: operators
spec:
  ipAddressPools:
    - proj-dev-pool
```
I have an Nginx Ingress Controller and I want to advertise all three ExternalIPs for the Service, just like an author of this thread.
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/11777877/217519529-ad8ea4ff-887e-4a6f-8cd0-9075d49192bf.png">
The problem is that first service is managed by helm chart of ingress controller, the last two Services I have to create manually to obtain more ExternalIPs.

If there are some changes to first service (for example one more port added), I have to repeat them manually to the rest two services. It could be more useful to have singe service and three ExternalIPs assigned to it. 

Does this possible feature contradicts to MetalLB architecture in some way?
