### ISSUE TITLE
LoadBalancer IP is unreachable with MetalLB upgraded to v0.13.7

### ISSUE THREAD

**Issue by xqdada** [metallb/metallb#1828]
When upgraded metallb to v0.13.7, I will'not be able to ping loadbalancer ip(ping 172.20.5.200/201) but internet connection in the browser,Use helm install.The following is the detailed information:

kubernetes: v1.26.0
calcio: v3.24.5
metallb: v0.13.7
kube-proxy: ipvs

configure content(metallb-config.yaml ):

```
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb-system
spec:
  addresses:
  - 172.20.5.200-172.20.5.201
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-ad
  namespace: metallb-system
spec:
  ipAddressPools:
  - default
```

issues detail:

1.ping loadbalancer ip in centos 7
![图片](https://user-images.githubusercontent.com/21285054/217417658-ea5c4b79-dbfa-4310-9f02-7c25eccada14.png)

2.in browser
![图片](https://user-images.githubusercontent.com/21285054/217418095-74186571-af63-4a8f-b626-572910f68d47.png)
