### ISSUE TITLE
Adding support for ip address range in reverse

### ISSUE THREAD

**Issue by vincent5753** [metallb/metallb#1856]
I had a cluster that I wanted to deploy metallb with yaml like this
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      auto-assign: true
      addresses:
      - 10.0.0.6-10.0.0.5
```

But the metallb failed deploying with the above ip ranges, until I changed the ip like following
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      auto-assign: true
      addresses:
      - 10.0.0.5-10.0.0.6
```

I think that it would be nice to have support for ip address range in reverse?
