### ISSUE TITLE
K3S: Disable Klipper

### ISSUE THREAD

**Issue by userbradley** [metallb/metallb#1871]
Hey,

I have a documentation site I maintain and on there, I put together a page on how to disable klipper on k3s after the fact (as I forgot to when it came to installing metallb)

I thought I would open an issue and see if you would accept a PR linking to this document, before I spend time creating one etc

[Disabling Klipper](https://documentation.breadnet.co.uk/kubernetes/k3s/disable-klipper/)

Let me know

**Comment by fedepaol** [comment]
sorry for the delay (and for the ignorance), mind expanding the need for disabling it?
And in any case, I'd rather accept a PR that adds the instructions directly to the docs instead of a link to the external page.

**Comment by userbradley** [comment]
Sure, so on K3s, klipper comes installed by default, and requires you to have it disabled from cluster creation.

I didn't RTFM properly the first time and had it still installed, so had issues. 

I would look to add the instructions to [configuration/k3s](https://metallb.universe.tf/configuration/k3s/)

This is more just a quality of life thing, as you can chose to uninstall k3s and reinstall it with the provided flag, or you can do it on the fly.

**Comment by rex-structorum** [comment]
Hello @fedepaol.  I am trying (unsuccessfully so far) to get MetalLB working with K3s on a local, single-node install.  The [documentation page you referenced](https://metallb.universe.tf/configuration/k3s) has instructions for disabling the K3s ServiceLB.

The K3s configuration caveat in the docs gave me the impression that K3s has been tried/tested against MetalLB, but I'm getting the impression from this issue that those instructions were just added?  Have you or any contributors been successful using MetalLB with K3s?

**Comment by userbradley** [comment]
Hi @rex-structorum - I opened this issue as when I installed metallb I didn't RTFM properly, and needed a way after the fact to disable the built in service.

I can assure you this works and is battle tested. Any questions I'd be happy to answer

**Comment by rex-structorum** [comment]
Thanks for the offer.  Was this page (https://metallb.universe.tf/configuration/k3s) present in the docs before you opened this issue?  Did you change or disable any other networking components of K3s, such as Traefik?

My latest attempt is as such:

Using local, wired wired network with a VyOS router (192.168.1.1) and Ubuntu 22.04 (192.168.1.10) for the single K3s node.

### Ubuntu 22.04:
- Firewall is disabled
- Enabled IP forwarding (I didn't see this in the docs but I assume is necessary?) in sysctl.conf: `net.ipv4.ip_forward=1`

### K3s Install arguments:
- --cluster-cidr=10.42.0.0/16
- --service-cidr=10.43.0.0/16
- --disable=servicelb

By default, K3s has kube-proxy with `--proxy-mode iptables`, so `--ipvs-strict-arp` is not necessary.

### Post install:
1. kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.10/config/manifests/metallb-native.yaml
2. kubectl apply -f metallb-config.yaml

(I have also tried `metallb-frr.yaml`, with same results)

File metallb-config.yaml
```yaml
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: address-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.44.0.0/16
  avoidBuggyIPs: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: metallb-system
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: bgp-peer
  namespace: metallb-system
spec:
  myASN: 4200000000
  peerASN: 4200000000
  peerAddress: 192.168.1.1
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: bgp-advertisement
  namespace: metallb-system
```

### Testing (with other Linux host, 192.168.1.11):
- kubectl apply -f nginx.yaml
- metallb assigns the pod IP 10.44.0.1
- from K3s node: `curl 10.44.0.1` works OK
- from other host: `arping 10.44.0.1`, from K3s node: `tcpdump -n arp host 192.168.1.11` I see K3s node MAC on both shells OK
- on VyOS router I configure BGP peering with MetalLB, can see IP advertisement 10.44.0.1 for Nginx pod OK
- see route 10.44.0.1 installed in VyOS main route table OK
- on other host: `traceroute 10.44.0.1` looks like some kind of BGP loop?
    > 192.168.1.1
    > 192.168.1.10
    > 192.168.1.1
    > 192.168.1.10
- So I delete BGP peering & advertisements in MetalLB to test with only L2, temporarily.
- Disable BGP peering in VyOS and install static route to `10.44.0.0/16` via 192.168.1.10
- Still nothing.  I'm perplexed how `curl` even works on the K3s node itself, as I don't see any local routes installed for `10.44.0.0/16`

I still cannot curl the Nginx pod from another host.  Traceroute

(I have also tried with `externalTrafficPolicy: Cluster`, with same results)

File nginx.yaml:
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
  externalTrafficPolicy: Local
```

**Comment by rex-structorum** [comment]
I have also tries using different ASNs for MetalLB and VyOS

**Comment by userbradley** [comment]
I am not using BGP on my configuration, so my knowledge there is limited (I rent so have minimal space for a cool router)

I have the below config set up for my k3s cluster

```conf
ExecStart=/usr/local/bin/k3s \
    server \
        '--datastore-endpoint' \
        'etcd' \
        '--disable' \
        'servicelb' \
        '--disable' \
        'traefik' \
        '--bind-address' \
        '172.16.2.0' \
        '--advertise-address' \
        '172.16.2.0' \
        '--tls-san' \
        '172.16.2.0' \
        '--cluster-domain' \
        'cluster.bread' \
```

So I have disabled `servicelb` and `traefik`

I have installed the `nginx` ingress manager to manage the hostname stuff, so I have the below config 

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: documentation
  annotations:
    metallb.universe.tf/address-pool: pool
spec:
  ingressClassName: "nginx"

  rules:
    - host: documentation.breadnet
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: documentation
                port:
                  number: 80
```

This seems to work for me.

Now as far as the traceroute goes, that is interesting, but when I ping an IP address that is assigned to a service

```shell
➜ k get svc                                                                                  
NAME              TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
mealie-backend    ClusterIP      10.43.67.30    <none>        9000/TCP       114d
mealie-frontend   LoadBalancer   10.43.64.79    172.16.0.6    80:32750/TCP   114d
mealie-internal   ClusterIP      10.43.97.254   <none>        80/TCP         114d
```

```shell
➜ ping 172.16.0.6                                                                            
PING 172.16.0.6 (172.16.0.6): 56 data bytes
Request timeout for icmp_seq 0
92 bytes from 172.16.2.1: Redirect Host(New addr: 172.16.0.6)
Vr HL TOS  Len   ID Flg  off TTL Pro  cks      Src      Dst
 4  5  00 0054 cb46   0 0000  3f  01 54a4 172.16.3.152  172.16.0.6 

Request timeout for icmp_seq 1
92 bytes from 172.16.2.1: Redirect Host(New addr: 172.16.0.6)
Vr HL TOS  Len   ID Flg  off TTL Pro  cks      Src      Dst
 4  5  00 0054 5dd8   0 0000  3f  01 c212 172.16.3.152  172.16.0.6 

Request timeout for icmp_seq 2
92 bytes from 172.16.2.1: Redirect Host(New addr: 172.16.0.6)
Vr HL TOS  Len   ID Flg  off TTL Pro  cks      Src      Dst
 4  5  00 0054 87e5   0 0000  3f  01 9805 172.16.3.152  172.16.0.6 

^C
--- 172.16.0.6 ping statistics ---
4 packets transmitted, 0 packets received, 100.0% packet loss

```

I get loss, but the site loads: 
<img width="1410" alt="image" src="https://github.com/metallb/metallb/assets/41597815/4994191a-471f-47bc-bf99-120ada2bd5b3">


I couldnt really find a good description on why pinging the IP address is wonky, but I would assume it's something to do with the FRR and the fact there is a single listener pod that then sends traffic internal to the cluster.

Can you try without the BGP, using a config similar to this?

```yaml
---
# Source: metallb/templates/ippool.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool
spec:
  addresses:
    - 172.16.0.2-172.16.0.128 # obvs change this to your IP ranve
---
# Source: metallb/templates/ippool.yaml
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: pool-advertisement
spec:
  ipAddressPools:
    - pool
```

Then install the nginx ingress controller and use the example I provided above

---

Finally to answer your question:

> Was this page (https://metallb.universe.tf/configuration/k3s) present in the docs before you opened this issue? 

Yes, it's always been there, for about 2 years I think? 

https://github.com/metallb/metallb/commit/2df3ba4a293684c0f6e868333c4ddf14aa4795d5

I hope this helps somewhat and isnt too rambly
