### ISSUE TITLE
Helm chart repository is unavailable

### ISSUE THREAD

**Issue by waahhhh** [metallb/metallb#1886]
The Helm chart repository "https://metallb.github.io/metallb" is unavailable.

Section from the documentation https://metallb.universe.tf/installation/#installation-with-helm:
> helm repo add metallb https://metallb.github.io/metallb
> helm install metallb metallb/metallb

There is only one similar issue, but that from last year #1574.

**Comment by userbradley** [comment]
When you say _ unavailable_ what do you mean?

I can curl the `index.yaml` file just fine

```yaml
➜ curl https://metallb.github.io/metallb/index.yaml                          
apiVersion: v1
entries:
  metallb:
  - apiVersion: v2
    appVersion: v0.13.9
    created: "2023-02-21T10:05:47.527957958Z"
    dependencies:
    - condition: crds.enabled
      name: crds
      repository: ""
      version: 0.13.9
    description: A network load-balancer implementation for Kubernetes using standard
      routing protocols
    digest: acf9c7f0430e71e000b2cf63836693bf4aa7dba0563f95dade91b28d56666022
    home: https://metallb.universe.tf
    icon: https://metallb.universe.tf/images/logo/metallb-white.png
    kubeVersion: '>= 1.19.0-0'
    name: metallb
    sources:
    - https://github.com/metallb/metallb
    type: application
    urls:
    - https://github.com/metallb/metallb/releases/download/metallb-chart-0.13.9/metallb-0.13.9.tgz
    version: 0.13.9

```
