### ISSUE TITLE
Metallb L2 duplicate mac

### ISSUE THREAD

**Issue by jackcarver-a** [metallb/metallb#1890]
Hey,

When using metallb in layer2 mode, I noticed strange behavior. There is a deployment (1 pod) and a service loadbalancer with an externalTrafficPolicy: Local policy. When the pod moves to another node, inaccessibility periodically occurs (15-20 minutes).  Switch is experiencing the error: ACI has detected multiple MACs using the same IP address XX.XX.XX.XX.

manifest:
```
local-metallb.yaml 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb-deploy
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: lb
  template:
    metadata:
      labels:
        app: lb
    spec:
      containers:
        - name: my-echo
          image: gcr.io/google_containers/echoserver:1.8

---
apiVersion: v1
kind: Service
metadata:
  name: lb-service3
  annotations:
    external-dns.alpha.kubernetes.io/hostname: example.hostname.com
spec:
  externalTrafficPolicy: Local
  selector:
    app: lb
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer

```

```
kubectl describe svc lb-service3 
Name:                     lb-service3
Namespace:                default
Labels:                   <none>
Annotations:              external-dns.alpha.kubernetes.io/hostname:  example.hostname.com
Selector:                 app=lb
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       XX.XX.XX.XX
IPs:                      XX.XX.XX.XX
LoadBalancer Ingress:     XX.XX.XX.XX
Port:                     <unset>  8080/TCP
TargetPort:               8080/TCP
NodePort:                 <unset>  32113/TCP
Endpoints:                XX.XX.XX.XX:8080
Session Affinity:         None
External Traffic Policy:  Local
HealthCheck NodePort:     31517
Events:
  Type    Reason        Age                  From             Message
  ----    ------        ----                 ----             -------
  Normal  nodeAssigned  11s (x107 over 23h)  metallb-speaker  announcing from node "k8s5.example.local"
  Normal  nodeAssigned  10s (x77 over 23h)   metallb-speaker  announcing from node "k8s4.example.local"

```
versions:
k8s: v1.23.2
metallb: v0.12.1
calico: v3.20.3
crio: 1.22.5
OS: OEL 8.6 kernel 5.4.17-2136.307.3.5.el8uek.x86_64
