### ISSUE TITLE
Outside the cluster cannot access services in the k8s cluster through EXTERNAL-IP

### ISSUE THREAD

**Issue by a365541453** [metallb/metallb#1902]
I am deploying a K8S cluster on VMware workstation, and after deploying metallb，
the terminals outside the cluster cannot access the services in the k8s cluster through EXTERNAL-IP,
but the terminals in the cluster can be accessed normally through curl

Does metallb not support VMware workstation environments? or where did I go wrong

MetalLB Version : controller:v0.13.9  speaker:v0.13.9
Kubernetes Version : v1.26.2
network addon : Calico

**Comment by csawtelle** [comment]
I am experiencing this same issue except I am using flannel on physical machines 

MetalLB Version : controller:v0.13.9 speaker:v0.13.9
Kubernetes Version : v1.26.3
network addon : Flannel

**Comment by rniranjan89** [comment]
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.240-192.168.1.250


apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example
  namespace: metallb-system


@csawtelle @a365541453 I hope you applied both IPAddressPool and L2Advertisement?

https://metallb.universe.tf/configuration/

**Comment by a365541453** [comment]
> @a365541453 did you follow the troubleshooting guide?

Yes, I installed it using the method on "Installation By Manifest", which didn't work on VMware workstations, but it worked on physical environments, and I asked my friends around me and they didn't know why

**Comment by a365541453** [comment]
> apiVersion: metallb.io/v1beta1 kind: IPAddressPool metadata: name: first-pool namespace: metallb-system spec: addresses:
> 
> * 192.168.1.240-192.168.1.250
> 
> apiVersion: metallb.io/v1beta1 kind: L2Advertisement metadata: name: example namespace: metallb-system
> 
> @csawtelle @a365541453 I hope you applied both IPAddressPool and L2Advertisement?
> 
> https://metallb.universe.tf/configuration/

this is my yaml
```
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.222.170-192.168.222.179
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool
```
