### ISSUE TITLE
Helm chart should have possibility to add Pod Security labels on namespace

### ISSUE THREAD

**Issue by djkormo** [metallb/metallb#1932]
Metallb version 0.13.9 installed via helm chart 

How using only helm chart installed via pipeline to add labels for Pod Security? 

On the namespace object level it should be like that:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: metallb-system
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: privileged
  name: metallb-system
```  

According to documentation  https://metallb.universe.tf/installation/

Imperative approach via patching namespace is from my point of view unaccepted.
