### ISSUE TITLE
How can i visit loandbance IP by different  network segment？

### ISSUE THREAD

**Issue by liaoqiArno** [metallb/metallb#1953]
my k8s cluster network segment is "10.0.100.0/24"
 ```
10.0.100.115   Ready,SchedulingDisabled   master   154m   v1.26.0
10.0.100.116   Ready                      node     154m   v1.26.0
10.0.100.117   Ready                      node     154m   v1.26.0
10.0.100.127   Ready,SchedulingDisabled   master   154m   v1.26.0
10.0.100.135   Ready,SchedulingDisabled   master   154m   v1.26.0
10.0.100.136   Ready                      node     154m   v1.26.0
```
my computer (my browser) ip is “10.0.37.210”，and can visit   "10.0.100.0/24",the network is ok.

I set ip pool:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: config
  namespace: metallb-system
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.0.100.141-10.0.100.145
```
if I set my svc loadbalance port is 80,I can't use my computer visit it.But if set port other port , I can visit, 
Please help.
