### ISSUE TITLE
frr does not peer with 127.0.0.1 

### ISSUE THREAD

**Issue by gclawes** [metallb/metallb#1966]
With the original speaker implementation, metallb can be peered with calico over localhost to have calico propagate metallb's routes to upstream routers (both calico and metallb cannot peer with the upstream routers at once).  This mode does not work with `frr` enabled.

For example, with the following configuration and `.Values.speaker.rff.enabled == false`:
```
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: default
spec:
  ipAddressPools:
  - default
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: calico
spec:
  myASN: 65003
  peerASN: 65002
  peerAddress: 127.0.0.1
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
spec:
  addresses:
  - 10.102.0.0/16
```

Calico shows a peering connection with 127.0.0.1:
```
[root@pi02 /]# birdcl -s /var/run/calico/bird.ctl sh pr
BIRD v0.3.3+birdv1.6.8 ready.
name     proto    table    state  since       info
static1  Static   master   up     2023-05-31
kernel1  Kernel   master   up     2023-05-31
device1  Device   master   up     2023-05-31
direct1  Direct   master   up     2023-05-31
Global_127_0_0_1 BGP      master   up     00:22:18    Established
Global_10_10_0_1 BGP      master   up     2023-05-31  Established
```

And routes are propagated to upstream router:
```
# birdc4 sh route | grep pi | grep 32
10.102.0.53/32     via 10.10.5.102 on lan4.5 [pi02 20:22:18] * (100) [AS65003i]
10.102.0.0/32      via 10.10.5.103 on lan4.5 [pi03 20:22:39] * (100) [AS65003i]
```

Using FRR with the same metallb CRs, the `127.0.0.1` connection is not established with calico:
```
[root@pi02 /]# birdcl -s /var/run/calico/bird.ctl sh pr
BIRD v0.3.3+birdv1.6.8 ready.
name     proto    table    state  since       info
static1  Static   master   up     2023-05-31
kernel1  Kernel   master   up     2023-05-31
device1  Device   master   up     2023-05-31
direct1  Direct   master   up     2023-05-31
Global_127_0_0_1 BGP      master   start  00:34:52    Connect       Socket: Connection closed
Global_10_10_0_1 BGP      master   up     2023-05-31  Established
```

Granted, this is not one of the documented ways to work with calico (https://metallb.universe.tf/configuration/calico/), but it is a case where gobgp speaker and frr don't have the same behavior for the same config.
