### ISSUE TITLE
Feature Request: Support for static assignment of IP addresses

### ISSUE THREAD

**Issue by yellowpattern** [metallb/metallb#1978]
In https://bugzilla.redhat.com/show_bug.cgi?id=1989700 there's a description of a scenario that I'd like to experiment with and if it is not supported then I'd like to ask for it to be.

The goal: have metalLB manage IPAddressPools that have a single IP address in them and be able to assign those to services that have the address pool name configured in their manifest.

That is I'd like to declare my IPAddressPool like this:

```
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: my-static-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.0.0.1/32
  autoAssign: false
  protocol: bgp
```

And then reference it from a service like this:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: my-static-pool
spec:
  type: LoadBalancer
```

I don't want to have to put the IP address in more than one place (primarily because it makes it harder to re-use the service manifest in different namespaces/environments.)
