### ISSUE TITLE
Unable to connect to services after upgrading to v0.13.10

### ISSUE THREAD

**Issue by Slyke** [metallb/metallb#1989]
1. Tried to sign up to the Slack, but got the error "XYZ@gmail.com doesn’t have an account on this workspace." and that I need to contact an admin.
2. Yup, have searched.
3. If you're reporting a bug, please specify all of the following:

**The bug itself, as detailed as you can:**

1. Upgraded from `v0.9.6` to `v0.13.10`
2. Changed config files to match new config format.
3. When running `kubectl get svc` I can see that the services are being assigned their correct External-IP addresses as specified in the service yml:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodered-automation
  name: nodered-automation
  namespace: nodered
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.1.2.3 # Example IP
spec:
  # externalTrafficPolicy: Local
  ports:
  - name: nodered-au-http
    protocol: TCP
    port: 1880
  - name: nodered-au-http2
    protocol: TCP
    port: 80
    targetPort: 1880
  selector:
    app: nodered-automation
  type: LoadBalancer
```

5. No errors reported in the metallb-controller pod
6. No errors in the speaker pods, but I do see `{"caller":"announcer.go:76","event":"announced interface to exclude","interface":"veth356cc09a","level":"info","ts":"2023-06-27T08:19:05Z"}`
7. When sshing into the node itself and running `ifconfig`, I can see that the veths are getting an IPv6 address, but not an IPv4 address:
```
veth356cc09a: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet6 fe80::30c3:fcff:fea8:f4a6  prefixlen 64  scopeid 0x20<link>
        ether b6:83:ae:7f:d5:81  txqueuelen 0  (Ethernet)
        RX packets 18  bytes 1328 (1.3 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 12957  bytes 778718 (778.7 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
8. When running `arping -I eth0 10.1.2.3` from same LAN, the node's terminal, or a pod running on that node, no responses are returned.

     - Version of MetalLB: v0.13.10
     - Version of Kubernetes: 1.23.4
     - Name and version of network addon: Flannel

Also, a side note (let me know if I should submit a bug for this), some of my pods have multiple services with the same IP, one service for TCP, and the other for UDP, when updating either of the services, the metallb controller reports this error: `{"caller":"service.go:135","error":"can't change sharing key for \"my-namespace/my-pod\", address also in use by my-namespace/my-pod-udp","level":"error","msg":"IP allocation failed","op":"allocateIPs","ts":"2023-06-27T08:18:52Z"}` and the IP fails to be allocated, requring both services to be deleted and reapplied. This is with `metallb.universe.tf/allow-shared-ip: shared` being set in the annotations.

**Comment by Slyke** [comment]
Solved.

After re-reading the docs carefully, I discovered that I also needed a `L2Advertisement` yaml.

```
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
    namespace: metallb-system
    name: my-lan
spec:
  addresses:
  - 10.1.1.10-10.1.2.254
  - 10.2.1.10-10.2.2.254
  - 10.3.1.10-10.3.2.254
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example
  namespace: metallb-system
spec:
  ipAddressPools:
  - main-lan
```
