### ISSUE TITLE
Random crash loops in reloader container

### ISSUE THREAD

**Issue by nanomad** [metallb/metallb#2029]
### MetalLB Version

0.13.10

### Deployment method

Charts

### Main CNI

flannel

### Kubernetes Version

1.27.4+k3s1

### Cluster Distribution

k3s

### Describe the bug

Sometimes relaoder gets stuck in crash loop backoff with the following stacktrace. This happens just on one node which coincidentally has multiple services with the same shared IP

```
Syntax error spotted: aborting.. 1 seconds
Caught SIGHUP and acquired lock! Reloading FRR..
Checking the configuration file syntax
2023-07-31 22:39:11,157  INFO: Called via "Namespace(input=None, reload=False, test=True, debug=False, log_level='info', stdout=True, pathspace=None, filename='/etc/frr_reloader/frr.conf', overwrite=False, bindir='/usr/bin', confdir='/etc/frr', rundir='/var/run/frr', vty_socket=None, daemon='', test_reset=False)"
2023-07-31 22:39:11,162  INFO: Loading Config object from file /etc/frr_reloader/frr.conf
2023-07-31 22:39:12,641  INFO: Loading Config object from vtysh show running
Traceback (most recent call last):
  File "/usr/lib/frr/frr-reload.py", line 1982, in <module>
    (lines_to_add, lines_to_del) = compare_context_objects(newconf, running)
  File "/usr/lib/frr/frr-reload.py", line 1762, in compare_context_objects
    (lines_to_add, lines_to_del) = ignore_delete_re_add_lines(
  File "/usr/lib/frr/frr-reload.py", line 1496, in ignore_delete_re_add_lines
    lines_to_add.remove((ctx_keys, line))
ValueError: list.remove(x): x not in list
Syntax error spotted: aborting.. 7 seconds
Caught SIGHUP and acquired lock! Reloading FRR..
```

Here's the full FRR config (when it is not crashing):

```
log file /etc/frr/frr.log informational
log timestamp precision 3
hostname pi01
ip nht resolve-via-default
ipv6 nht resolve-via-default
route-map 10.10.50.1-in deny 20


ip prefix-list 10.10.50.1-pl-ipv4 permit 10.10.60.4/32


ip prefix-list 10.10.50.1-pl-ipv4 permit 10.10.60.53/32


ip prefix-list 10.10.50.1-pl-ipv4 permit 10.10.60.3/32


ip prefix-list 10.10.50.1-pl-ipv4 permit 10.10.60.2/32


ip prefix-list 10.10.50.1-pl-ipv4 permit 10.10.60.53/32


ip prefix-list 10.10.50.1-pl-ipv4 permit 10.10.60.2/32


ip prefix-list 10.10.50.1-pl-ipv4 permit 10.10.60.1/32


ip prefix-list 10.10.50.1-pl-ipv4 permit 10.10.60.53/32

route-map 10.10.50.1-out permit 1
  match ip address prefix-list 10.10.50.1-pl-ipv4
route-map 10.10.50.1-out permit 2
  match ipv6 address prefix-list 10.10.50.1-pl-ipv4


ipv6 prefix-list 10.10.50.1-pl-ipv4 deny any

router bgp 65000
  no bgp ebgp-requires-policy
  no bgp network import-check
  no bgp default ipv4-unicast

  neighbor 10.10.50.1 remote-as 65000
  neighbor 10.10.50.1 port 179
  neighbor 10.10.50.1 timers 1 3


  neighbor 10.10.50.1 bfd profile bfd-profile-full

  address-family ipv4 unicast
    neighbor 10.10.50.1 activate
    neighbor 10.10.50.1 route-map 10.10.50.1-in in
    neighbor 10.10.50.1 route-map 10.10.50.1-out out
  exit-address-family
  address-family ipv6 unicast
    neighbor 10.10.50.1 activate
    neighbor 10.10.50.1 route-map 10.10.50.1-in in
    neighbor 10.10.50.1 route-map 10.10.50.1-out out
  exit-address-family
  address-family ipv4 unicast
    network 10.10.60.1/32
    network 10.10.60.2/32
    network 10.10.60.3/32
    network 10.10.60.4/32
    network 10.10.60.53/32
  exit-address-family


bfd
  profile bfd-profile-full
    receive-interval 300
    transmit-interval 300
    detect-multiplier 3
    minimum-ttl 254
```

### To Reproduce

Unknown

### Expected Behavior

reloader does not crash loop

### Additional Context

MetalLB reosurces are as follows:

```yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb-system
spec:
  addresses:
  - 10.10.60.1-10.10.60.253
---
apiVersion: metallb.io/v1beta1
kind: BFDProfile
metadata:
  name: bfd-profile-full
  namespace: metallb-system
spec:
  receiveInterval: 300
  transmitInterval: 300
  detectMultiplier: 3
  echoMode: false
  passiveMode: false
  minimumTtl: 254
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: rt-casa
  namespace: metallb-system
spec:
  myASN: 65000
  peerASN: 65000
  peerAddress: 10.10.50.1
  bfdProfile: bfd-profile-full
  holdTime: "3s"
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: default
  namespace: metallb-system
```

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [ ] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue
