### ISSUE TITLE
helmChart inflator friendly chart, including namespace

### ISSUE THREAD

**Issue by wibed** [metallb/metallb#2033]
### MetalLB Version

any

### Deployment method

Charts

### Main CNI

-

### Kubernetes Version

-

### Cluster Distribution

-

### Describe the bug

no possibilities to define the namespace from within the chart.
defies capabilities by tooling such as the chart inflator provided by kustomize.

https://github.com/kubernetes-sigs/kustomize/issues/3815

### To Reproduce

use this as a reference:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./addresspool.yaml
  - ./l2advertisement.yaml

helmGlobals:
  chartHome: ../../../base/metallb-system


helmCharts:
- name: metallb
  releaseName: cluster0
  namespace: metallb-system
  includeCRDs: true
  repo: https://metallb.github.io/metallb
``` 

### Expected Behavior

the chart to be usable with the helm chart inflator.

### Additional Context

none

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by fedepaol** [comment]
Need to understand better what the inflator does, but this is likely to be fixed by https://github.com/metallb/metallb/pull/1965

**Comment by fedepaol** [comment]
> ### Describe the bug
> no possibilities to define the namespace from within the chart. defies capabilities by tooling such as the chart inflator provided by kustomize.

@wibed since I see you already wrapped your head on this topic a lot, mind expanding on what's missing on the chart to make this inflator friendly?

**Comment by fedepaol** [comment]
ping @wibed :P

**Comment by fedepaol** [comment]
Closing this, feel free to reopen if you can provide the requested infos.

**Comment by wibed** [comment]
please kindly reopen.
i have specified the chart as follows:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../../../base/metallb-system

helmCharts:
- name: metallb
  Namespace: metallb-system
  releaseName: cluster0
  includeCRDs: true
  valuesInline:
  repo: https://metallb.github.io/metallb

patches:
  - path: values.yaml
    target:
      kind: HelmRelease
```

Couldnt make it happen, have downloaded the new charts including the related pr.
event though having `{ .Release.Namespace }` within the charts. was not able to deploy it.
there is no such field as `releaseNamespace` within the realms of the chartinflator
