### ISSUE TITLE
simple global load balancing

### ISSUE THREAD

**Issue by raffaelespazzoli** [metallb/metallb#2136]
### Is your feature request related to a problem?

Metalb is designed to be a create and manage local load balancer. But the BGP protocol can be used to create global load balancer using the concept of equal cost multi path.

It would be great if it was possible to use metallb to create global load balancers.

In fact it is simple to show that if two Loadbalancer Services in two different clusters are created with the same VIP and metallb is configured with BGP, the traffic will be load balanced across the two clusters.

The problem is that we cannot allow tenants to pick the VIPs for their LoadBalancer Services.

So some coordination is needed between the clusters across which one needs to establish global load balancing. And yet the metallb operator is cluster-bound and cannot "see" beyond the cluster it's running on.

### Describe the solution you'd like

I'd like to propose to use DNS as a means of coordination between the various metallb instances.
I'd like to be able to express the desire to have the VIP of a LoadBalancer service assigned by doing a dns lookup with a give FQDN.
For example if a LoadBalancer service is annotated with:
`metallb.io/assign-from-fqdn: myglobal.service.example.io`
The controller will try to resolve the name and proceed only when the name can be resolved to a VIP. At that point the controller will assign the VIP to the service (checking, obviously, that it belong to the authorized CIRDS and that it is available).
This simple change seems enough to implement rudimentary BGP-based global load balancers. In  the future perhaps it might be expanded with more load balancing strategies.

### Additional context

I am envisioning using this together with external-dns. So let's imaging two clusters. In cluster A we would ahve this LoadBalancer Service definition:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
  annotations:
    external-dns.alpha.kubernetes.io/hostname: myglobal.service.example.io
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
  type: LoadBalancer
```
notice the extenral dns annotation that will name the resulting VIP to `myglobal.service.example.io`
and in cluster B, we would have this service definition:
 ```yaml
 apiVersion: v1
kind: Service
metadata:
  name: my-service
  annotations:
    metallb.io/assign-from-fqdn: myglobal.service.example.io
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
  type: LoadBalancer
 ```
causing the VIP to be assigned from the resolved name (after external-dns has done it's job).

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.
