### ISSUE TITLE
Speaker pods is missing the Prometheus port in Annotations when using prometheus.scrapeAnnotations=true in Helm chart

### ISSUE THREAD

**Issue by JesperBerggren** [metallb/metallb#2181]
### MetalLB Version

0.13.12

### Deployment method

Charts

### Main CNI

Calico

### Kubernetes Version

1.27.7

### Cluster Distribution

Microk8s

### Describe the bug

The Speaker pods are missing the _prometheus.io/port: "7472"_ in Annotations when deploying via the Helm chart if setting prometheus.scrapeAnnotations=true.

It's because of a small bug in the speaker.yaml template.
Currently it says (on line 129-135):
```
      annotations:
        {{- if .Values.prometheus.scrapeAnnotations }}
        prometheus.io/scrape: "true"
        {{- if not .Values.speaker.frr.enabled }}
        prometheus.io/port: "{{ .Values.prometheus.metricsPort }}"
        {{- end }}
        {{- end }}
```
I think it should be something like:
```
      annotations:
        {{- if .Values.prometheus.scrapeAnnotations }}
        prometheus.io/scrape: "true"
        {{- if .Values.speaker.frr.enabled }}
        prometheus.io/port: "{{ .Values.speaker.frr.metricsPort }}"
        {{ else }}
        prometheus.io/port: "{{ .Values.prometheus.metricsPort }}"
        {{- end }}
        {{- end }}
```

### To Reproduce

Create a values.yaml file with something like:
```
prometheus:
  scrapeAnnotations: true
  rbacPrometheus: false
```
Install metallb via something like:
helm upgrade --install --namespace metallb-system --version 0.13.12 -f metallb-values.yaml metallb metallb/metallb

### Expected Behavior

I would expect the annotations to be:
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    prometheus.io/port: "7472"
    prometheus.io/scrape: "true"
    ...
```

### Additional Context

Seems like a simple fix :-)

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by oribon** [comment]
Hi, this is actually intentional because in frr mode we expose 2 ports for metrics, and I think you can't specify 2 ports on the annotation. Is there an issue you're facing regarding it?
iirc using "monitoring" as the port name when scrape=true tells prometheus to use it, perhaps that has changed (or I made it up :sweat_smile:)?

**Comment by JesperBerggren** [comment]
Hi again!
Well, the issue is that Prometheus can't scrape the metrics.
When go into Status --> Targets on Prometheus it says the following for speaker targes:
```
http://10.30.76.83:7946/metrics | DOWN
http://10.30.76.83/metrics | DOWN
```
Notice the ports. There's no metrics running on neither 7946 nor 80.
I can see that the metrics ports are named monitoring, but it appears Prometheus isn't scraping those ports. We're running with a standard Prometheus scrape config. I guess it could be tweaked to scrape ports with a specific name.

**Comment by fedepaol** [comment]
@JesperBerggren this is still an issue right? Or did you manage to get it work?

**Comment by JesperBerggren** [comment]
Yes, it's still an issue. I guess it might be possible to fix it via some reconfiguration of the Prometheus scraping configs but I've not yet fixed it.

**Comment by fedepaol** [comment]
Fair enough, we'll have another look then

**Comment by JesperBerggren** [comment]
Hi again,

Ok, it seems like it's not a problem with the speaker pods anyways.
It's my Prometheus scrape configs that are faulty.

I have this config:
```
    additionalScrapeConfigs:
    - job_name: 'kubernetes-pods'
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name
```
This gives me these targets for a single speaker pod:
- http://192.168.0.2/metrics
- http://192.168.0.2:7946/metrics
- http://192.168.0.2:7472/metrics
- http://192.168.0.2:7473/metrics

The last two are UP while the two first are DOWN (obviously). But I cannot grasp where the two first comes from. Port 80 isn't even defined in speaker pod, as far as I can tell.

I'm not an export in scrape configs. Can anybody see the problem from my config?

**Comment by oribon** [comment]
Hey, I didn't look closely on the config (because I'm not too familiar with it either 😅), what I want to ask is if you're using the prometheus operator (or can use it)? if so, a PodMonitor / ServiceMonitor for the controller/speakers should solve your problems.

**Comment by JesperBerggren** [comment]
Hi again,

A ServiceMonitor would partially solve my problems. It could probably get the metrics but we would still have two targets marked as down (under the list called "kubernetes-pods" as configured above).

Well, after many trials and errors I've solved it!

If anybody else should be in the same situation and looking for a solution I solved it via this configuration:
```
    additionalScrapeConfigs:
    - job_name: 'kubernetes-pods'
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        action: drop
        regex: ^metallb-system$
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name
    - job_name: 'kubernetes-pods-metallb'
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        action: keep
        regex: ^metallb-system$
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_container_port_name]
        action: keep
        regex: monitoring
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [ __address__, __meta_kubernetes_pod_container_port_number]
        action: replace
        regex: (.+):(?:\d+);(\d+)
        replacement: ${1}:${2}
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name
```
It creates a new list called kubernetes-pods-metallb where the relabelling is based on the fact that metrics ports are named "monitoring" and pods reside in the metallb-system namespace.
