### ISSUE TITLE
IP ranges no longer work

### ISSUE THREAD

**Issue by viceice** [metallb/metallb#2221]
### MetalLB Version

0.13.12

### Deployment method

Charts

### Main CNI

calico

### Kubernetes Version

1.27.8

### Cluster Distribution

k3s

### Describe the bug

IP ranges no longer work on IP pools

### To Reproduce

```yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: local
  namespace: metallb-system
spec:
  addresses:
  - 172.30.2.70-172.30.2.99
  autoAssign: false
```

Apply this pool an try to use `172.30.2.70` from that pool and get the not allowed error on the service.

### Expected Behavior

Ranges should work like they did some versions before.

### Additional Context

Workaround: use cidr ips
```yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: local
  namespace: metallb-system
spec:
  addresses:
  - 172.30.2.70/31
  - 172.30.2.72/29
  - 172.30.2.80/28
  autoAssign: false
```

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue
