### ISSUE TITLE
IPv6: Requests to LoadBalancer external-IP originating from cluster nodes result in "no route to host"

### ISSUE THREAD

**Issue by troodes** [metallb/metallb#2255]
### MetalLB Version

0.13.9

### Deployment method

Manifests

### Main CNI

calico

### Kubernetes Version

1.26.5

### Cluster Distribution

kubespray

### Describe the bug

IPv6 requests to the external-IP of the LoadBalancer service fail with "no route to host" if the request originates from a client running on any of the k8s cluster nodes that is not hosting a pod replica of the application.  This does not appear to hold true for the IPv4 external-IP, which works as expected.

The IPv6 failure manifests itself regardless of the LoadBalancer service being single-stack IPv6, or dual-stack.

Things that do work as expected on my dual-stacked setup:

- IPv6 requests originating from clients hosted on non-cluster nodes work as expected.
- IPv6 Requests originating from clients hosted on cluster nodes which also happen to be hosting a replica pod of the app work as expected.
- IPv4 requests work as expected, regardless of where the client resides.

### To Reproduce

1. Deploy app with LB service that is either IPv6, or dual-stacked.
2. Validate your app by testing IPv6 request to it from a client that is on a non-cluster host - should work and help validate the sanity of your app's deployment.
3. Test IPv6 request to the app from a client on a cluster node on which one of the app's replicas is deployed - should work.
4. Test IPv6 request to the app from a client on a cluster node on which there are **no** replicas of the app deployed - this fails.

### Expected Behavior

I'd expect IPv6 requests originating from any of the cluster nodes to route properly to the app, the same as IPv4 behavior.

### Additional Context

Local is being used for the externalTrafficPolicy on the service.

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.97.222,fded:fade:face:acea::ae
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: nginx-ingress
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: nginx-ingress
    app.kubernetes.io/name: ingress-nginx
  name: nginx-ingress-ingress-nginx-controller-med
  namespace: nsp-psa-restricted
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ipFamilyPolicy: PreferDualStack
  ipFamilies:  ["IPv4","IPv6"]
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
      appProtocol: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
      appProtocol: https

  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: nginx-ingress
    app.kubernetes.io/name: ingress-nginx
```

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue
