### ISSUE TITLE
Why can't ARP be sent for the LoadBalancer IP?

### ISSUE THREAD

**Issue by cfanbo** [metallb/metallb#2353]
### MetalLB Version

v0.14.4

### Deployment method

Manifests

### Main CNI

flannel

### Kubernetes Version

v1.28.8

### Cluster Distribution

kubeadm

### Describe the bug

OS: Ubuntu 22.04.1 LTS

I installed kubernetes on a Raspberry Pi 4B, and found that it could not send ARP broadcasts to the local network for the LoadBalancer IP. I have already referred to https://metallb.universe.tf/troubleshooting/ to enable promiscuous mode on the interface。

Working on a k8s host：
```
$ kubectl get svc -n ingress-nginx
NAME                                 TYPE           CLUSTER-IP       EXTERNAL-IP     PORT(S)                      AGE
ingress-nginx-controller             LoadBalancer   10.103.50.74     192.168.1.200   80:32628/TCP,443:31948/TCP   4h45m
ingress-nginx-controller-admission   ClusterIP      10.100.134.238   <none>          443/TCP                      4h45m

$ kubectl get ingress
NAME                 CLASS   HOSTS                ADDRESS         PORTS   AGE
ingress-myservicea   nginx   myservicea.foo.org   192.168.1.200   80      4h8m
ingress-myserviceb   nginx   myserviceb.foo.org   192.168.1.200   80      4h8m

$ curl -D- http://192.168.1.200 -H 'Host: myservicea.foo.org'
HTTP/1.1 200 OK
Date: Wed, 03 Apr 2024 07:38:33 GMT
Content-Type: text/html
Content-Length: 615
Connection: keep-alive
Last-Modified: Tue, 28 Mar 2023 17:09:24 GMT
ETag: "64231f44-267"
Accept-Ranges: bytes
...

```

Working on other host(MacPro)
```
$ curl -D- http://192.168.1.200 -H 'Host: myservicea.foo.org' -m 10

curl: (28) Connection timed out after 10001 milliseconds

$ ? (192.168.1.1) at 9c:7f:81:e:30:fc on en0 ifscope [ethernet]
? (192.168.1.2) at (incomplete) on en0 ifscope [ethernet]
? (192.168.1.33) at (incomplete) on en0 ifscope [ethernet]
? (192.168.1.100) at 5c:2:14:d5:ca:e2 on en0 ifscope [ethernet]
? (192.168.1.101) at e4:5f:1:56:9a:c9 on en0 ifscope [ethernet]
? (192.168.1.102) at 40:45:da:97:50:c2 on en0 ifscope [ethernet]
? (192.168.1.103) at cc:b5:d1:2a:bb:c3 on en0 ifscope [ethernet]
? (192.168.1.104) at 64:9e:31:8:dd:3e on en0 ifscope [ethernet]
? (192.168.1.105) at 5c:2:14:f8:4a:f2 on en0 ifscope [ethernet]
? (192.168.1.106) at 60:7e:a4:16:cf:75 on en0 ifscope [ethernet]
? (192.168.1.107) at aa:da:7d:32:c4:e on en0 ifscope [ethernet]
? (192.168.1.108) at a4:5e:60:bb:c:19 on en0 ifscope permanent [ethernet]
? (192.168.1.110) at 64:9e:31:2c:23:6b on en0 ifscope [ethernet]
? (192.168.1.111) at 12:6c:d4:93:27:7c on en0 ifscope [ethernet]
```
No ARP record found for 192.168.1.200

### To Reproduce

1. crate deployment
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.23-alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myservicea
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:alpine3.19
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myserviceb
spec:
  selector:
    app: apache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
```

2. ingress
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-myservicea
spec:
  rules:
  - host: myservicea.foo.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myservicea
            port:
              number: 80
  ingressClassName: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-myserviceb
spec:
  rules:
  - host: myserviceb.foo.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myserviceb
            port:
              number: 80
  ingressClassName: nginx
  ```
  3. on other host, send http request
  ```
$ curl -D- http://192.168.1.200 -H 'Host: myservicea.foo.org' -m 10

curl: (28) Connection timed out after 10001 milliseconds

```

### Expected Behavior

send ARP broadcast for LoadBalancer IP

### Additional Context

"How to observe the logs for ARP requests?"

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue
