### ISSUE TITLE
Obscure message with duplicate ipaddresspools in the pool selector

### ISSUE THREAD

**Issue by fedepaol** [metallb/metallb#2377]
### MetalLB Version

latest

### Deployment method

Not relevant

### Main CNI

not relevant

### Describe the bug

Create a bgp advertisement /l2 advertisemetn with the same name twice in the ipaddresspool selector and check the error:

{"caller":"config_controller.go:142","controller":"ConfigReconciler","error":"duplicate definition of ipAddressPools \"ingressgateway\"","level":"error","ts":"2024-04-17T14:42:54Z"}

### To Reproduce

See above

### Expected Behavior

A clear message that tells me to remove the duplicate entry from advertisement xy.

I suspect this also applies in other areas where we use the validate* functions.

### Additional Context

none

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by tozastation** [comment]
hi...!! Can i try to do this issue?

**Comment by fedepaol** [comment]
sure thing!

**Comment by tozastation** [comment]
[My Memo]

reproduce manifest

```yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: cheap
  namespace: metallb-system
spec:
  addresses:
  - 192.168.10.0/24
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example
  namespace: metallb-system
spec:
  ipAddressPools:
  - cheap
  ipAddressPoolSelectors:
    - matchLabels:
        name: default
    - matchLabels:
        name: default
```
