### ISSUE TITLE
L2 Advertisement Only Works Temporarily

### ISSUE THREAD

**Issue by edfincham** [metallb/metallb#2388]
### MetalLB Version

0.14.5

### Deployment method

Manifests

### Main CNI

flannel (k3s)

### Kubernetes Version

1.29.4

### Cluster Distribution

k3s

### Describe the bug

I have a 2 node raspberry-pi cluster running k3s which is connected to my router over wifi. The two nodes have static DHCP leases configed with the router and k3s is installed with the following flags `--disable servicelb --disable traefik --kube-proxy-arg=ipvs-strict-arp=true` 

The metallb installion all works fine and there are no issues creating an `IPAddressPool` (the IP range is not available to the rotuer) or an `L2Advertisement`.

When I create a LB service with an IP in the `IPAddressPool` range, it is assigned to the service, it is announced, and it is accessible from devices connected to my router.

However, this is only temporary. After a few minutes, the address becomes unreachable when I try to access from a browser (but remains assigned as the external IP for the service).

I've enabled debug logs and really don't see anything useful there myself, but I'm no expert in this.

I've also tried the troubleshooting steps and run the following on my machine:
```
sudo tcpdump -n -i wlan0 arp src host 192.168.0.242
```
As well as:
```
sudo arping -I wlan0 192.168.0.242
```

The tpcdump just contains `who-has` requests and replies which crop up when I make a change to the configuration (which causes it to work again, but temporarily). The arping just gets timeouts.

### To Reproduce

Install the manifest:
```shell
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.5/config/manifests/metallb-native.yaml
```

Create the metallb resources:
```yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: mainpool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.0.241-192.168.0.255
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - mainpool
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: rpi-1
```

Deploy Argocd:
```shell
helm repo add argo https://argoproj.github.io/argo-helm
helm repo update
helm install \
  argocd argo/argo-cd \
  --namespace argocd \
  --create-namespace \
  --version 5.52.0 \
  --values helm/argocd-values.yaml 
```

Where `argocd-values.yaml` contains just:
```yaml
configs:
  params:
    server.insecure: true

server:
  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.0.242
    externalTrafficPolicy: Local
```

### Expected Behavior

I expect the IP address for my service to be announced, and then to be accessible over my local network.

### Additional Context

Set `externalTrafficPolicy: Local` in the ArgoCD helm chart since there was some chatter in the issues about this solving what appears to be the same problem; no dice there.

Set `--kube-proxy-arg=ipvs-strict-arp=true` in the k3s install command due to [this discussion](https://github.com/k3s-io/k3s/discussions/7124) and some other chat in the issues about strictARP solving what also appears to be the same problem. Again, no dice.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by edfincham** [comment]
Had to zip since github won't let me upload a tarball
[metallb_report.zip](https://github.com/metallb/metallb/files/15167252/metallb_report.zip)

**Comment by mattmalec** [comment]
I am also experiencing this too. Happened out of no where - months and months of no downtime, and all of a sudden this exact thing started happening. Restarting the speaker daemonset is a temporary fix for us, but it's not ideal.

**Comment by edfincham** [comment]
Update: it does work consistently when I 
connect the L2 node via Ethernet. 

However, this is not an ideal configuration and doesn't explain why it only works temporarily via WiFi. I've also tried specifying the interface as wlan0 in the L2Advertisement spec but this didn't change anything 😕

**Comment by mattmalec** [comment]
Weird, we are using a wired connection and still experience this.

**Comment by fedepaol** [comment]
it can be two different issues. @mattmalec did it happen after upgrading metallb?

**Comment by fedepaol** [comment]
> Update: it does work consistently when I connect the L2 node via Ethernet.
> 
> However, this is not an ideal configuration and doesn't explain why it only works temporarily via WiFi. I've also tried specifying the interface as wlan0 in the L2Advertisement spec but this didn't change anything 😕

did you check https://metallb.org/troubleshooting/#using-wifi-and-can-t-reach-the-service ?

**Comment by edfincham** [comment]
> > Update: it does work consistently when I connect the L2 node via Ethernet.
> > However, this is not an ideal configuration and doesn't explain why it only works temporarily via WiFi. I've also tried specifying the interface as wlan0 in the L2Advertisement spec but this didn't change anything 😕
> 
> did you check https://metallb.org/troubleshooting/#using-wifi-and-can-t-reach-the-service ?

This works! Odd though as I saw this solution in the issues and was sure I had tested it previously... regardless, thanks for the help!

**Comment by mattmalec** [comment]
@fedepaol No we haven't updated in a while - I can give that a shot to see if it'll help. It's been running for a few months fine and then randomly started doing this without touching it.

**Comment by fedepaol** [comment]
> @fedepaol No we haven't updated in a while - I can give that a shot to see if it'll help. It's been running for a few months fine and then randomly started doing this without touching it.

@mattmalec please provide the logs / results of arping when it stops working. In general, try to follow the troubleshooting guide. Also also, when you have the details, please file a new issue.

**Comment by bashar-alasmar** [comment]
> @fedepaol No we haven't updated in a while - I can give that a shot to see if it'll help. It's been running for a few months fine and then randomly started doing this without touching it.

Hello mate, is it solved for you? i'm facing the same issue with metallb version 0.14.8

**Comment by krpusr** [comment]
I am still facing this issue, did anyone figured it out, it just works for 2 hours then throws 404 Not Found

I have to start metallb every two hours 
```
kubectl rollout restart daemonset/speaker -n metallb-system
```

This what I have
```
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.0.1.1-10.0.1.254
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-l2advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - default-pool
```
