### ISSUE TITLE
Enable MetalLB to run alongside KubeVIP

### ISSUE THREAD

**Issue by SlavikCA** [metallb/metallb#2396]
### Is your feature request related to a problem?

I have Harvester 1.3.0 Kubernetes cluster, which uses kubeVIP for cluster HA access.

I want to install HA Ingress (Traefik) for which I need VIP. 
It looks like it's hard to use kubeVIP, because it's managed by Harvester and my changes to it's configuration will be discarded.
So, I want MetalLB to manage ingress VIP.

Here is my config:
```
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: mapped-to-wan
  namespace: metallb-system
spec:
  addresses:
    - 10.0.4.251/32
---
# kubectl describe l2advertisement.metallb.io  -n metallb-system
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: wan
  namespace: metallb-system
spec:
  ipAddressPools:
    - mapped-to-wan
```

And it seemed to work:
> {"caller":"service.go:150","event":"ipAllocated","ip":["10.0.4.251"],"level":"info","msg":"IP address assigned by controller","ts":"2024-05-14T19:39:06Z"}

I have not yet created any LoadBalancer.

However, when looking at the MetalLB controller logs: it spits huge number of log lines, which appears like it's fighting with KubeVIP. This lines repeating over and over:
```
{"caller":"service_controller.go:64","controller":"ServiceReconciler","level":"info","start reconcile":"kube-system/ingress-expose","ts":"2024-05-14T19:39:06Z"}
{"caller":"service.go:108","error":"[\"10.0.4.247\"] is not allowed in config","event":"clearAssignment","level":"info","msg":"current IP not allowed by config, clearing","ts":"2024-05-14T19:39:06Z"}
{"caller":"service.go:150","event":"ipAllocated","ip":["10.0.4.251"],"level":"info","msg":"IP address assigned by controller","ts":"2024-05-14T19:39:06Z"}
{"caller":"main.go:116","event":"serviceUpdated","level":"info","msg":"updated service object","ts":"2024-05-14T19:39:06Z"}
{"caller":"service_controller.go:115","controller":"ServiceReconciler","end reconcile":"kube-system/ingress-expose","level":"info","ts":"2024-05-14T19:39:06Z"}
{"caller":"service_controller.go:64","controller":"ServiceReconciler","level":"info","start reconcile":"kube-system/ingress-expose","ts":"2024-05-14T19:39:06Z"}
{"caller":"service_controller.go:115","controller":"ServiceReconciler","end reconcile":"kube-system/ingress-expose","level":"info","ts":"2024-05-14T19:39:06Z"}
```
10.0.4.247 is my KubeVIP LoadBalancer

Here is how Harvester manages it's VIP:
```yaml
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: vip
    namespace: harvester-system
  data:
    enabled: "true"
    hwAddress: ""
    ip: 10.0.4.247
    loadBalancerIP: ""
    mode: static
    serviceType: LoadBalancer
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kube-vip.io/ignore-service-security: "true"
      kube-vip.io/loadbalancerIPs: 10.0.4.247
    name: ingress-expose
    namespace: kube-system
  spec:
    allocateLoadBalancerNodePorts: true
    ports:
    - name: https-internal
      nodePort: 31075
      port: 443
      protocol: TCP
      targetPort: 443
    - name: http
      nodePort: 31712
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app.kubernetes.io/name: rke2-ingress-nginx
    type: LoadBalancer
...
```

### Describe the solution you'd like

Is there any option to prevent MetalLB to conflict with kubeVIP entries?

Or am I missing something im my configuration?

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by SlavikCA** [comment]
I reinstalled Metallb with Helm.

And used following in my `values.yaml` to only take effect for this class:
```
loadBalancerClass: "metallb"
```

also I scoped `IPAddressPool` to only one namespace:

```
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: mapped-to-wan
  namespace: traefik
spec:
  addresses:
    - 10.0.4.248/32
  serviceAllocation:
    namespaces:
      - traefik
```

And everything worked, as expected.
