### ISSUE TITLE
Support Multiple IPs per Service from the Same Pool for Enhanced DNS-Level Redundancy

### ISSUE THREAD

**Issue by danielbjornadal** [metallb/metallb#2410]
### Is your feature request related to a problem?

Currently, MetalLB does not support assigning multiple IP addresses from the same pool to a single service. This limitation restricts the ability to create DNS entries with multiple IPs, which is crucial for achieving redundancy at the DNS level. Without this feature, if the node hosting the MetalLB IP fails, the service becomes unreachable for 5-10 seconds, causing traffic interruption.

### Describe the solution you'd like

I would like MetalLB to support assigning multiple IP addresses from the same IP pool to a single service. This enhancement will allow DNS entries to contain multiple IPs, providing redundancy and ensuring continuous traffic flow even if one node fails. Additionally, it would be beneficial to have a feature that enforces the distribution of these IPs across different nodes, rather than having all assigned IPs on a single node. This distribution will further enhance the reliability and availability of the service.

### Additional context

Implementing this feature will significantly improve the resilience of services managed by MetalLB in Kubernetes clusters. It ensures high availability by allowing DNS-based load balancing and failover, reducing the risk of service disruption due to node failures. This is especially important for critical applications where uptime is crucial.

Hypothetical configuration example:
```
apiVersion: v1
kind: Service
metadata:
  name: rke2-ingress-nginx-loadbalancer
  namespace: kube-system
    metallb.universe.tf/address-pool: pool-10-35-2-208-28
    metallb.universe.tf/loadBalancerIPs: "10.35.2.208, 10.35.2.209"
    metallb.universe.tf/forceOnDifferentNodes: "true"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: rke2-ingress-nginx
    app.kubernetes.io/name: rke2-ingress-nginx
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
```

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.
