### ISSUE TITLE
config metallb bgp ipv4 ippool with native mode failed

### ISSUE THREAD

**Issue by changluyi** [metallb/metallb#2431]
### MetalLB Version

0.14.5

### Deployment method

Operator

### Main CNI

kube-ovn

### Describe the bug

it is a dual cluster,  and I run metallb with native mode,  if you first create a dual ipaddressPool  A , and associate the ipaddressPool A to l2advertisement, and secondly create a ipv4 ipaddressPool B, and associate the ipaddressPool  to a bgpadvertisement, it will get a webhook error 

- ` pool "A" has ipv6 CIDR fd01::/120, native bgp mode does not support ipv6`

### To Reproduce

1. create ipaddressPool  A and l2advertisement with below:
```
kind: IPAddressPool
metadata:
  name: test
  namespace: metallb-system
spec:
  addresses:
  - 1.1.1.1/24
  - fd01::03/120
  autoAssign: true
  avoidBuggyIPs: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  generation: 1
  name: test
  namespace: metallb-system
spec:
  ipAddressPools:
  - test
```

2. create ipaddressspool test2
```
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: test2
  namespace: metallb-system
spec:
  addresses:
  - 4.4.4.4/24
  autoAssign: true
  avoidBuggyIPs: true
```

3. associate test2 to bgpadvertisement
```
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: test2
  namespace: metallb-system
spec:
  ipAddressPools:
  - test2
```

webhook will raise error:
```
Error from server (Forbidden): error when creating "bgpadv.yaml": admission webhook "bgpadvertisementvalidationwebhook.metallb.io" denied the request: pool "test" has ipv6 CIDR fd01::/120, native bgp mode does not support ipv6
```

### Expected Behavior

when test2 ippool associate with bgpadvertisement , should not check test1's ipv6 cidr.

### Additional Context

![image](https://github.com/metallb/metallb/assets/47097611/64b1a4b3-9352-4bce-9dbf-a3bb2a47e767)
the related code is above, 
I think the code inspection at this location needs to be more accurate

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by cyclinder** [comment]
Yes, we do not support IPv6 in native mode, but it is supported in frr bgp mode.

**Comment by changluyi** [comment]
my question is  metallb should not  check the ipaddressPool that is not associated with bgpadvertisement.

**Comment by fedepaol** [comment]
Is there a reason why you added a v6 pool if it can't be used?

**Comment by changluyi** [comment]
I add a dual ipaddressPool A associated with l2advertisment, (because I only use pool A do l2 arp or nd advertisement),  and then I create a ipv4 ipaddressPool B associated with bgpadvertisment,  

but when I create B's bgpadvertisment yaml , metallb strangely checks pool A with invalid v6 bgp cause，but actually A is only for l2 purposes

**Comment by fedepaol** [comment]
Ok, I get it, thanks!

**Comment by cyclinder** [comment]
I also get it, okay, let me check the code and try to fix it.

**Comment by fedepaol** [comment]
> I also get it, okay, let me check the code and try to fix it. @fedepaol If a BGP advertisement doesn't configure any pools, Which pool will it use? Metallb supports one pool that can be used by `L2Advertisement` and `BGPAdvertisement `simultaneously. so this is a reason why webhook rejected the request.

Right, with no pools it selects all of them, but in this case the BGPAdvertisement has a selector right?

```
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: test2
  namespace: metallb-system
spec:
  ipAddressPools:
  - test2
```
