### ISSUE TITLE
Node status becomes NotReady once I create service of type LoadBalancer

### ISSUE THREAD

**Issue by mareimorsy** [metallb/metallb#2455]
### MetalLB Version

v0.13.9

### Deployment method

Charts

### Main CNI

calico and cilium

### Kubernetes Version

v1.30.2

### Cluster Distribution

kubernetes [kubespray]

### Describe the bug

Node status becomes NotReady once I create service of type LoadBalancer

I have configured `IPAddressPool` and `L2Advertisement` as following:

```yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: main-pool
  namespace: metallb
spec:
  addresses:
  - <worker-node-4-public-ip>/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: pools-advertisement
  namespace: metallb
spec:
  ipAddressPools:
  - main-pool
```

When I test if the LB will be created properly like this, I get the proper IP and it works as expected
```bash
kubectl create deployment nginx --image nginx:alpine
kubectl expose deployment nginx --port 80 --type=LoadBalancer
kubectl get svc
# output
nginx        LoadBalancer   10.233.17.92    <worker-node-4-public-ip>      80:32666/TCP   21m
```
However the node becomes `NotReady` after 40s, and when I delete the service, it becomes Ready immediately.

### To Reproduce

Install new kubernetes cluster using kubespray with `calico` or `cilium` ... make sure to set `kube_proxy_strict_arp: true`
install metallb `v0.13.9` through kubespray or helmchart 
create service of type LoadBalancer ... and the node which has the same IP will become `NotReady`

### Expected Behavior

Node should be `Ready` and able to host different pods

### Additional Context

when trying to `nc -vz <master-node-public-ip> <kube-apiserver-ip>` from the `NotReady` node it is not able to connect, but once I delete the service, all other nodes are reachable.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue
