### ISSUE TITLE
Unable to create LoadBalancer with ExternalTrafficPolicy Local

### ISSUE THREAD

**Issue by jlaska** [metallb/metallb#2553]
### MetalLB Version

0.14.8

### Deployment method

Charts

### Main CNI

Flannel

### Kubernetes Version

v1.30.5+k3s1

### Cluster Distribution

k3s

### Describe the bug

I am attempting to run a local dns service while [preserving the client source IP](https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip).  Following the documentation, I'm setting `externalTrafficPolicy: Local` and `type: LoadBalancer`.  I'm also ensuring the following conditions:

* I'm using the same sharing key: `metallb.universe.tf/allow-shared-ip: "global"`
* I'm using ports that aren't already being used by another LoadBalancer service: `tcp/53, udp/53`

After creating the services, they remain in stuck in `<pending>` with the following event:

```
  Type     Reason            Age    From                Message
  ----     ------            ----   ----                -------
  Warning  AllocationFailed  4m21s  metallb-controller  Failed to allocate IP for "pihole/pihole-dns-udp": no available IPs
```

### To Reproduce

1. With the following `L2Advertisement`
```
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: metallb
spec:
  ipAddressPools:
  - default-pool
```
2. With the following `IPAddressPool`
```
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb
spec:
  addresses:
    - 10.0.1.10/32
```
3. With the following helm chart `values.yaml`
```
---
# Default values for metallb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
loadBalancerClass: ""

# To configure MetalLB, you must specify ONE of the following two
# options.

rbac:
  create: true

prometheus: # (redacted)
controller:
  enabled: true
  # -- Controller log level. Must be one of: `all`, `debug`, `info`, `warn`, `error` or `none`
  logLevel: debug
  # command: /controller
  # webhookMode: enabled
  image:
    repository: quay.io/metallb/controller
    tag:
    pullPolicy:
  strategy:
    type: RollingUpdate
  serviceAccount:
    create: true
    name: ""
    annotations: {}
  securityContext:
    runAsNonRoot: true
    # nobody
    runAsUser: 65534
    fsGroup: 65534
  resources: {}
  nodeSelector: {}
  tolerations: []
  priorityClassName: ""
  runtimeClassName: ""
  affinity: {}
  podAnnotations: {}
  labels: {}
  livenessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  readinessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  tlsMinVersion: "VersionTLS12"
  tlsCipherSuites: ""
  extraContainers: []

speaker:
  enabled: true
  logLevel: debug
  tolerateMaster: true
  memberlist:
    enabled: true
    mlBindPort: 7946
    mlBindAddrOverride: ""
    mlSecretKeyPath: "/etc/ml_secret_key"
  excludeInterfaces:
    enabled: true
  ignoreExcludeLB: false

  image:
    repository: quay.io/metallb/speaker
    tag:
    pullPolicy:
  updateStrategy:
    type: RollingUpdate
  serviceAccount:
    create: true
    name: ""
    annotations: {}
  securityContext: {}
  resources: {}
    # limits:
      # cpu: 100m
      # memory: 100Mi
  nodeSelector: {}
  tolerations: []
  priorityClassName: ""
  affinity: {}
  ## Selects which runtime class will be used by the pod.
  runtimeClassName: ""
  podAnnotations: {}
  labels: {}
  livenessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  readinessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  startupProbe:
    enabled: true
    failureThreshold: 30
    periodSeconds: 5
  frr:
    enabled: false
    image:
      repository: quay.io/frrouting/frr
      tag: 9.0.2
      pullPolicy:
    metricsPort: 7473
    resources: {}
  reloader:
    resources: {}
  frrMetrics:
    resources: {}
  extraContainers: []
crds:
  enabled: true
  validationFailurePolicy: Fail

frrk8s:
  enabled: false
```
5. Create the following services

```
---
apiVersion: v1
kind: Service
metadata:                                                                                                                                                             
  name: pihole-dns-udp
  labels:
    app: pihole
    app.kubernetes.io/name: pihole
  annotations:
    metallb.universe.tf/allow-shared-ip: "global"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: pihole
    app.kubernetes.io/name: pihole
  ports:
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53

---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns-tcp
  labels:
    app: pihole
    app.kubernetes.io/name: pihole
  annotations:
    metallb.universe.tf/allow-shared-ip: "global"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: pihole
    app.kubernetes.io/name: pihole
  ports:
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-web
  labels:
    app: pihole
    app.kubernetes.io/name: pihole
spec:
  type: ClusterIP
  selector:
    app: pihole
    app.kubernetes.io/name: pihole
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http                                                                                                                                                

```

### Expected Behavior

```
$ kubectl get svc -n pihole -o wide
NAME             TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE     SELECTOR
pihole-dns-tcp   LoadBalancer   10.43.91.167   10.0.1.10     53:31949/TCP   141m    app.kubernetes.io/name=pihole,app=pihole
pihole-dns-udp   LoadBalancer   10.43.80.157   10.0.1.10     53:31329/UDP   142m    app.kubernetes.io/name=pihole,app=pihole
```

### Additional Context

* The `Cluster` traffic policy allows the services to create.  However, that does not satisfy my client source IP goal.
* [Controller logs available](https://github.com/user-attachments/files/17195678/kube.txt) with `logLevel: debug`
  ```
  $ kubectl logs -n metallb metallb-controller-56b6cc96f8-xd455 --timestamps
  ```
* No other service is LoadBalancing port 53
  ```
  $ kubectl get svc -A -o wide | grep "LoadBalancer.*[^0-9]53:"
  pihole-dns-tcp   LoadBalancer   10.43.91.167   <pending>     53:31949/TCP   162m    app.kubernetes.io/name=pihole,app=pihole
  pihole-dns-udp   LoadBalancer   10.43.80.157   <pending>     53:31329/UDP   162m    app.kubernetes.io/name=pihole,app=pihole
  ```
* I can get externalTrafficPolicy `Cluster` to work, but not `Local` and I'm using the following selectors across the services and deployment: 
  ```
  $ kubectl get svc,pods -A --selector="app.kubernetes.io/name=pihole,app=pihole"
  NAMESPACE   NAME                     TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
  pihole      service/pihole-dns-tcp   LoadBalancer   10.43.91.167   <pending>     53:31949/TCP   164m
  pihole      service/pihole-dns-udp   LoadBalancer   10.43.80.157   <pending>     53:31329/UDP   164m
  pihole      service/pihole-web       ClusterIP      10.43.46.152   <none>        80/TCP         3h47m
  
  NAMESPACE   NAME                          READY   STATUS    RESTARTS   AGE
  pihole      pod/pihole-75b969786b-hq2kh   1/1     Running   0          169m
  ```

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue
