### ISSUE TITLE
High virtual memory usage when FRR is enabled 

### ISSUE THREAD

**Issue by mguggi** [metallb/metallb#2584]
### MetalLB Version

0.14.8

### Deployment method

Charts

### Main CNI

weave 

### Kubernetes Version

1.26.7

### Cluster Distribution

rancher

### Describe the bug

When we deploy `MetalLB` with `Helm`  and set the `frr.enabled` to `true` our monitoring system shows memory usage as critical. 

The `top` command in the `frr` container show the all `frr` processes uses very high virtual memory (`VSZ` column).

```
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
   33     0 root     S    1246m   1%  15   0% /speaker --port=7472 --log-level=info
  111    53 frr      S     256g 256%  12   0% /usr/lib/frr/zebra -d -F traditional -A 127.0.0.1 -s 90000000
  120    53 frr      S    96.0g  96%  11   0% /usr/lib/frr/bgpd -d -F traditional -A 127.0.0.1 -p 0
  116    53 frr      S    32.0g  32%   5   0% /usr/lib/frr/mgmtd -d -F traditional
  136    53 frr      S    32.0g  32%   4   0% /usr/lib/frr/bfdd -d -F traditional -A 127.0.0.1
  131    53 frr      S    32.0g  32%  13   0% /usr/lib/frr/staticd -d -F traditional -A 127.0.0.1
   59    55 root     S    32.0g  32%   4   0% /usr/lib/frr/watchfrr zebra mgmtd bgpd staticd bfdd
``` 

We have also tried to set the `resource` for the  `frr` container. 

```  
resources:
    requests: 
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 200Mi
```

### To Reproduce

1. Deploy the version 0.14.8 with `Helm`

### Expected Behavior

No high virtual memory usage.

### Additional Context

I don't understand why this is so.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by fedepaol** [comment]
Can you share also your configuration?

**Comment by mguggi** [comment]
This is currently our whole configuration. 

```
# This was autogenerated by MetalLB's custom resource generator.
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  creationTimestamp: null
  name: mgmt
  namespace: metallb-system
spec:
  addresses:
  - 10.232.11.47/32
status: {}
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  creationTimestamp: null
  name: backend
  namespace: metallb-system
spec:
  addresses:
  - 172.18.20.220/32
  - 172.18.20.221/32
  - 172.18.20.222/32
  - 172.18.20.223/32
  - 172.18.20.225/32
  - 172.18.20.230/32
  - 172.18.20.231/32
  - 172.18.20.232/32
  - 172.18.20.233/32
  - 172.18.20.234/32
  - 172.18.20.235/32
  - 172.18.20.242/32
  - 172.18.20.243/32
  - 172.18.20.245/32
status: {}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  creationTimestamp: null
  name: l2advertisement1
  namespace: metallb-system
spec:
  ipAddressPools:
  - mgmt
status: {}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  creationTimestamp: null
  name: l2advertisement2
  namespace: metallb-system
spec:
  ipAddressPools:
  - backend
status: {}
---

```
