### ISSUE TITLE
A question related to declaring VIPs from the external address pool in MetalLB.

### ISSUE THREAD

**Issue by changluyi** [metallb/metallb#2586]
### Is your feature request related to a problem?

no

### Describe the solution you'd like

Currently, if a VIP from the external address pool needs to be advertised from a certain node, it is necessary to establish a BGP peering relationship with the user's BGP router on that node. Is there any improvement method in the community so that the selected node from the external address pool does not necessarily have to establish a BGP peering relationship with the user's BGP router?

What I mean is that it is possible that the node selected by metallb's external address pool is not among the nodes selected by BGPeer?

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by fedepaol** [comment]
Please check the docs. We have node selectors for the bgppeer (to choose what nodes to establish with) and for the bgpadvertisement (to choose which node advertise a given pool from).

**Comment by changluyi** [comment]
For example：
```
--- 
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: test
  namespace: metallb-system
spec:
  myASN: 64512
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: 192.168.136.228
  peerASN: 64512
  peerAddress: 192.168.254.242
  peerPort: 179
  routerID: 192.168.254.253
  
  ---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: test
  namespace: metallb-system
spec:
  aggregationLength: 32
  aggregationLengthV6: 128
  ipAddressPools:
  - test
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: 192.168.136.227
  peers:
  - test
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: test
  namespace: metallb-system
spec:
  addresses:
  - 8.8.8.8/24
  autoAssign: true
  avoidBuggyIPs: true
```

the IPs in addressPool `test`  will never be announced. because nodeSelectors in BGPAdvertisement and nodeSelectors in BGPPeer have no intersection
