### ISSUE TITLE
Community validation webhook denies all updates

### ISSUE THREAD

**Issue by Jeroen0494** [metallb/metallb#2597]
### MetalLB Version

1.14.8

### Deployment method

Manifests

### Main CNI

Calico

### Kubernetes Version

1.29.7

### Cluster Distribution

kubespray

### Describe the bug

For some reason the community can only be created once, all patches to the resource are denied.

The resource:
```
---
apiVersion: metallb.io/v1beta1
kind: Community
metadata:
  name: well-known
  namespace: "metallb-system"
spec:
  communities:
  - name: no-export
    value: 65535:65281
  - name: no-advertise
    value: 65535:65282
  - name: local-as
    value: 65535:65283
  - name: nopeer
    value: 65535:65284
```

Output:
```
Error from server: error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"metallb.io/v1beta1\",\"kind\":\"Community\",\"metadata\":{\"annotations\":{},\"name\":\"well-known\",\"namespace\":\"metallb-system\"},\"spec\":{\"communities\":[{\"name\":\"no-export\",\"value\":\"65535:65281\"},{\"name\":\"no-advertise\",\"value\":\"65535:65282\"},{\"name\":\"local-as\",\"value\":\"65535:65283\"},{\"name\":\"nopeer\",\"value\":\"65535:65284\"}]}}\n"}}}
to:
Resource: "metallb.io/v1beta1, Resource=communities", GroupVersionKind: "metallb.io/v1beta1, Kind=Community"
Name: "well-known", Namespace: "metallb-system"
for: "templates/layer3.yaml": error when patching "templates/layer3.yaml": admission webhook "communityvalidationwebhook.metallb.io" denied the request without explanation
```
[metallb_report.zip](https://github.com/user-attachments/files/17815942/metallb_report.zip)

The "without explanation" makes it so I have no idea why my resource is being denied.

### To Reproduce

Apply the community resource twice. The first one will succeed, the second one will fail.

### Expected Behavior

Apply the community resource twice. Both will succeed, and the second one will report the resource was unchanged.

### Additional Context

No

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue
