### ISSUE TITLE
LoadBalancer Service binds VIP to control plane node excluded from nodeSelector

### ISSUE THREAD

**Issue by antoniogrv** [metallb/metallb#2641]
### MetalLB Version

0.14.2

### Deployment method

Raw YAML manifests (both for Operator, and non-Operator deployments)

### Main CNI

Calico (via Tigera)

### Kubernetes Version

1.29.9

### Cluster Distribution

Vanilla Kubernetes (kubeadm)

### Describe the bug

In short, IPs allocated for `LoadBalancer` Services by MetalLB get assigned on a network interface on the Kubernetes control plane. I've verified this behaviour on a 5-node cluster (1 control planes, 4 workers).

- My `IPAddressPool` contains the following range: `["10.129.82.76-10.129.82.77"]`. I have a corresponding L2Advertismeent object referencing such pool.
- When creating a `LoadBalancer` Service (with the `autoAssign: true` configuration enabled), the External IP field of the Service is correctly populated with `10.129.82.76` (assuming no other `LoadBalancer` Service is currently pending and requiring an IP).
- Now, accessing the control plane of the Kubernetes cluster and executing `ip a` shows that `10.129.82.76` is indeed binded on the main network interface (`inet 10.129.82.76/32 scope global <nic-name>`).
- Deleting the Service removes the corresponding virtual IP from the NIC on the control plane.

This happens **only on the control plane, and not on any of the other 4 nodes of this 5-nodes Kubernetes cluster**.

I'm actually able to ping and SSH into `10.129.82.76`, even though I possibly should not be able to do that. What's going on here?

**Important.** MetalLB `speakers` pod spawn on the correct nodes. I actually have a `nodeSelector` for both speakers and controllers that exclude the control planes. From events and log, I can see that addresses are correctly announced from non-control plane nodes. Still, the control plane gets the VIP on its NIC.

For some reason, *sometimes* -- as in, *after some time*, `LoadBalancer` VIPs are not reachable anymore. In this case, restarting the control plane (which hosts the VIP on its NIC) or deleting the Service (which removes the VIP on the control plane NIC) and recreating the Service (again, this binds the VIP to the control plane NIC) temporarily fixes the problem.

### To Reproduce

See above.

### Expected Behavior

To my understanding, I should not be able to ping or SSH into the VIPs allocated for the `LoadBalancer` Services. Also, the VIP is allocated on Kubernetes cluster nodes that do not host any speaker pods.
On a different note, if that is the expected behaviour, then I'd assume that the VIP would be allocated on nodes that actually have the `speaker` pods running. This is not the case: the VIP is allocated on a node that does not have the `speaker` pod.

Please note that this may just be a misunderstanding on my side on how such VIPs are allocated on nodes. This is possibly more on the `kube-proxy` side of things rather than MetalLB.

### Additional Context

`kube-proxy` pods are correctly running on every node, with the default `""` mode, which should be `iptables`. 

Tested on both 0.14.2 (Operator YAML manifests) and 0.14.9 (non-Operator YAML manifests).

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by fedepaol** [comment]
> Now, accessing the control plane of the Kubernetes cluster and executing `ip a` shows that `10.129.82.76` is indeed binded on the main network interface (`inet 10.129.82.76/32 scope global <nic-name>`).

This is not metallb. MetalLB works by replying to arp requests _as if_ the interfaces were holding the ip, but it never assigned the ip itself. I'd suggest picking another range.

**Comment by antoniogrv** [comment]
> > Now, accessing the control plane of the Kubernetes cluster and executing `ip a` shows that `10.129.82.76` is indeed binded on the main network interface (`inet 10.129.82.76/32 scope global <nic-name>`).
> 
> This is not metallb. MetalLB works by replying to arp requests _as if_ the interfaces were holding the ip, but it never assigned the ip itself. I'd suggest picking another range.

Thank you for the swift reply, @fedepaol.

I understand that this is not MetalLB's doing. I'd like to understand what's going on under the hood. Which Kubernetes component could be assigning the IP to the master control plane's NIC? I'm guessing it may have something to do either with the Calico CNI, or perhaps `kube-proxy`.

As per your suggestion, I've tried using a completely different IP range (`192.168.100.0/24`), but the issue persists in the same fashion as described previsouly.

**Comment by fedepaol** [comment]
> > > Now, accessing the control plane of the Kubernetes cluster and executing `ip a` shows that `10.129.82.76` is indeed binded on the main network interface (`inet 10.129.82.76/32 scope global <nic-name>`).
> > 
> > 
> > This is not metallb. MetalLB works by replying to arp requests _as if_ the interfaces were holding the ip, but it never assigned the ip itself. I'd suggest picking another range.
> 
> Thank you for the swift reply, @fedepaol.
> 
> I understand that this is not MetalLB's doing. I'd like to understand what's going on under the hood. Which Kubernetes component could be assigning the IP to the master control plane's NIC? I'm guessing it may have something to do either with the Calico CNI, or perhaps `kube-proxy`.
> 
> As per your suggestion, I've tried using a completely different IP range (`192.168.100.0/24`), but the issue persists in the same fashion as described previsouly.

Oh, this is weird. I thought you just matched an assigned ip by mistake. So you are saying that if you change the lb ip, the ip assigned to the nic changes too (by  running ip a on the host)?

**Comment by antoniogrv** [comment]
> Oh, this is weird. I thought you just matched an assigned ip by mistake. So you are saying that if you change the lb ip, the ip assigned to the nic changes too (by running ip a on the host)?

This is correct.

Please have a look the following configuration.

*Note*. I've deleted some system annotations (e.g `uuid(s)`) for sake of clarity.

- `IPAddressPool`:

```yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: l2-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.100.0/24
  autoAssign: true
  avoidBuggyIPs: false
```

- `L2Advertisement`:

```yaml
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: config
  namespace: metallb-system
spec:
  interfaces:
  - enp19s0
  ipAddressPools:
  - l2-pool
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: mynode02
      role: storage-node
```

- `MetalLB`:

```yaml
apiVersion: metallb.io/v1beta1
kind: MetalLB
metadata:
  name: metallb
  namespace: metallb-system
spec:
  controllerNodeSelector:
    role: storage-node
  controllerTolerations:
  - effect: NoSchedule
    key: role
    operator: Equal
    value: storage-node
  nodeSelector:
    role: storage-node
  speakerTolerations:
  - effect: NoSchedule
    key: role
    operator: Equal
    value: storage-node
status:
  conditions:
  - lastTransitionTime: "2024-12-19T13:27:59Z"
    message: ""
    reason: Available
    status: "True"
    type: Available
  - lastTransitionTime: "2024-12-19T13:27:59Z"
    message: ""
    reason: Upgradeable
    status: "True"
    type: Upgradeable
  - lastTransitionTime: "2024-12-19T13:27:59Z"
    message: ""
    reason: Progressing
    status: "False"
    type: Progressing
  - lastTransitionTime: "2024-12-19T13:27:59Z"
    message: ""
    reason: Degraded
    status: "False"
    type: Degraded
```

My Kuberentes cluster nodes are the following:

```
- mynode1 <-- Control Plane
- mynode2 <-- Worker / Storage
- mynode3 <-- Worker / Storage
- mynode4 <-- Worker / Storage
- mynode5 <-- Worker
```

`mynode2`, `mynode3` and `mynode4` have the following taints and labels:

```yaml
# [...]
metadata:
  labels:
    role: storage-node
# [...]
spec:
  taints:
  - effect: NoSchedule
     key: role
     value: storage-node
```

Please note that:

- All nodes have the `enp11s0` NIC, mappend on the `10.129.82.0/25` subnet.
- `mynode2` has an extra NIC: `enp19s0`, mapped on the `192.168.100.0/24` subnet.

Operator-wise, `speaker`, 'controller' and `webhook` pods do spawn on the correct nodes. That is, nodes that have the `storage-node` label.

```bash
kubectl get pods -n metallb-system -o wide | grep infra

controller-5f6c8645f8-zlcsd                            1/1     Running   0               8m42s   192.168.212.199   mynode03   <none>           <none>
metallb-operator-controller-manager-66f4df5756-msv6c   1/1     Running   0               8m47s   192.168.212.204   mynode03   <none>           <none>
metallb-operator-webhook-server-7f54d577d4-t67nq       1/1     Running   1 (8m17s ago)   8m47s   192.168.212.194   mynode03   <none>           <none>
speaker-2knx5                                          4/4     Running   0               8m42s   10.129.82.57      mynode02   <none>           <none>
speaker-59s66                                          4/4     Running   0               8m42s   10.129.82.56      mynode01   <none>           <none>
speaker-mmbn2                                          4/4     Running   0               8m42s   10.129.82.55      mynode04   <none>           <none>
```

Now, when checking Services, a correct IP is thrown to the following NGINX Ingress Controller `LoadBalancer` Service:

```bash
kubectl get svc -A | grep LoadBalancer

ingress-nginx   ingress-nginx-controller   LoadBalancer   10.109.215.166   192.168.100.1   80:32428/TCP,443:31598/TCP
```

Finally, running `ip a` on `mynode01`, which is the control plane, shows the following:

```
...
2: enp11s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:83:d6:1f brd ff:ff:ff:ff:ff:ff
    inet 10.129.82.54/25 brd 10.129.82.127 scope global enp11s0 # Node IP, ignore
...
    inet 192.168.100.1/32 scope global enp11s0 # <---- This is the problem
       valid_lft forever preferred_lft forever
...

While running `ip a` on `mynode02` shows the following:

```
...
2: enp11s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:83:29:12 brd ff:ff:ff:ff:ff:ff
    inet 10.129.82.57/25 brd 10.129.82.127 scope global enp11s0 # Node IP, ignore
       valid_lft forever preferred_lft forever
...
3: enp19s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:83:3c:9c brd ff:ff:ff:ff:ff:ff
    inet 192.168.100.10/24 brd 192.168.100.255 scope global enp19s0 # Node IP, ignore
       valid_lft forever preferred_lft forever
...
