### ISSUE TITLE
IP allocation failed if pool priority is configured

### ISSUE THREAD

**Issue by xhejtman** [metallb/metallb#2656]
### MetalLB Version

0.14.9

### Deployment method

Charts

### Main CNI

calico

### Kubernetes Version

1.31.4

### Cluster Distribution

rke2 (rancher).

### Describe the bug

If pools are configured with priorities:
```
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
spec:
  addresses:
  - x.y.z.193-x.y.z.254
  - x.y.a.10-x.y.a.127
  serviceAllocation:
    priority: 1
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-v6
spec:
  addresses:
  - aaaa:bbbb:cccc:dddd:8:4::/96
  serviceAllocation:
    priority: 1
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: privmuni
spec:
  addresses:
  - 10.16.63.129-10.16.63.254
  serviceAllocation:
    priority: 2
```

I am getting the following error:
```
{"caller":"service_controller.go:64","controller":"ServiceReconciler","level":"info","start reconcile":"test-ns/test3d-ssl","ts":"2025-01-16T22:05:31Z"}
{"caller":"service_controller.go:95","controller":"ServiceReconciler","level":"debug","processing service":"{\"kind\":\"Service\",\"apiVersion\":\"v1\",\"metadata\":{\"name\":\"test3d-ssl\",\"namespace\":\"test-ns\",\"uid\":\"3db0b400-d118-4357-ae95-098b86ff08da\",\"resourceVersion\":\"2600679039\",\"creationTimestamp\":\"2025-01-16T22:05:31Z\",\"labels\":{\"app.kubernetes.io/managed-by\":\"Helm\"},\"annotations\":{\"external-dns.alpha.kubernetes.io/hostname\":\"test-ns-test3d-ssl.dyn.cloud.e-infra.cz\",\"meta.helm.sh/release-name\":\"test3d-ssl\",\"meta.helm.sh/release-namespace\":\"test-ns\"},\"managedFields\":[{\"manager\":\"helm\",\"operation\":\"Update\",\"apiVersion\":\"v1\",\"time\":\"2025-01-16T22:05:31Z\",\"fieldsType\":\"FieldsV1\",\"fieldsV1\":{\"f:metadata\":{\"f:annotations\":{\".\":{},\"f:external-dns.alpha.kubernetes.io/hostname\":{},\"f:meta.helm.sh/release-name\":{},\"f:meta.helm.sh/release-namespace\":{}},\"f:labels\":{\".\":{},\"f:app.kubernetes.io/managed-by\":{}}},\"f:spec\":{\"f:allocateLoadBalancerNodePorts\":{},\"f:externalTrafficPolicy\":{},\"f:internalTrafficPolicy\":{},\"f:ports\":{\".\":{},\"k:{\\\"port\\\":5900,\\\"protocol\\\":\\\"TCP\\\"}\":{\".\":{},\"f:name\":{},\"f:port\":{},\"f:protocol\":{},\"f:targetPort\":{}}},\"f:selector\":{},\"f:sessionAffinity\":{},\"f:type\":{}}}}]},\"spec\":{\"ports\":[{\"name\":\"vnc\",\"protocol\":\"TCP\",\"port\":5900,\"targetPort\":5900}],\"selector\":{\"app\":\"test3d-ssl\"},\"clusterIP\":\"10.43.178.93\",\"clusterIPs\":[\"10.43.178.93\"],\"type\":\"LoadBalancer\",\"sessionAffinity\":\"None\",\"externalTrafficPolicy\":\"Local\",\"healthCheckNodePort\":31919,\"ipFamilies\":[\"IPv4\"],\"ipFamilyPolicy\":\"SingleStack\",\"allocateLoadBalancerNodePorts\":false,\"internalTrafficPolicy\":\"Cluster\"},\"status\":{\"loadBalancer\":{}}}","ts":"2025-01-16T22:05:31Z"}
{"caller":"main.go:52","event":"startUpdate","level":"debug","msg":"start of service update","ts":"2025-01-16T22:05:31Z"}
{"caller":"service.go:173","error":"no available IPs","level":"error","msg":"IP allocation failed","op":"allocateIPs","ts":"2025-01-16T22:05:31Z"}
{"caller":"main.go:87","event":"noChange","level":"debug","msg":"service converged, no change","ts":"2025-01-16T22:05:31Z"}
{"caller":"main.go:88","event":"endUpdate","level":"debug","msg":"end of service update","ts":"2025-01-16T22:05:31Z"}
{"caller":"service_controller.go:112","controller":"ServiceReconciler","endpoints":"[]","event":"failed to handle service","level":"error","name":"test-ns/test3d-ssl","service":"{\"kind\":\"Service\",\"apiVersion\":\"v1\",\"metadata\":{\"name\":\"test3d-ssl\",\"namespace\":\"test-ns\",\"uid\":\"3db0b400-d118-4357-ae95-098b86ff08da\",\"resourceVersion\":\"2600679039\",\"creationTimestamp\":\"2025-01-16T22:05:31Z\",\"labels\":{\"app.kubernetes.io/managed-by\":\"Helm\"},\"annotations\":{\"external-dns.alpha.kubernetes.io/hostname\":\"test-ns-test3d-ssl.dyn.cloud.e-infra.cz\",\"meta.helm.sh/release-name\":\"test3d-ssl\",\"meta.helm.sh/release-namespace\":\"test-ns\"},\"managedFields\":[{\"manager\":\"helm\",\"operation\":\"Update\",\"apiVersion\":\"v1\",\"time\":\"2025-01-16T22:05:31Z\",\"fieldsType\":\"FieldsV1\",\"fieldsV1\":{\"f:metadata\":{\"f:annotations\":{\".\":{},\"f:external-dns.alpha.kubernetes.io/hostname\":{},\"f:meta.helm.sh/release-name\":{},\"f:meta.helm.sh/release-namespace\":{}},\"f:labels\":{\".\":{},\"f:app.kubernetes.io/managed-by\":{}}},\"f:spec\":{\"f:allocateLoadBalancerNodePorts\":{},\"f:externalTrafficPolicy\":{},\"f:internalTrafficPolicy\":{},\"f:ports\":{\".\":{},\"k:{\\\"port\\\":5900,\\\"protocol\\\":\\\"TCP\\\"}\":{\".\":{},\"f:name\":{},\"f:port\":{},\"f:protocol\":{},\"f:targetPort\":{}}},\"f:selector\":{},\"f:sessionAffinity\":{},\"f:type\":{}}}}]},\"spec\":{\"ports\":[{\"name\":\"vnc\",\"protocol\":\"TCP\",\"port\":5900,\"targetPort\":5900}],\"selector\":{\"app\":\"test3d-ssl\"},\"clusterIP\":\"10.43.178.93\",\"clusterIPs\":[\"10.43.178.93\"],\"type\":\"LoadBalancer\",\"sessionAffinity\":\"None\",\"externalTrafficPolicy\":\"Local\",\"healthCheckNodePort\":31919,\"ipFamilies\":[\"IPv4\"],\"ipFamilyPolicy\":\"SingleStack\",\"allocateLoadBalancerNodePorts\":false,\"internalTrafficPolicy\":\"Cluster\"},\"status\":{\"loadBalancer\":{}}}","ts":"2025-01-16T22:05:31Z"}
{"caller":"service_controller.go:113","controller":"ServiceReconciler","end reconcile":"test-ns/test3d-ssl","level":"info","ts":"2025-01-16T22:05:31Z"}
{"level":"debug","ts":"2025-01-16T22:05:31Z","logger":"events","msg":"Failed to allocate IP for \"test-ns/test3d-ssl\": no available IPs","type":"Warning","object":{"kind":"Service","namespace":"test-ns","name":"test3d-ssl","uid":"3db0b400-d118-4357-ae95-098b86ff08da","apiVersion":"v1","resourceVersion":"2600679039"},"reason":"AllocationFailed","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/recorder.(*Provider).getBroadcaster.func1.1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/recorder/recorder.go:104\nk8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher.func1\n\t/go/pkg/mod/k8s.io/client-go@v0.31.4/tools/record/event.go:418"}
```

and service is in Pending state.

If I select pool explicitly via `metallb.universe.tf/address-pool: default` annotation, IP is assigned. Similarly, IP is assigned, if I remove priority settings from the pools.

### To Reproduce

1. deploy metallb with values:
```
controller:
  logLevel: debug
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    fsGroup: 65534
    seccompProfile:
      type: RuntimeDefault
speaker:
  enabled: false
```

2. define pools with priorities as above.
3. create service:
```
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Release.Namespace }}-{{ .Release.Name }}.dyn.cloud
spec:
  selector:
    app: {{ .Release.Name }}
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  externalTrafficPolicy: Local
  ports:
    - port: 5900
      name: vnc
      targetPort: 5900
```

4. service is pending. 

### Expected Behavior

Allocate IP in the highest priority pool.

### Additional Context

n/a

### I've read and agree with the following

- [x] I've checked all open and closed issues and my request is not there.
- [x] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [x] I've checked all open and closed issues and my issue is not there.
- [x] This bug is reproducible when deploying MetalLB from the main branch
- [x] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [x] I checked the logs and MetalLB is not discarding the configuration as not valid
- [x] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [x] I will provide the definition of my service and the related endpoint slices and attach them to this issue
