### ISSUE TITLE
MetalLBAddressPoolExhausted/MetalLBAddressPoolUsage alerts: add opt-out for specific pools

### ISSUE THREAD

**Issue by gberche-orange** [metallb/metallb#2665]
### Is your feature request related to a problem?

Some `IPAddressPool` are not designed to have spare capacity and should not trigger an alert. For instance, [statically assigned IP addresses](https://metallb.io/usage/#requesting-specific-ips), where the `IPAddressPool` only contains the static IP addresses manually assigned.

Currently, the `MetalLBAddressPoolExhausted` alert triggers when all ip addresses have been allocated in a pool. It is not yet possible to exclude a given pool from the alert.

https://github.com/metallb/metallb/blob/569a38ed0d8f7bc9eefa8c45df8450d62ad98238/charts/metallb/templates/prometheusrules.yaml#L44-L54

### Describe the solution you'd like

Provide a way to exclude some pools from the `MetalLBAddressPoolExhausted` alert
* A list of pool names to exclude in the helm chart value, 

Currently:
https://github.com/metallb/metallb/blob/569a38ed0d8f7bc9eefa8c45df8450d62ad98238/charts/metallb/values.yaml#L164-L168

```yaml
    # MetalLBAddressPoolExhausted
    addressPoolExhausted:
      enabled: true
      labels:
        severity: critical
      # Optionally exclude some pools by name if they match the specified regular expression. Default to null
      # Example "static-pool1|static-pool2"
      ignorePoolsRegexp: null 
```

Alert expr would then become something like

`expr: metallb_allocator_addresses_in_use_total{pool!~"${ignorePoolsRegexp}"} >= on(pool) metallb_allocator_addresses_total{pool!~"${ignorePoolsRegexp}"}`

### I've read and agree with the following

- [x] I've checked all open and closed issues and my request is not there.
- [x] I've checked all open and closed pull requests and my request is not there.
