### ISSUE TITLE
Documenting the IP range change workflow

### ISSUE THREAD

**Issue by weisjohn** [metallb/metallb#308]
**Is this a bug report or a feature request?**:

feature request

**What happened**:

@danderson very quickly and awesomely helped me understand how to migrate my metallb-managed services from one block of IPs to another.

**What you expected to happen**:

To spend hours rebuilding my cluster by hand after re-`kubeadm init`-ing and installing metallb.

**How to reproduce it (as minimally and precisely as possible)**:

Here's my first stab at documenting:

<hr />

## IP Address Migration

To migrate an IP address range for a set of services, you must remove the old ConfigMap, and replace it with a new one, then delete the Pods within the `metallb-system` namespace.

For example, using a Layer2 IP address range, beginning with the following ConfigMap:

```yml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.0.0.10-10.0.0.19
```

And assuming a `new.yml` config file, with a new IP address range of `10.0.0.20-10.0.0.29`, to migrate your services to a new IP range, you should:

```bash
# note the old IPs allocated to the services
kubectl get svc

# delete the old configmap
kubectl -n metallb-system delete cm config

# apply the new configmap
kubectl apply -f new.yml

# delete the metallb pods
kubectl -n metallb-system delete pod --all

# watch the pods come back up
kubectl -n metallb-system get pods -w

# inspect new IPs of services
kubectl get svc
```

<hr />

**Anything else we need to know?**:

I need to know where to put the documentation.  Should it be in a page under usage https://metallb.universe.tf/usage/ ?  Should it be under configuration https://metallb.universe.tf/configuration/ ?

**Environment**:
- MetalLB version: v0.7.3
- Kubernetes version: v1.11.2
- BGP router type/version: Layer2
- OS (e.g. from /etc/os-release): n/a
- Kernel (e.g. `uname -a`): n/a
