### ISSUE TITLE
Suggestion: Populate external IP with public one when using layer2 mode

### ISSUE THREAD

**Issue by rbq** [metallb/metallb#437]
I set up MetalLB in layer2 mode, it hands out local IPs from a /29 range and my firewall routes a public /29 subnet there. All this works extremely well, except for the fact that there seems to be no way to populate the provisioned LoadBalancer with the matching external IP. I imagine an option like this:

```
address-pools:
- name: default
  protocol: layer2
  addresses:
  - 192.168.10.0/29
  externalIPs:
  - 123.123.123.123/29
```

Would this be possible?
