### ISSUE TITLE
L2 use all node IPs without actually specifying each IP/range in yaml

### ISSUE THREAD

**Issue by davidcorbin** [metallb/metallb#514]
Is there a way for Metallb to only allocate node IPs without having to specify each IP or IP range specifically?

For example, a 3 node cluster like:
```
NAME          STATUS   ROLES    AGE    VERSION   INTERNAL-IP      EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
node1.a.com   Ready    <none>   1d     v1.15.3   10.228.128.237   <none>        Ubuntu 16.04.6 LTS   4.4.0-170-generic   docker://19.3.2
node2.a.com   Ready    master   1d     v1.15.3   10.228.128.238   <none>        Ubuntu 16.04.6 LTS   4.4.0-170-generic   docker://19.3.2
node3.a.com   Ready    <none>   1d     v1.15.3   10.228.128.236   <none>        Ubuntu 16.04.6 LTS   4.4.0-170-generic   docker://19.3.2
```

would be configured with the following yaml:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.228.128.236-10.228.128.238
```

Would there be a way to tell Metallb to allocate only node IPs without specifically hardcoding them? E.g.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses: nodeIPs
```
