### ISSUE TITLE
The metallb-controller got "permission denied" when I build docker image by myself

### ISSUE THREAD

**Issue by xieyanker** [metallb/metallb#522]
Hello, I want to build the `metallb-controller` image by myself. But I got `standard_init_linux.go:211: exec user process caused "permission denied"` when I run it in the pod. However, it's no such problem when I use the image which from offical dockerhub. 

I found the main reason is the pod wants to run as non root user. It will become normal if I remove it  . So, I want to know where is my mistake.

```yaml
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
```

my metallb version is `v0.8.2`

I make docker image as follows:

```shell
cd controller
CGO_ENABLED=0 go build
docker build -t registry.icp.com:5000/library/cke/metallb/controller:v0.8.2 .
```
