### ISSUE TITLE
Intra-cluster access is slow

### ISSUE THREAD

**Issue by bantocn** [metallb/metallb#528]
Hi,

I'm using layer 2. The assigned IP address can be accessed normally from outside, but the connection speed is very slow when accessing inside the cluster, which takes about 1 minute. My cluster information is as follows:

- MetalLB: v0.8.2
- Kubernetes: v1.17.2
- Network addon:  flannel v0.11.0-amd64
- kube-proxy mode: ipvs

**Comment by bantocn** [comment]
I have tried using bgp mode, but the problem persists

**Comment by bantocn** [comment]
And I found that using the assigned ip to push the docker image is always wrong, and there is no problem changing to the cluster network

**Comment by bantocn** [comment]
I finally found the reason. It's a problem with ipvs. Switch to iptables and it works.

**Comment by rata** [comment]
Is the problem present when connecting using nodePort instead of the load balancer IP?

**Comment by bantocn** [comment]
Thanks for your reply, everything works fine when using nodeport, and I found that some services cannot function normally when using the IP assigned by metallb. For example: docker push image

**Comment by bantocn** [comment]
@rata Thanks for your reply, everything works fine when using nodeport, and I found that some services cannot function normally when using the IP assigned by metallb. For example: docker push image

**Comment by rata** [comment]
Sorry, not sure I follow. How is `docker push` related to metallb? Are you pushing to a registry server via metallb? Can you please elaborate, with as much detail as possible and concrete detailed examples?

**Comment by bantocn** [comment]
Let me give an example:
metallb assigned IP: 192.168.2.2
NodePort: 192.168.1.2

When using 192.168.2.2 to push the image, it will keep prompting: `Retrying in 5 seconds`, until it is prompted that the push fails.

When I use 192.168.1.2 there is no problem.

**Comment by rata** [comment]
@bantocn sorry, I don't follow. You mention things like docker registry, nodePort (but only a IP?) and I don't know which things are running where and don't really understand the setup.

You have a service type load balancer, right? I assume it has the IP 192.168.2.2 from your comment. What are the pods behind it runnig? And do you connect from where (a pod, a node, a pod in the same node, a node outside the cluster), running what command *exactly*, and what is the output you get?

How have you tested that nodePort works fine?

Please have a look at this: https://metallb.universe.tf/configuration/troubleshooting/, it might help to shed some light

**Comment by rata** [comment]
Friendly ping?

**Comment by bantocn** [comment]
My command is executed as follows:


- execute on k8s master:

```
[root@k8s-master1 ~]# kubectl get svc -n prod
NAME                  TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                         AGE
gitea-service         LoadBalancer   10.96.21.35     10.1.3.6      80:30192/TCP,22:31013/TCP       31d


[root@k8s-master1 ~]# curl -o /dev/null -s -w '%{time_connect}:%{time_starttransfer}:%{time_total}\n' 'http://10.1.3.6'
63.128:63.136:63.136
```


- execute on mac
```
✘ banto@bantodeiMac  ~  curl -o /dev/null -s -w '%{time_connect}:%{time_starttransfer}:%{time_total}\n' 'http://10.1.3.6'
0.003464:0.010184:0.010758
```

**Comment by rata** [comment]
Oh, does it seem the same issue than reported here: https://github.com/metallb/metallb/issues/153#issuecomment-570058857. And it seems to be an upstream issue: https://github.com/metallb/metallb/issues/153#issuecomment-588033577 and a workaround here: https://github.com/metallb/metallb/issues/153#issuecomment-623003250

Can you check if you see the same? In that case, the workaround or using kube-proxy in iptables mode should work around it too.

If that is the same issue, can we close this and move the discussion there (if you have something else to add)? :)

**Comment by bantocn** [comment]
I have tried using iptables mode before, but the problem has not been solved.

**Comment by rata** [comment]
Can you share more about your setup? Is this just a switch and nothing else? are you using vlans or something like that? Can it be related to https://github.com/kubernetes/kubernetes/issues/88986#issuecomment-616906847, for example?

**Comment by chief93** [comment]
Had simillar behavior with my installation, that includes `Mikrotik` as upstream router, but the origin was slow interaction with `MetalLB` Service from the my home network hosts. Solved by simple `NAT` rule:
```
chain: srcnat
action: masquerade
src_address: [home_network_address_range]
dst.address: [metallb_address_range]
```
I think that the main reason of such issue - internal clients tries to reach the `BGP`-announced addresses through the requests through external interface of the upstream router, within some additional routing operations. The proposed NAT rule routes the internal traffic only in internal network.

Here is, for exampe, my case:
![metallb](https://user-images.githubusercontent.com/2089568/82230300-397c0680-9934-11ea-8ff0-f48275f5dc0c.PNG)

**Comment by bantocn** [comment]
My metallb configuration

```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
    - peer-address: 10.1.2.1
      peer-asn: 65000
      my-asn: 65009
    address-pools:
    - name: default
      protocol: bgp
      addresses:
      - 10.1.3.0/24
```

My kube-proxy configuration

```
apiVersion: v1
data:
  config.conf: |-
    apiVersion: kubeproxy.config.k8s.io/v1alpha1
    bindAddress: 0.0.0.0
    clientConnection:
      acceptContentTypes: ""
      burst: 0
      contentType: ""
      kubeconfig: /var/lib/kube-proxy/kubeconfig.conf
      qps: 0
    clusterCIDR: 10.244.0.0/16
    configSyncPeriod: 0s
    conntrack:
      maxPerCore: null
      min: null
      tcpCloseWaitTimeout: null
      tcpEstablishedTimeout: null
    enableProfiling: false
    healthzBindAddress: ""
    hostnameOverride: ""
    iptables:
      masqueradeAll: false
      masqueradeBit: null
      minSyncPeriod: 0s
      syncPeriod: 0s
    ipvs:
      excludeCIDRs: null
      minSyncPeriod: 0s
      scheduler: ""
      strictARP: true
      syncPeriod: 0s
    kind: KubeProxyConfiguration
    metricsBindAddress: ""
    mode: ipvs
```
