### ISSUE TITLE
metallb : Multiple protocol like TCP & UDP usses issue

### ISSUE THREAD

**Issue by shailendra-singh93** [metallb/metallb#530]
As we know load balancer doesn't support multiple protocol such as TCP & UDP in kubernetes services. So is there any way that load balancer could be used for multiple protocols?

**Comment by ttyS0** [comment]
I use the `allow-shared-ip` feature for this. Specifically, the service config for my Unifi controller looks like this:

```
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-tcp
  namespace: unifi
  annotations:
    metallb.universe.tf/allow-shared-ip: "unifi-controller"
spec:
  type: LoadBalancer
  selector:
    app: unifi-controller
  ports:
  - name: unifi-device-inform
    port: 8080
  - name: unifi-controller-ui
    port: 8443
  - name: unifi-http
    port: 8880
  - name: unifi-https
    port: 8843
  - name: unifi-speed-test
    port: 6789
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-udp
  namespace: unifi
  annotations:
    metallb.universe.tf/allow-shared-ip: "unifi-controller"
spec:
  type: LoadBalancer
  selector:
    app: unifi-controller
  ports:
  - name: unifi-discovery
    port: 10001
    protocol: UDP
  - name: unifi-stun
    port: 3478
    protocol: UDP
```
