### ISSUE TITLE
metallb only works when replica=1

### ISSUE THREAD

**Issue by imranrazakhan** [metallb/metallb#540]
I installed two nodes kubernetes on Mac with virtualbox and deployed a nginx app to test metallb but it only works when my app has 1 replica, i found one bug [71596](https://github.com/kubernetes/kubernetes/issues/71596) related to this but for me its failing for both `Local` and `Cluster` values of `externalTrafficPolicy:` 

     - Version of MetalLB : 0.8.3
     - Version of Kubernetes: 1.17.3
     - Name and version of network addon (e.g. Calico, Weave...): flannel
     - Whether you've configured kube-proxy for iptables or ipvs mode : i didnt started kube-proxy
     - OS: CentOS 7.7

metallb config:
```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: mydefault
      protocol: layer2
      addresses:
      - 192.168.0.240-192.168.0.241
```

nginx-srv.yaml:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"nginx","namespace":"default"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"nginx"},"type":"LoadBalancer"}}
  creationTimestamp: "2020-03-11T15:19:11Z"
  name: nginx
  namespace: default
spec:
  clusterIP: 10.103.216.75
  externalTrafficPolicy: Local
  healthCheckNodePort: 30355
  ports:
  - name: http
    nodePort: 31775
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.0.241
```

## kubectl get svc nginx -o wide -n default
```
NAME    TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)        AGE    SELECTOR
nginx   LoadBalancer   10.103.216.75   192.168.0.241   80:31775/TCP   138m   app=nginx
```

When i hit 192.168.0.241 in browser speaker logs shows below, but nothing on browser and request timeout

```
{"caller":"arp.go:102","interface":"enp0s3","ip":"192.168.0.241","msg":"got ARP request for service IP, sending response","responseMAC":"08:00:27:bb:7d:2f","senderIP":"192.168.0.252","senderMAC":"60:f8:1d:b0:5d:22","ts":"2020-03-11T17:49:59.62426469Z"}
{"caller":"arp.go:102","interface":"enp0s3","ip":"192.168.0.241","msg":"got ARP request for service IP, sending response","responseMAC":"08:00:27:bb:7d:2f","senderIP":"192.168.0.252","senderMAC":"60:f8:1d:b0:5d:22","ts":"2020-03-11T17:49:59.624407827Z"}
```

```
$ curl -v 192.168.0.241
*   Trying 192.168.0.241...
* TCP_NODELAY set
* Connection failed
* connect to 192.168.0.241 port 80 failed: Network is unreachable
* Failed to connect to 192.168.0.241 port 80: Network is unreachable
* Closing connection 0
curl: (7) Failed to connect to 192.168.0.241 port 80: Network is unreachable
```
