### ISSUE TITLE
Fix kustomize installation instructions

### ISSUE THREAD

**Issue by johananl** [metallb/metallb#566]
As far as I can tell, the kustomize installation instructions provided [here](https://metallb.universe.tf/installation/#installation-with-kustomize) do not work. The sample kustomization file seems to rely on a new kustomize [feature](https://github.com/kubernetes-sigs/kustomize/pull/2167) which allows fetching resources over HTTP(S). This feature has been merged but isn't yet included in kubectl (I've tested with the current stable `kubectl` which is `v1.18.0`). In addition, the contents of the kustomization seem to be wrong and the instructions contain typos and aren't very clear IMO.

Following is a kustomization which works for me:

```
.
├── configmap.yaml
├── kustomization.yaml
└── secret.yaml
```

```yaml
# kustomization.yaml
namespace: metallb-system

resources:
  - https://raw.githubusercontent.com/metallb/metallb/main/manifests/namespace.yaml?ref=v0.9.3
  - https://raw.githubusercontent.com/metallb/metallb/main/manifests/metallb.yaml?ref=v0.9.3
  - configmap.yaml 
  - secret.yaml
```

```yaml
# configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: bgp
      addresses:
      - 192.168.1.240-192.168.1.250
```

```yaml
# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: verysecurelol
```

Running `kustomize build` in a directory with the files above results in a properly-kustomized YAML output which deploys MetalLB correctly when piped to `kubectl`. I've tested this by building kustomize from `master` at https://github.com/kubernetes-sigs/kustomize/commit/50cc1968e4c8c60a4384fc6eae17b9f81e69cd97.

I suggest we make the following changes to the docs:

- Fix `kustomization.yaml` to point at the latest versions of `metallb.yaml` and `namespace.yaml` over HTTPS using the correct syntax as specified [here](https://github.com/knative/serving/releases/download/v0.12.0/serving.yaml). Note that we should link to a **raw** GitHub URL.
- Mention the minimal version of kubectl required for the above to work.

**alternatively**

- Replace the HTTP reference in `kustomization.yaml` with a YAML snippet which can be copy-pasted.

In addition, I suggest we do the following changes to the kustomize section in the docs:

- Include sample snippets for `namespace.yaml` and `secret.yaml`. Without these files the example fails, and the reader may not know what to put in these files.
- Change `*.yml` to `*.yaml`. Both options work but the latter seems much more common these days.
- Rephrase the following sentence: `You can install MetalLB with kustomize by pointing on the remote kustomization fle :`.
  - `fle` should be `file`.
  - There is an extra space before the colon.
  - The phrasing "by pointing on the remote kustomization file" is confusing in my opinion. It is not clear to me what I am supposed to do.
