### ISSUE TITLE
allow selecting services to announce with the bgb speaker

### ISSUE THREAD

**Issue by juliantaylor** [metallb/metallb#604]
We would like to be able to deploy multiple speaker pods (bgb mode) in the cluster which select different subsets of service ips to announce.

The usecase is that our kubernetes cluster has 3 master nodes and many workers. The apiserver is exposed via a metallb speaker announcing the ip in bgb mode. For auditing we need the correct source ips in the apiserver audit log we need to ensure that a speaker is running on the master nodes and the apiserver is using an `externalTrafficPolicy: Local` service (as our sdn (calico) does not retain source ips for cross node traffic).

But the speaker nodes on the master machines will also announce all `externalTrafficPolicy: Cluster` services on the master node leading to worker pod traffic being routed over the master nodes.

We would like to avoid unnecessary traffic on the master nodes by deploying two deployments of speaker pods with the set on the master nodes only announcing the local services on the master (the apiserver).

There would be several ways to implement this and we could provide a patch should this be accepted:

- add a boolean flag to the speaker to only announce `externalTrafficPolicy: Local` services, this is very simple and would fulfill our usecase
- add a namespace selector configuration to the speaker that way the apiserver service can be moved into its own namespace and a speaker set added for that namespace. The other deployment would then watch all other namespaces. This would probably be done by watching all namespaces and filtering the received events to avoid too many watches if there are many namespaces.
- add a label selector to the service watch, this is simple too and would work but would require admission policies to restrict who may set that label.

**Comment by johananl** [comment]
Sounds useful to me. I haven't checked the feasibility though so I'll let other folks chime in.

IMO it would be nice to choose an approach which solves the problem in a generic and flexible way rather than do something that's very tailored to the specific use case. I can image there could be other use cases where it would be useful to determine which services should be advertised by a specific set of speakers. Sounds like your 3rd suggestion goes in this direction IIUC.

I'm wondering what would be the right way to represent such functionality in the configuration. Were you thinking about something like the following:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
    - peer-address: 10.0.0.1
      peer-asn: 64501
      my-asn: 64500
      # Advertise only services with the label `type: special`.
      service-selectors:
      - match-labels:
          type: special
```

Also, I didn't understand your point regarding the need for admission policies. Could you elaborate?

**Comment by juliantaylor** [comment]
In a multi tenant cluster without admission policies there are no restrictions for labels that users can add to their service objects.
So any user of the cluster could add the labels to have their services exposed on speakers you wanted to have restricted to for example only admin components.

This can only be restricted via an admission controller (for example something based on open policy agent) that disallows labels based on who deploys them.

Of course a multi tenant cluster should also have these type of admission controllers so a label selector is still a fine solution, but you also get quite far without them in stock kubernetes so it is an additional hurdle in using this solution.

**Comment by juliantaylor** [comment]
The need for admission control is only something for the documentation of the feature, not something metallb should implement.

**Comment by johananl** [comment]
Thanks @juliantaylor, that's clearer now. Let's wait for some more feedback on the details. I'm wondering if it makes sense to add a knob under `peers`, especially with the potential of https://github.com/metallb/metallb/pull/593 coming up. There are most likely other alternatives such as this one:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    # Advertise special services only from master nodes
    advertise-maps:
    - service-selectors:
      - match-labels:
          type: special
      node-selectors:
      - match-labels:
          node.kubernetes.io/master: ""
    peers:
    - peer-address: 10.0.0.1
      peer-asn: 64501
      my-asn: 64500
```

We could then have a logic which checks for a matching "advertise map" (not sure about this naming) when a service is added/changed and only creates the advertisement if the node on which the speaker runs matches the node selectors. Other services get advertised as usual by all speakers.
