### ISSUE TITLE
Packets route through default gateway than the intended route

### ISSUE THREAD

**Issue by VanagaS** [metallb/metallb#610]
Given a setup:
eth0: public IP, default gateway through this.
eth0.vlan1: private network (kubernetes cluster nodes run on this network)
eth0.vlan2: public IP pool with a dedicated route table

After Metallb assigns an IP from public IP pool (from eth0.vlan2) to a svc->pod->node, if we do a traceroute of that public IP from Internet, the packet lands through eth0 instead of via eth0.vlan2.

However, if we directly assign the external IP from the pool to eth0.vlan2 interface on a node and if we do a traceroute of that public IP from Internet, the packet lands through eth0.vlan2 correctly.

Because of this, the return packets (in case of metallb assigned IP) are routed through eth0.vlan2 and hence never reach the requester (as the packets actually originate from eth0).

Is there anything that we can do for this use case?

**Comment by jmozd** [comment]
+1

I've been unsuccessful in creating policy-based routing for Linux kernel 5.3.18 for a similar scenario:

- eth0: "cluster-internal network". Default route points to a router on that network (routing table "main"), but is only intended for management traffic
- eth1: "services network". No IP assigned at OS level, but MetalLB has a pool of IP addresses handled by the network eth1 is attaching to. There's a separate router on that network, that's forwarding all traffic for the services network to remotes.
- created separate routing table (local network route for services network, plus a default route pointing at the router on the services network
- for test: created a rule for a specific target test subnet ("ip rule add to a.b.c.0/24 table <separate table>"), pointing at the separate routing table: clients on that test subnet can access the services (tcpdump verifies that all packets ingress and egress go via eth1).
- instead, created a rule "ip rule add from <MetalLB IP pool subnet> table <separate table>": Despite the "ip rule", packets with a sender address from the MetalLB pool still are routed via eth0 and the wrong default gateway (tcpdump verifies that ingress traffic for the services IPs is via eth1, but egress falsely goes via eth0).

(In case it matters: Same behavior if eth1 has a (distinct) IP within the services IP subnet assigned.)

If I manually assign a services IP to eth1, I can verify via tcpdump that the "ip rule add from ..." actually works with that kernel (test traffic egress going via eth1), so it seems to be something MetalLB-specific.

Any help you can provide? Anything I can add to get to the root of this?

**Comment by jochenseeber** [comment]
Same here. Setup is:
* eth0: External network
* eth0.vlan: VLAN with public IP range for load balancer
* Routing policy set up, routing works without MetalLB with manually assigned IP address form MetalLB's pool

Packed come in from eth0.vlan, are processed and get dropped on their way out, instead of routed through eth0.vlan

**Comment by harridu** [comment]
metoo. I am using real network interfaces instead of vlans. iptables is based on nft.

**Comment by harridu** [comment]
Using ipvs mode and strict arp for kube-proxy did the trick.

**Comment by LensHunnel** [comment]
Hello, 

I'm trying to create policy-based routing for Linux kernel 5.10.0-19-cloud-amd64 with two differents network interfaces. When I add the following command : 
```bash
 root@worker1/#: ip rule add from 192.168.209.0/24 table rt2
 root@worker1/#: ip rule show
 0:      from all lookup local
 32765:  from 192.168.209.0/24 lookup rt2
 32766:  from all lookup main
 32767:`  from all lookup default
```
after some seconds the rule disapears, maybe someone have an idea ? 

```bash
 root@worker1/#: ip rule show
 0:      from all lookup local
 32766:  from all lookup main
 32767:`  from all lookup default
```
Thanks

**Comment by zentavr** [comment]
I have vanilla Kubernetes 1.26.1, Calico v3.25.0, MetalLB 0.13.7
Kernel Ubuntu 22.04.1 5.15.0-58-generic.

Cluster has 3 master nodes and 3 worker nodes. My ISP delegated  `a.b.c.184/29` subnet to me where `a.b.c.185` is  a gateway. The subnet is delegated over VLAN.

Master node looks like:
```
ens6p18: 10.93.79.x/24 - default gateway 10.93.79.83
```

Worker node:
```
ens6p18: 10.93.79.x/24 - default gateway 10.93.79.83
ens6p19: has not IP address, looks into VLAN where a.b.c.185 gateway sits
```

I'd installed MetalLB by helm chart. Values are:
```yaml
---
loadBalancerClass: "metallb"
controller:
  logLevel: "debug"

speaker:
  logLevel: "debug"
```

Namespace had been created with the next labels:
```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      ...
  creationTimestamp: "2023-02-04T23:30:42Z"
  labels:
    kubernetes.io/metadata.name: metallb
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
  name: metallb
  resourceVersion: "39097"
  uid: 406ca23e-1803-4887-93c0-cade9cf0ea7a
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
```

The CRDs are:
```yaml
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: vswitch-4046-pool
  namespace: metallb
spec:
  addresses:
    - a.b.c.186-a.b.c.190
  autoAssign: true
  avoidBuggyIPs: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  annotations:
  name: vswitch-4046-adv
  namespace: metallb
spec:
  interfaces:
  - enp6s19
  ipAddressPools:
  - vswitch-4046-pool
  nodeSelectors:
  - matchLabels:
      metallb.universe.tf/vSwitch-4046-pool: "true"
```

The worker nodes which have the VLAN onboard have the appropriate label:
```yaml
apiVersion: v1
kind: Node
metadata:
  annotations:
    csi.volume.kubernetes.io/nodeid: '{"csi.tigera.io":"worker01.k8s.cti.local"}'
    kubeadm.alpha.kubernetes.io/cri-socket: /var/run/cri-dockerd.sock
    node.alpha.kubernetes.io/ttl: "0"
    projectcalico.org/IPv4Address: 10.93.79.41/24
    projectcalico.org/IPv4VXLANTunnelAddr: 172.20.130.0
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2023-02-04T21:25:19Z"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: worker01.k8s.cti.local
    kubernetes.io/os: linux
    metallb.universe.tf/vSwitch-4046-pool: "true"
  name: worker01.k8s.cti.local
spec:
 ...
```

The problem is that I can see the incoming traffic by `tcpdump` at `enp6s19`, but the client from the internet does not receive any reply.

P.S.: Source base routing is applied:
```shell
root@worker01:~# ip rule list
0:	from all lookup local
100:	from all fwmark 0x3fb lookup rt_pb_enp6s19_1019
110:	from a.b.c.184/29 lookup rt_pb_enp6s19_1019
32766:	from all lookup main
32767:	from all lookup default
root@worker01:~# ip route list table rt_pb_enp6s19_1019
default via a.b.c.185 dev enp6s19 onlink
a.b.c.184/29 dev enp6s19 scope link
root@worker01:~# ip link sh enp6s19
3: enp6s19: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether ea:46:17:e4:0d:e1 brd ff:ff:ff:ff:ff:ff
root@worker03:~# ip a l enp6s19
3: enp6s19: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether ea:46:17:e4:0d:e1 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::e846:17ff:fee4:de1/64 scope link
       valid_lft forever preferred_lft forever
root@worker01:~# cat /proc/sys/net/ipv4/conf/all/rp_filter
0
root@worker01:~# cat /proc/sys/net/ipv4/conf/default/rp_filter
0
root@worker01:~# cat /proc/sys/net/ipv4/conf/enp6s19/rp_filter
0
```

**Comment by zentavr** [comment]
What I see with tcpdump at `enp6s19`:
```
02:04:54.858291 IP x.y.z.230.55215 > a.b.c.186.443: Flags [S], seq 1693191197, win 65535, options [mss 1460,nop,wscale 6,nop,nop,TS val 266762460 ecr 0,sackOK,eol], length 0
02:04:54.858847 IP 10.93.79.43.44660 > 10.93.79.41.4789: VXLAN, flags [I] (0x08), vni 4096
IP 172.20.173.128.34786 > 172.20.130.12.443: Flags [S], seq 1693191197, win 65535, options [mss 1460,nop,wscale 6,nop,nop,TS val 266762460 ecr 0,sackOK,eol], length 0
02:04:55.857121 IP x.y.z.230.55215 > a.b.c.186.443: Flags [S], seq 1693191197, win 65535, options [mss 1460,nop,wscale 6,nop,nop,TS val 266763461 ecr 0,sackOK,eol], length 0
02:04:55.857510 IP 10.93.79.43.44660 > 10.93.79.41.4789: VXLAN, flags [I] (0x08), vni 4096
IP 172.20.173.128.34786 > 172.20.130.12.443: Flags [S], seq 1693191197, win 65535, options [mss 1460,nop,wscale 6,nop,nop,TS val 266763461 ecr 0,sackOK,eol], length 0
02:04:56.858154 IP x.y.z.230.55215 > a.b.c.186.443: Flags [S], seq 1693191197, win 65535, options [mss 1460,nop,wscale 6,nop,nop,TS val 266764461 ecr 0,sackOK,eol], length 0
02:04:56.858385 IP 10.93.79.43.44660 > 10.93.79.41.4789: VXLAN, flags [I] (0x08), vni 4096
IP 172.20.173.128.34786 > 172.20.130.12.443: Flags [S], seq 1693191197, win 65535, options [mss 1460,nop,wscale 6,nop,nop,TS val 266764461 ecr 0,sackOK,eol], length 0
02:04:57.871608 IP x.y.z.230.55215 > a.b.c.186.443: Flags [S], seq 1693191197, win 65535, options [mss 1460,nop,wscale 6,nop,nop,TS val 266765462 ecr 0,sackOK,eol], length 0
02:04:57.871818 IP 10.93.79.43.44660 > 10.93.79.41.4789: VXLAN, flags [I] (0x08), vni 4096
IP 172.20.173.128.34786 > 172.20.130.12.443: Flags [S], seq 1693191197, win 65535, options [mss 1460,nop,wscale 6,nop,nop,TS val 266765462 ecr 0,sackOK,eol], length 0
02:04:58.860371 IP x.y.z.230.55215 > a.b.c.186.443: Flags [S], seq 1693191197, win 65535, options [mss 1460,nop,wscale 6,nop,nop,TS val 266766463 ecr 0,sackOK,eol], length 0
02:04:58.860552 IP 10.93.79.43.44660 > 10.93.79.41.4789: VXLAN, flags [I] (0x08), vni 4096
IP 172.20.173.128.34786 > 172.20.130.12.443: Flags [S], seq 1693191197, win 65535, options [mss 1460,nop,wscale 6,nop,nop,TS val 266766463 ecr 0,sackOK,eol], length 0
```

If you notice - Immediately after `IP x.y.z.230.55215 > a.b.c.186.443` there is another one `10.93.79.43.44660 > 10.93.79.41.4789: VXLAN` where `172.20.130.12` is the Pod IP address which sits at the neighbor worker. Should that packet come over `enp6s19` where is no IP addresses at all? I expected that on `enp6s18`

**Comment by zentavr** [comment]
In my case the issue was in source based routing. I had the rule `iptables -t mangle -A PREROUTING -i enp6s19 -j MARK --set-mark 1019` and this made the second packet to go over the same interface but not the another one.

**Comment by johnsimcall** [comment]
@zentavr are you saying you fixed your issue? I have been having the same problem. Do you know where your `PREROUTING` rule came from, or if it came back after Node reboots and upgrades?

**Comment by zentavr** [comment]
@johnsimcall yes, I did. I had a mark rule with iptables and an `ip rule` which caused the problem. Because of this the second packet (VXLAN traffic) had been sent from the wrong interface and the Pod had never received that.

**Comment by zentavr** [comment]
@johnsimcall do you want the configs?

**Comment by johnsimcall** [comment]
Thank you! Could you please share your configs?

**Comment by zentavr** [comment]
@johnsimcall As I mentioned before - I have 6 nodes in the cluster. API is available via dedicated IP (it could be haproxy, kube-vip in my case). Cluster was installed using `kubeadm` utillity.
```
10.93.79.37    master01.k8s.cti.local
10.93.79.38    master02.k8s.cti.local
10.93.79.39    master03.k8s.cti.local
10.93.79.41    worker01.k8s.cti.local
10.93.79.42    worker02.k8s.cti.local
10.93.79.43    worker03.k8s.cti.local

10.93.79.40 api.k8s.cti.local
```

Kubeadm config:
```yaml
---
# kubeadm-config.yaml
# kubeadm init --upload-certs --config kubeadm-config.yaml
#
# Syntax: https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
kubernetesVersion: v1.26.1
# Our config goes here
clusterName: "cti-cluster"
controlPlaneEndpoint: api.k8s.cti.local
apiServer:
  certSANs:
    - api.k8s.cti.local
#  ControlPlaneComponent:
#    extraArgs:
#      - ""
networking:
  serviceSubnet: 10.240.0.0/12
  podSubnet: 172.20.0.0/16
  dnsDomain: "cti.local"
controllerManager:
  extraArgs:
    "bind-address": "0.0.0.0"
    "secure-port": "10257"
scheduler:
  extraArgs:
    "bind-address": "0.0.0.0"
    "secure-port": "10259"
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
metricsBindAddress: "0.0.0.0"
mode: "ipvs"
ipvs:
  strictARP: true
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  #advertiseAddress: ""
  bindPort: 6443
nodeRegistration:
  criSocket: "unix:///var/run/cri-dockerd.sock"
  kubeletExtraArgs:
    v: "4"
  imagePullPolicy: "IfNotPresent"
```

CNI Driver: Calico (tested with Flannel as well). Calico was installed by Helm Chart:
```yaml
---
# helm install calico projectcalico/tigera-operator --version v3.25.0 -f calico-config.yaml --namespace tigera-operator
installation:
  cni:
    type: Calico
  calicoNetwork:
    bgp: Disabled
    ipPools:
    - cidr: 172.20.0.0/16
      encapsulation: VXLAN
```

MetalLB was installed by a Helm chart:
```yaml
---
# kubectl apply -f metallb-namespace.yml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
  name: metallb
```

And helm config (in my case I wanted `loadBalancerClass`, because have other LBs as well like `kube-vip` and would like to specify which LB exactly the service should use - feature available from Kubernetes 1.24+ as I recall):
```yaml
---
# helm upgrade metallb metallb/metallb     --install     --namespace metallb     --values metallb-values.yaml
loadBalancerClass: "metallb"
controller:
  logLevel: "debug"

speaker:
  logLevel: "debug"
```

MetalLB CRDs:
```yaml
---
# kubectl -n metallb apply -f metallb-crds.yml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: local-vlan79-pool
spec:
  addresses:
  - 10.93.79.50-10.93.79.79
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: local-vlan79-adv
spec:
  ipAddressPools:
  - local-vlan79-pool
  nodeSelectors:
  - matchExpressions:
    - key: "metallb.universe.tf/local-vlan79-pool"
      operator: "Exists"
  interfaces:
  - enp6s18
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: vswitch-4046-pool
spec:
  addresses:
  - 1.2.3.186-1.2.3.190
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: vswitch-4046-adv
spec:
  ipAddressPools:
  - vswitch-4046-pool
  nodeSelectors:
  - matchExpressions:
    - key: "metallb.universe.tf/vSwitch-4046-pool"
      operator: "Exists"
  interfaces:
  - enp6s19
``` 

The workers has appropriate labels:
```shell
kubectl label node worker01.k8s.cti.local metallb.universe.tf/local-vlan79-pool=""
kubectl label node worker02.k8s.cti.local metallb.universe.tf/local-vlan79-pool=""
kubectl label node worker03.k8s.cti.local metallb.universe.tf/local-vlan79-pool=""

kubectl label node worker01.k8s.cti.local metallb.universe.tf/vSwitch-4046-pool=""
kubectl label node worker02.k8s.cti.local metallb.universe.tf/vSwitch-4046-pool=""
kubectl label node worker03.k8s.cti.local metallb.universe.tf/vSwitch-4046-pool=""
```

**Comment by zentavr** [comment]
@johnsimcall Source Based Routing.

Worker nodes does not handle the dedicated routable IPv4 number. `enp6s19` is just UP without any IP at all:
```
# cat /etc/network/interfaces
auto enp6s19
iface enp6s19 inet manual
```

IProute2 table (`/etc/iproute2/rt_tables.d/1019_pb.conf`):
```
1019 rt_pb_enp6s19_1019
```

Rules:
```
root@worker01:~# ip rule list
0:	from all lookup local
99:	from 1.2.3.184/29 to 172.20.0.0/16 lookup main
110:	from 1.2.3.184/29 lookup rt_pb_enp6s19_1019
32766:	from all lookup main
32767:	from all lookup default
root@worker01:~# ip route list
default via 10.93.79.83 dev enp6s18 onlink
10.93.79.0/24 dev enp6s18 proto kernel scope link src 10.93.79.41
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
172.20.0.0/24 via 172.20.0.0 dev flannel.1 onlink
172.20.1.0/24 via 172.20.1.0 dev flannel.1 onlink
172.20.2.0/24 via 172.20.2.0 dev flannel.1 onlink
172.20.3.0/24 via 172.20.3.0 dev flannel.1 onlink
172.20.4.0/24 via 172.20.4.0 dev flannel.1 onlink
172.20.5.0/24 dev cni0 proto kernel scope link src 172.20.5.1
root@worker01:~# ip route list table rt_pb_enp6s19_1019
default via 1.2.3.185 dev enp6s19 onlink
1.2.3.184/29 dev enp6s19 scope link
```

Here:
- `172.20.0.0/16` - pod subnet

Before I had the rules which I'd removed (check up https://github.com/metallb/metallb/issues/610#issuecomment-1418326496):
```
iptables -t mangle -A PREROUTING -i enp6s19 -j MARK --set-mark 1019
ip rule add 100 from all fwmark 0x3fb lookup rt_pb_enp6s19_1019
```

This caused the problem like this:
```
02:04:54.858291 IP x.y.z.230.55215 > a.b.c.186.443: Flags [S], seq 1693191197, win 65535, options [mss 1460,nop,wscale 6,nop,nop,TS val 266762460 ecr 0,sackOK,eol], length 0
02:04:54.858847 IP 10.93.79.43.44660 > 10.93.79.41.4789: VXLAN, flags [I] (0x08), vni 4096
IP 172.20.173.128.34786 > 172.20.130.12.443: Flags [S], seq 1693191197, win 65535, options [mss 1460,nop,wscale 6,nop,nop,TS val 266762460 ecr 0,sackOK,eol], length 0
```

How you can see at the interface `enp6s19`, after worker receives a packet `IP x.y.z.230.55215 > a.b.c.186.443` (which is expected) there is another one here: `10.93.79.43.44660 > 10.93.79.41.4789: VXLAN`. I think that `iptables mark` + `ip rule` made the kernel issue the packet (Kubernetes overlay network) at the wrong interface.

P.S.: Examples how to set up routing are [here](https://itnext.io/configuring-routing-for-metallb-in-l2-mode-7ea26e19219e).

**Comment by zentavr** [comment]
No plans to add that into the docs?

**Comment by OLED1** [comment]
@zentavr A documentation how to deal with multiple interfaces when using metallb with calico would be great. May open an additional ticket as feature request?

**Comment by OLED1** [comment]
When i am using @zentavr config, than my ingress controller does not get an External IP:
```
kubectl get svc -n nginx-ingress 
NAME                                 TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                      AGE
ingress-nginx-controller             LoadBalancer   10.241.20.90   <pending>     80:30101/TCP,443:30361/TCP   80m
ingress-nginx-controller-admission   ClusterIP      10.240.2.31    <none>        443/TCP                      80m
```

My metallb ippool and l2 config:
```
cat metallb-crds.yml 
---
# kubectl -n metallb apply -f metallb-crds.yml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: vswitch-1286-pool
spec:
  addresses:
  - 1.2.3.17-1.2.3.27
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: vswitch-1286-adv
spec:
  ipAddressPools:
  - vswitch-1286-pool
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: nodeA.esrv.local
  interfaces:
```

Any ideas?

**Comment by fedepaol** [comment]
@OLED1 please file a separate issue for this. Also, try to have a look at the troubleshooting guide https://metallb.universe.tf/troubleshooting/

**Comment by travisghansen** [comment]
For those who need I have a project to address this here: https://github.com/travisghansen/metallb-node-route-agent

It currently works with cilium and the kube-proxy replacement or calico+kube-proxy+ipvs. I assume it could be tweaked to work with kube-proxy+iptables as well with relatively minor rules.

For the ipvs mode I do a similar set of iptables rules as described in the previous comment but my approach is to use conntrack on connections that aren’t from cluster peers (ie: outside world) and then copy the connection mark to packets in the forward chain. Combine that with fwmark on the rule and so far seems to work perfectly as things do in cilium.

Of note, none of the iptables logic is necessarily built-in but I allow arbitrary scripts to be executed pre/post reconcile and the container has all the necessary binaries etc to do what you need (iptables, ipset, conntrack, ip, kubectl, jq, etc). If anyone has any improvements or feedback they are welcome!

**Comment by azmmmm** [comment]
For those who still struggle in this problem, I may have a simple hacky solution that avoid dealing with **iptables**.  
My setting is (metallb+calico+kube-proxy+ipvs-strict-arp) ubuntu22.04 and L2advertisement
and ens160 for 10.0.0.0/24 internal management network, ens192 for public network at 172.30.2.0/24.

I think the reason for this headache may be the policy base routing does not get applied. (I doubt that it's because we set kube-proxy from iptables mod to ipvs mode.)

Analysis
---

First I use this [setup](https://itnext.io/configuring-routing-for-metallb-in-l2-mode-7ea26e19219e#:~:text=add%20the%20routes%3A-,ip%20route%20add%201.2.3.0/24%20dev%20eth0.100%20table%20100%0Aip%20route%20add%20default%20via%201.2.3.1%20table%20100,-Pay%20attention%20that)
```
@k8s-worker-3:~$ ip route
default via 10.1.1.1 dev ens160 proto dhcp src 10.1.1.134 metric 100 
10.1.1.0/24 dev ens160 proto kernel scope link src 10.1.1.134 metric 100 
10.1.1.1 dev ens160 proto dhcp scope link src 10.1.1.134 metric 100  
blackhole 192.168.69.192/26 proto bird 
192.168.140.0/26 via 10.1.1.133 dev tunl0 proto bird onlink 
192.168.182.64/26 via 10.1.1.81 dev tunl0 proto bird onlink 
192.168.196.0/26 via 10.1.1.80 dev tunl0 proto bird onlink 
192.168.230.0/26 via 10.1.1.121 dev tunl0 proto bird onlink 
@k8s-worker-3:~$ ip rule
0:	from all lookup local
32764:	from 172.30.2.0/24 to 192.168.0.0/16 lookup main proto static
32765:	from 172.30.2.0/24 lookup 188 proto static
32766:	from all lookup main
32767:	from all lookup default
@k8s-worker-3:~$ ip route show table 188
default via 172.30.2.1 dev ens192 proto static onlink 
```

And both incoming traffic from public net and internal net can reach the node, but no outgoing traffic send.

```
~$ sudo tcpdump -i any 'port 80'

ens192 In  IP [public net].61.32.25886 > 172.30.2.133.http: Flags [S], seq 1648037408, win 42340, options [mss 1460,nop,nop,sackOK,nop,wscale 11], length 0
ens192 In  IP [public net].149.208.57414 > 172.30.2.133.http: Flags [S], seq 4126846053, win 1024, length 0
ens192 In  IP 172.30.2.130.59977 > 172.30.2.133.http: Flags [S], seq 3224408039, win 65535, options [mss 1400,nop,wscale 6,nop,nop,TS val 1944409597 ecr 0,sackOK,eol], length 0
```

after i add route
```
172.30.2.0/24 dev ens192 proto static scope link 
```

I managed to get access from the same network. 

```
ens192 In  IP 172.30.2.130.60071 > 172.30.2.133.http: Flags [S], seq 523314498, win 65535, options [mss 1400,nop,wscale 6,nop,nop,TS val 1684829178 ecr 0,sackOK,eol], length 0
tunl0 Out IP k8s-worker-3.52990 > 192.168.230.11.http: Flags [S], seq 523314498, win 65535, options [mss 1400,nop,wscale 6,nop,nop,TS val 1684829178 ecr 0,sackOK,eol], length 0
tunl0 In  IP 192.168.230.11.http > k8s-worker-3.52990: Flags [S.], seq 1229294084, ack 523314499, win 64260, options [mss 1440,sackOK,TS val 778290393 ecr 1684829178,nop,wscale 7], length 0
ens192 Out IP 172.30.2.133.http > 172.30.2.130.60071: Flags [S.], seq 1229294084, ack 523314499, win 64260, options [mss 1440,sackOK,TS val 778290393 ecr 1684829178,nop,wscale 7], length 0
```

however, there is still no outgoing traffic from public net.
But after i add route.
```
default via 172.30.2.1 dev ens192 proto static 
```
I manage to get access and outgoing traffic from both public and internal network.
So my conclusion is that k8s only take routes from main table, and the policy base routing does not get applied.

Solution
---

### Simply add default route 
```
default via 172.30.2.1 dev ens192 proto static 
```
defect: the node don't actually get an IP in ens192. So the machine itself and ohter pods in this node can't access internet.

(
    ens192 Out IP k8s-worker-3.http > [internet].32.46970  
    it's using incorrect ip for ens192(from lo or other interface i supposed), so no way for the reply to get back.
)
### A little better hacky solution (enough for most use case)
Statically assign an IP to ens192, and add default route.

I assign the exact same IP for the node to do L2Advertisement. And it's working fine. But you will need to specify the node for speaker.

```
network:
  ethernets:
    ens160:
      dhcp4: true
    ens192:
      addresses:
      - 172.30.2.133/24
      routes:
      - to: default
        via: 172.30.2.1

  version: 2
```
```
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: hack-172.30.2.133
  namespace: metallb
spec:
  ipAddressPools:
  - hack-172.30.2.133
  nodeSelectors:
  - matchLabels:
      has-ip: "172.30.2.133"
```
```
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: hack-172.30.2.133
  namespace: metallb
spec:
  addresses:
  - 172.30.2.133/32 
---
```
Also you can assign other ip that is not in the pool. So that you don't have to do nodeSelectors and get a larger pool for speaker to choose from. But it will take one ip for access ineternet.

Or just make sure the assigned ip does not get advertised by other node.

But still, the approch so far must use interface ens192 for access internet. In my senario, the ens192 might have some limited access to the internet. (yeah, chinese firewall) I want it to access internet using ens160 while being accessable in ens192.

### More hacky way
I set ip forward for router of ens160(10.1.1.1 in my case). Which make a traffic like this.   
incoming ens192 ->k8s node-> outgoing ens160
```
ens192 In  IP [public client].32.54724 > k8s-worker-3.http: Flags [.], ack 716, win 21, length 0
tunl0 Out IP k8s-worker-3.63364 > 192.168.230.11.http: Flags [.], ack 716, win 21, length 0
tunl0 In  IP 192.168.230.11.http > k8s-worker-3.63364: Flags [.], ack 849, win 502, length 0
ens160 Out IP k8s-worker-3.http > [public client].32.54724: Flags [.], ack 849, win 502, length 0
```

```
network:
  ethernets:
    ens160:
      dhcp4: true
    ens192:
      addresses:
      - 172.30.2.4/24 # set an ip not in advertised pool
  version: 2
```
```
default via 10.1.1.1 dev ens160 proto dhcp src 10.1.1.134 metric 100 
10.1.1.0/24 dev ens160 proto kernel scope link src 10.1.1.134 metric 100 
10.1.1.1 dev ens160 proto dhcp scope link src 10.1.1.134 metric 100  
172.30.2.0/24 dev ens192 proto kernel scope link src 172.30.2.4 metric 100 
blackhole 192.168.69.192/26 proto bird 
192.168.140.0/26 via 10.1.1.133 dev tunl0 proto bird onlink 
192.168.182.64/26 via 10.1.1.81 dev tunl0 proto bird onlink 
192.168.196.0/26 via 10.1.1.80 dev tunl0 proto bird onlink 
192.168.230.0/26 via 10.1.1.121 dev tunl0 proto bird onlink 
```

I'm hoping someone can come up with a better solution without modifying router setting or using complicated packet filter.

Using Iptables is just too complicated for me, and i can't configure it right using the method others provided. Sorry! :)
