### ISSUE TITLE
Feature request: addresses assignment outside of Service definition

### ISSUE THREAD

**Issue by chief93** [metallb/metallb#616]
Hi everyone!
First of all I wish to thank the developers of MetalLB for such a great and easy-to-use software :)

My question could be a little bit silly, but I want to know - is there some possibility to reserve the IP from some pool for specific `Service`, outside of the Service itself (without assign `spec.loadBalancerIP` in the `Service`)? If no, then I wish to post such behavior as a feature request :)

The assignment can be implemented for end-user in different ways, for example, by some new Kubernetes [CustomResourceDefinition](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/):
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: leases.metallb
spec:
  group: metallb
  versions:
   - name: v1
     served: true
     storage: true
     schema:
       openAPIV3Schema:
         type: object
         properties:
           spec:
             type: object
             properties:
               serviceName:
                 type: string
               serviceNamespace:
                 type: string
               addresses:
                 type: array
                 items:
                   type: object
                   properties:
                     pool:
                       type: string
                     address:
                       type: string
  # either Namespaced or Cluster
  scope: Cluster
  names:
    plural: leases
    singular: lease
    kind: Lease
    shortNames:
     - l
```
Then we can use it like this:
```yaml
apiVersion: metallb/v1
kind: Lease
metadata:
  name: myservice-lease1
spec:
  serviceName: myservice
  serviceNamespace: myservice-namespace
  addresses:
   - pool: my-ipv4pool
     address: 192.168.10.10
```

In another way, we can set this directly in the MetalLB `ConfigMap`:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
     - peer-address: 10.0.0.1
       peer-asn: 64501
       my-asn: 64500
    address-pools:
     - name: default
       protocol: bgp
       addresses:
        - 192.168.10.0/24
    leases:
     - serviceName: myservice
       serviceNamespace: myservice-namespace
       pool: default
       address: 192.168.10.10
```

Such feature would have a big opporunity impact to the managing of the any types of installations, because the app infrastructure wouldn't need to "keep in mind" the assigned addresses and other `LoadBalancer` specific options.
