### ISSUE TITLE
Hyper-V + ubuntu + kubeadm + callico + metallb = external pending

### ISSUE THREAD

**Issue by survivant** [metallb/metallb#617]
(I recreated the setup with vmware, and metallb assign a external IP)

I have a little Setup on Hyper-v (windows 10): 1 master + 2 workers.  I'm not able to obtain an external IP for nginx.

my 3 VM have differents MAC  and they are on the same virtual switch : vagrant (external + OS autorize to share... (I had to translate from french.. not sure the exact term here)

```

kubectl get nodes -o wide

NAME          STATUS   ROLES    AGE     VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION       CONTAINER-RUNTIME
k8s-master    Ready    master   4h56m   v1.18.3   192.168.50.8    <none>        Ubuntu 18.04.4 LTS   4.15.0-101-generic   docker://19.3.11
k8s-worker1   Ready    <none>   4h52m   v1.18.3   192.168.50.9    <none>        Ubuntu 18.04.4 LTS   4.15.0-101-generic   docker://19.3.11
k8s-worker2   Ready    <none>   4h49m   v1.18.3   192.168.50.10   <none>        Ubuntu 18.04.4 LTS   4.15.0-101-generic   docker://19.3.11
vagrant@k8s-master:/vagrant/provision$
```
I installed metallb with these commands
```
      - kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/namespace.yaml
      - kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/metallb.yaml
      - kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"
```
my configuration is
```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.50.200-192.168.50.250
```

I install nginx with this (https://raw.githubusercontent.com/google/metallb/v0.9.3/manifests/tutorial-2.yaml    but I had to change the apiVersion of the deployment)
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1
        ports:
        - name: http
          containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer


vagrant@k8s-master:/vagrant/provision$ kubectl get svc -o wide
NAME         TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE     SELECTOR
kubernetes   ClusterIP      10.96.0.1       <none>        443/TCP        4h59m   <none>
nginx        LoadBalancer   10.101.204.85   <pending>     80:32134/TCP   34m     app=nginx
```
I'm using kubernetes 1.18.3  (installed with kubeadm)
