### ISSUE TITLE
Look into a generic pool <> node affinity mechanism

### ISSUE THREAD

**Issue by johananl** [metallb/metallb#630]
We have multiple requests around being able to announce specific IPs from a specific subset of speakers:

- https://github.com/metallb/metallb/issues/511
- https://github.com/metallb/metallb/issues/383

We also have a PR which addresses this for BGP only: https://github.com/metallb/metallb/pull/596

I suggest we look into a **generic** (namely protocol-independent) way for adding this functionality. AFAICT, the UX could be something like the following:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: bgp # Or layer2!
      addresses:
      - 198.51.100.0/24
      # Announce IPs in this pool only from
      # speakers running on matching nodes.
      node-selectors:
      - match-labels:
          rack: frontend
```

We can then check the node selectors and decide whether to announce an address in the layer2/BGP implementation.

I need to think about this more at a low level to see if this can play well with things like the "single active node" nature of layer 2. It is very likely trickier than I'm currently thinking.

**Comment by liuyuan10** [comment]
another issue with this is that metallb only annonce IPs from a node that runs the pod. even if you make an IP annonced from a subnet of nodes, you have to put the same node selector in your pod spec to make sure you have pod running in those nodes.  you need #613 to make it work as expected.

**Comment by anton-johansson** [comment]
@liuyuan10, very good point.

But I do guess that it would be up to the cluster admins to make sure that you're not locking down your services by not having pods on the nodes being eligible for announcing.

As you say, putting the same node selectors on the pods themselves is one way to go.

If you only take "out" one node a time and have atleast two pods up at any given time, it shouldn't be a problem either.

**Comment by ykulazhenkov** [comment]
When BGP used, we can have multiple BGP peers on each node. With "node" selector we can't fully cover use-case(https://github.com/metallb/metallb/pull/596) when one node establishes connections with multiple BGP peers which are in different network segments.

**Comment by anton-johansson** [comment]
Messing around with workarounds for this, I tried adding `nodeSelector` to my Speaker `DaemonSet`. This almost works as I want it, but it made me understand why this issue could be very tricky.

Using the `nodeSelector`, I can easily unlabel the node I want to prepare for maintenance. However, when the Speaker `Pod` is deleted, there is ~1 second of a gap before another Speaker starts announcing. I'm assuming this would be an issue even with a "real" implementation where the speakers look at the labels/annotations themselves.

How would you even solve this? Is it possible to start announcing on another speaker before the old speaker stops announcing? What happens if two announces the same address simultaneously?

**Comment by rata** [comment]
It worth noting, though, that [this use case][link] will not be solved by this generic mechanism


[link]: https://github.com/metallb/metallb/pull/596#issuecomment-662717916

**Comment by johananl** [comment]
> It worth noting, though, that [this use case](https://github.com/metallb/metallb/pull/596#issuecomment-662717916) will not be solved by this generic mechanism

Good point. I'd rather have a solution that works for all protocols if possible.

**Comment by sandromodarelli** [comment]
Hello folks,
I read the discussion starting from the @ykulazhenkov PR https://github.com/metallb/metallb/pull/596
I would share another use case : we are using metallb on a k8s cluster with nodes spreaded around the world. Each node (`peers / - node-selector`) announce the same /24 prefix (`address-pool`) to the provider AS.

All works, but there's a huge unbalance due to different routing provided from each provider. Basically 90% of the traffic from the world goes to us-west-01 (also traffic coming from EU countries)

To solve this, we need to set different `communities` during announcement (example: use Level3 community `64980:0 - announce to customers but not to EU peers` while announcing from a US zone node)

Since the annotation `metallb.universe.tf/address-pool` allows only one address pool per service, a solution can be a `node-selector` also into `bgp-advertisements` (since node selection it's available for BGP peers).

Example config:

```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
    - peer-address: 10.0.0.1
      peer-asn: 64501
      my-asn: 64500
      node-selectors:
      - match-labels:
        topology.kubernetes.io/zone: us-west-01
    - peer-address: 10.1.0.1
      peer-asn: 64502
      my-asn: 64500
      node-selectors:
      - match-labels:
        topology.kubernetes.io/zone: eu-west-01
    address-pools:
    - name: anycast
      protocol: bgp
      addresses:
      - 192.168.10.0/24
      bgp-advertisements:
      - aggregation-length: 32
        localpref: 100
        communities:
        - no-advertise
      - aggregation-length: 24
        communities:
        - telia-prepend-x3-EU-peers # adding community only during announcement from eu-west-01
        node-selectors:
        - match-labels:
          topology.kubernetes.io/zone: eu-west-01
      - aggregation-length: 24
        communities:
        - level3-no-EU-peers # adding community only during announcement from us-west-01
        node-selectors:
        - match-labels:
          topology.kubernetes.io/zone: us-west-01
    bgp-communities:
      no-advertise: 65535:65282
      level3-no-EU-peers: 64980:0
      telia-prepend-x3-EU-peers: 1299:5003
```
