### ISSUE TITLE
Announce route for nodeless endpoints

### ISSUE THREAD

**Issue by calfox** [metallb/metallb#646]
LB Services with non-pod endpoints defined are assigned an IP from the pool in Layer2 mode but this is not currently announced as they can't be linked to a particular node.

## Testing

This service will get assigned an IP but this will not be accessible outside of the cluster as no node takes ownership of ARP replies:

```
apiVersion: v1
kind: Service
metadata:
  name: test-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: test-svc
subsets:
  - addresses:
      - ip: 192.168.0.10
    ports:
      - port: 80
```

## Possible Solutions

Update the `usableNodes()` function in `speaker/layer2_controller.go` to support EndpointAddress structs that only return an IP (as above), listing all nodes as usable if none are linkable but an external IP exists:

```
func usableNodes(eps *v1.Endpoints, mList *memberlist.Memberlist) []string {
	var activeNodes map[string]bool
	if mList != nil {
		activeNodes = map[string]bool{}
		for _, n := range mList.Members() {
			activeNodes[n.Name] = true
		}
	}

	usable := map[string]bool{}
	extEp := false
	for _, subset := range eps.Subsets {
		for _, ep := range subset.Addresses {
			if ep.NodeName == nil {
				extEp = true
				continue
			}
			if activeNodes != nil {
				if _, ok := activeNodes[*ep.NodeName]; !ok {
					continue
				}
			}
			if _, ok := usable[*ep.NodeName]; !ok {
				usable[*ep.NodeName] = true
			}
		}
	}

	if extEp && len(usable) == 0 {
		usable = activeNodes
	}

	var ret []string
	for node, ok := range usable {
		if ok {
			ret = append(ret, node)
		}
	}

	return ret
}
```

A simpler solution may also be possible where all nodes are returned as usable on the first external IP, assuming node-based and external Endpoints cannot be mixed, wasn't sure on that:

```
usable := map[string]bool{}
SubsetLoop:
	for _, subset := range eps.Subsets {
		for _, ep := range subset.Addresses {
			if ep.NodeName == nil {
				usable = activeNodes
				break SubsetLoop
			}
			if activeNodes != nil {
				if _, ok := activeNodes[*ep.NodeName]; !ok {
					continue
				}
			}
			if _, ok := usable[*ep.NodeName]; !ok {
				usable[*ep.NodeName] = true
			}
		}
	}
```

I have a working PR for either I can submit but perhaps these addresses are dropped from announcement for a reason?
