### ISSUE TITLE
Any way to reduce log level/verbosity

### ISSUE THREAD

**Issue by zigmund** [metallb/metallb#655]
Hi there,

currently we're using metallb with 5 k8s clusters, ~30 nodes/metallb-speakers overall. Each speaker writes every 5-10 minutes two log recrods for every service in cluster. For example:
```
{"caller":"main.go:267","event":"startUpdate","msg":"start of service update","service":"foo-namespace/bar-service","ts":"2020-07-01T15:22:12.278029276Z"}
{"caller":"main.go:271","event":"endUpdate","msg":"end of service update","service":"foo-namespace/bar-service","ts":"2020-07-01T15:22:12.278091447Z"}
{"caller":"main.go:267","event":"startUpdate","msg":"start of service update","service":"foo-namespace/bar-service","ts":"2020-07-01T15:29:14.991299133Z"}
{"caller":"main.go:271","event":"endUpdate","msg":"end of service update","service":"foo-namespace/bar-service","ts":"2020-07-01T15:29:14.991318263Z"}
```
So we have about 1.8 million such log records every day.

Is there any config option to reduce log level to filter out such log records? Tried to dig into source code with no success.
Maybe we have some misconfig and that situation with logs is abnormal? Config from one of clusters:
```
peers:
- peer-address: x.x.x.x
  peer-asn: xxx
  my-asn: xxx
  hold-time: 15s
  node-selectors:
  - match-labels:
      metallb: "true"
address-pools:
- name: pool-foobar
  protocol: bgp
  avoid-buggy-ips: true
  addresses:
  - x.x.x.0/24
  bgp-advertisements:
  - aggregation-length: 24
```

Kubernetes v1.16.7
kube-proxy in iptables mode
Flannel v0.11.0 in host-gw mode w/o cni
MetalLB v0.9.3 BGP/L2 depending on cluster.
