### ISSUE TITLE
In layer2 mode, metallb don't find address-pools other than first one

### ISSUE THREAD

**Issue by dtourde** [metallb/metallb#669]
In layer2 mode (not tested with BGP yet), services created with other than first address-pool fails to find pool by name.

configmap.yml
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.0.11.120-10.0.11.159
    - name: core-services
      protocol: layer2
      addresses:
      - 10.0.11.100-10.0.11.119
      auto-assign: false
    - name: public
      protocol: layer2
      addresses:
        - 10.0.11.254
      auto-assign: false
```

mynginx-svc-lb.yml
```yaml
apiVersion: v1
kind: Service
metadata:
  name: mynginx-svc-lb
  namespace: mynginx
  annotations:
    metallb.universe.tf/address-pool: public
spec:
  selector:
    app: mynginx
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
```

service mynginx-svc-lb:
```shell
Name:                     mynginx-svc-lb
Namespace:                mynginx
Labels:                   <none>
Annotations:              metallb.universe.tf/address-pool: public
Selector:                 app=mynginx
Type:                     LoadBalancer
IP:                       10.43.236.132
Port:                     <unset>  80/TCP
TargetPort:               80/TCP
NodePort:                 <unset>  30077/TCP
Endpoints:                <none>
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type     Reason            Age   From                Message
  ----     ------            ----  ----                -------
  Warning  AllocationFailed  3s    metallb-controller  Failed to allocate IP for "mynginx/mynginx-svc-lb": unknown pool "public"
```

kubectl version:
```shell
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"archive", BuildDate:"2020-06-02T11:18:12Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5+k3s1", GitCommit:"58ebdb2a2ec5318ca40649eb7bd31679cb679f71", GitTreeState:"clean", BuildDate:"2020-05-06T23:43:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
k3s with '--disable servicelb --disable traefik' launch parameters.

---

When service mynginx-svc-lb is set with `metallb.universe.tf/address-pool: default` or no `annotations` at all, it works as expected.
```shell
Name:                     mynginx-svc-lb
Namespace:                mynginx
Labels:                   <none>
Annotations:              metallb.universe.tf/address-pool: default
Selector:                 app=mynginx
Type:                     LoadBalancer
IP:                       10.43.239.94
LoadBalancer Ingress:     10.0.11.120
Port:                     <unset>  80/TCP
TargetPort:               80/TCP
NodePort:                 <unset>  32583/TCP
Endpoints:                10.42.2.171:80
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type    Reason        Age   From                Message
  ----    ------        ----  ----                -------
  Normal  IPAllocated   67s   metallb-controller  Assigned IP "10.0.11.120"
  Normal  nodeAssigned  62s   metallb-speaker     announcing from node "worker-03-asus"
```

```shell
Name:                     mynginx-svc-lb
Namespace:                mynginx
Labels:                   <none>
Annotations:              Selector:  app=mynginx
Type:                     LoadBalancer
IP:                       10.43.71.225
LoadBalancer Ingress:     10.0.11.120
Port:                     <unset>  80/TCP
TargetPort:               80/TCP
NodePort:                 <unset>  31678/TCP
Endpoints:                10.42.2.170:80
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type    Reason        Age   From                Message
  ----    ------        ----  ----                -------
  Normal  IPAllocated   16s   metallb-controller  Assigned IP "10.0.11.120"
  Normal  nodeAssigned  10s   metallb-speaker     announcing from node "worker-03-asus"
```

---

Installation method for metallb:
```bash
#!/bin/env bash
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/namespace.yaml
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/metallb.yaml
# On first install only
kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"
```

**Comment by dtourde** [comment]
The configuration file was wrongly formatted.
A single IP __must__ be a valid CIDR format, like X.X.X.X/32.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.0.11.120-10.0.11.159
    - name: core-services
      protocol: layer2
      addresses:
      - 10.0.11.100-10.0.11.119
      auto-assign: false
    - name: public
      protocol: layer2
      addresses:
        - 10.0.11.254/32
      auto-assign: false
```
