### ISSUE TITLE
external-ip status is pending

### ISSUE THREAD

**Issue by qiyongxiao** [metallb/metallb#673]
I deploy the metalb found the service's external-ip status is pending. Why show this with all pod is running

### kubernetes version
```
[lsme@k8smaster1 yamls]$ kubectl get node
NAME         STATUS   ROLES    AGE   VERSION
k8smaster1   Ready    master   13d   v1.18.5
k8smaster2   Ready    master   13d   v1.18.5
k8smaster3   Ready    master   13d   v1.18.5
k8sworker1   Ready    worker   12d   v1.18.5
k8sworker2   Ready    worker   12d   v1.18.5
k8sworker3   Ready    worker   12d   v1.18.5
k8sworker4   Ready    worker   11d   v1.18.5
```

### metalb-configmap
```
[lsme@k8smaster1 yamls]$ kubectl get configmaps -n metallb-system config -o yaml
apiVersion: v1
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.10.177-192.168.10.200
kind: ConfigMap
metadata:
  name: config
  namespace: metallb-system
```

### metalb pod's status
```
[lsme@k8smaster1 yamls]$ kubectl get pod -n metallb-system
NAME                          READY   STATUS    RESTARTS   AGE
controller-57f648cb96-fm645   1/1     Running   0          20m
speaker-7k4mc                 1/1     Running   0          17m
speaker-c2jmz                 1/1     Running   0          20m
speaker-prvn6                 1/1     Running   0          20m
speaker-qjtwv                 1/1     Running   0          20m
speaker-qvj6n                 1/1     Running   0          20m
speaker-s87wf                 1/1     Running   0          20m
speaker-vrkpq                 1/1     Running   0          20m
```

### deploy test pod
```
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: crowd
spec:
  ports:
  - name: nginx
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    k8s-app: nginx
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: crowd
spec:
  selector:
    matchLabels:
      k8s-app: nginx
  template:
    metadata:
      labels:
        k8s-app: nginx
    spec:
      containers:
      - image: harbor.imagicdatatech.com/magicdata/nginx:v1.18.0
        imagePullPolicy: Always
        name: nginx
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-conf
          subPath: nginx.conf
      imagePullSecrets:
      - name: dockerpullimages
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 420
          name: nginx.conf
        name: nginx-conf
```

### show the status
```
[qiyongxiao@k8smaster1 yamls]$ kubectl apply -f nginx.conf
service/nginx unchanged
deployment.apps/nginx unchanged
[qiyongxiao@k8smaster1 yamls]$ kubectl get pod,service -n crowd
NAME                         READY   STATUS    RESTARTS   AGE
pod/nginx-5989df98c4-8wz6d   1/1     Running   0          41m

NAME            TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
service/nginx   LoadBalancer   10.104.126.15   <pending>     80:31499/TCP   35m
```

**Comment by Aoana** [comment]
Hi!

Having <pending> ExternalIP can have a number of reasons.
I try to outline a few things for starters.

**Q:** Have you checked the MetalLB controller logs around timestamp when configmap was applied?
This to ensure that the configuration have actually been put to use.
If the config is not allowed the controller will not enforce it but instead mark config as stale.
If this have happens the controller basically have no VIPs to work with and all services are stuck in <pending>.
Log messages from MetallLB controller is usually quite clear on the reason.
There are also prometheus metrics for checking this: `config_stale_bool` and `config_loaded_bool`.

Reasons can for example be:
- Syntax Errors (most common)
- Config previously ran with different IP range that have been assigned to other services.

Please also clarify how you installed MetalLB (using the 0.9.3 manifest provided or by other means?).
I ask to make sure all RBAC related parts are there.

Best Regards
Anders

**Comment by rchenzheng** [comment]
@qiyongxiao Please post the logs from the controller and speaker of any errors.

**Comment by qiyongxiao** [comment]
> @qiyongxiao Please post the logs from the controller and speaker of any errors.

this is the controller's log
```
E0727 08:00:07.476354       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.ConfigMap: Get https://10.96.0.1:443/api/v1/namespaces/metallb-system/configmaps?fieldSelector=metadata.name%3Dconfig&limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
I0727 08:00:07.477344       1 trace.go:81] Trace[939984059]: "Reflector pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98 ListAndWatch" (started: 2020-07-27 07:59:37.476415857 +0000 UTC m=+31.086364504) (total time: 30.000878594s):
Trace[939984059]: [30.000878594s] [30.000878594s] END
```

**Comment by qiyongxiao** [comment]
> @rchenzheng hi,hear is the controller log
```
E0727 08:00:07.476354       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.ConfigMap: Get https://10.96.0.1:443/api/v1/namespaces/metallb-system/configmaps?fieldSelector=metadata.name%3Dconfig&limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
I0727 08:00:07.477344       1 trace.go:81] Trace[939984059]: "Reflector pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98 ListAndWatch" (started: 2020-07-27 07:59:37.476415857 +0000 UTC m=+31.086364504) (total time: 30.000878594s):
Trace[939984059]: [30.000878594s] [30.000878594s] END
```
my cluster init cofig file is:
```
[root@k8smaster1 ~]# more kubeadm-init.yml
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: abcdef.0123456789abcdef
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
localAPIEndpoint:
  advertiseAddress: 192.168.10.175
  bindPort: 6443
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  name: k8smaster1
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
apiServer:
  timeoutForControlPlane: 4m0s
  certSANs:
    - k8smaster1
    - k8smaster2
    - k8smaster3
    - 192.168.10.173
    - 192.168.10.175
    - 192.168.10.162
    - 192.168.10.71
  extraArgs:
    authorization-mode: "Node,RBAC"
certificatesDir: /etc/kubernetes/pki
controlPlaneEndpoint: "192.168.10.71:6443"
clusterName: MagicData
controllerManager:
  extraArgs:
    "horizontal-pod-autoscaler-cpu-initialization-period": "1m0s"
    "horizontal-pod-autoscaler-downscale-stabilization": "10m0s"
    "horizontal-pod-autoscaler-sync-period": "30s"
    "leader-elect": "true"
    "leader-elect-lease-duration": "10s"
    "leader-elect-renew-deadline": "7s"
    "node-eviction-rate": "0.2"
    "pod-eviction-timeout": "20s"
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: registry.aliyuncs.com/google_containers
kubernetesVersion: v1.18.0
networking:
  serviceSubnet: 10.96.0.0/12
  podSubnet: 192.168.0.0/16
  dnsDomain: "cluster.local"
scheduler: {}
```

**Comment by Aoana** [comment]
Hi!

I verified the metallb config and it validates in my system, so we can assume that it is ok from validation perspective.

Please provide the full output of the controller logs, this can clarify if the error you spotted is only shown in startup or is persistent.
Run command `kubectl logs controller-57f648cb96-fm645 -n metallb-system` and provide the full output.
If system have been running for a long time you can install fresh, reproduce and collect logs from there to pinpoint relevant log entries. Since Controller monitors service updates the logs can be fairly large if it have been running for a long time.

Check my previous request:
> Please also clarify how you installed MetalLB (using the 0.9.3 manifest provided or by other means?). I ask to make sure all RBAC related parts are there.

If the problem shows as controller cannot register to K8s API it could be some RBAC related resource missing.
The provided steps and manifests at https://metallb.universe.tf/installation/ should provide all resources needed, so make sure you follow those steps. Request for this info is mentioned in the github issue template as well.

> E0727 08:00:07.476354       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.ConfigMap: Get https://10.96.0.1:443/api/v1/namespaces/metallb-system/configmaps?fieldSelector=metadata.name%3Dconfig&limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
I0727 08:00:07.477344       1 trace.go:81] Trace[939984059]: "Reflector pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98 ListAndWatch" (started: 2020-07-27 07:59:37.476415857 +0000 UTC m=+31.086364504) (total time: 30.000878594s):
Trace[939984059]: [30.000878594s] [30.000878594s] END

Temporary entries as you showed from log have been spotted in our sites at startup (Calico CNI plugin), but is because of a race condition when controller process is ready and when K8s have setup the network (controller is a simple process so it starts very quickly). So in our case it establishes the connection to K8s eventually (can cause ~30s delay until next try and only shows at startup). This is the reason its important you provide the full logs. 

**Sidenote:** I notice that your podSubnet `192.168.0.0/16` overlaps with the address pool range `192.168.10.177-192.168.10.200`.
There is no coordination between Metallb and K8s in this regard (as far as I know) so theoretically a VIP could be assigned to both pod and LB service. This is probably unlikely since I assume pod IPs will be picked from bottom of /16 subnet, but just wanted to point it out. 

Best Regards
Anders

**Comment by qiyongxiao** [comment]
@Aoana 
hear is all logs for controller
[alllog.txt](https://github.com/metallb/metallb/files/4981868/alllog.txt)

I followed the steps of metallb installation at https://metallb.universe.tf/installation/. while on node execute the command could get information,but in containers will be timeout :
```
[lsme@k8smaster1 ~]$ curl https://10.96.0.1:443 -k
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {

  },
  "code": 403
}
```
So, if i want to modified the podSubnet, must monidified the controller's configaration restart the controller-manager?
```
- --cluster-cidr=192.168.0.0/16   #modified the new subnet?
```

**Comment by Aoana** [comment]
Hi!

Thanks for the logs, the issue is clear to be the connection to the K8s API fails (for any resources).
As a result of this MetalLB, not being able to read ConfigMap, is currently not running with any config and obviously have no VIPs to hand out. 

You yourself pinpointed that you can reach (using curl) K8s in host netns on worker (?) but not from within the metallb controller container. **Are you able to ping the K8s API IP from within the container?** It might help to understand if the problem is routing or if it actually is a permission problem (as stated by Curl).

> So, if i want to modified the podSubnet, must monidified the controller's configaration restart the controller-manager?

Since you were using private IPs for the address pool I assume this is for lab usage (non production) environment.
In that case it might be simpler to use another private network as the address pool in MetalLB.
For example you can set the range to `10.0.0.0/24` and you will not have any risk of collision.
I am no expert on kubeadm so I cannot support if you want to change that config.

Best Regards
Anders

**Comment by qiyongxiao** [comment]
@Aoana Yes,it's able to ping k8s api within the container.
```
[lsme@k8smaster1 ~]$ kubectl get pod -n crowd
NAME                       READY   STATUS    RESTARTS   AGE
mongodb-0                  1/1     Running   0          21h
[qiyongxiao@k8smaster1 ~]$ kubectl exec -it -n crowd mongodb-0 bash
[root@mongodb-0 mongo]# ping 10.96.0.1
PING 10.96.0.1 (10.96.0.1) 56(84) bytes of data.
64 bytes from 10.96.0.1: icmp_seq=1 ttl=245 time=10.1 ms
64 bytes from 10.96.0.1: icmp_seq=2 ttl=245 time=9.15 ms
^C
```

**Comment by qiyongxiao** [comment]
@Aoana @rchenzheng I have resolve this problem by change the metallb-controller deployed to any k8smaster's. I don't know why it deployed on k8sworker will be failed to access api
```
......
          readOnlyRootFilesystem: true
      nodeName: k8smaster1
      #nodeSelector:
      #  beta.kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
............
```
