### ISSUE TITLE
Peer autodiscovery multiple node-peer support

### ISSUE THREAD

**Issue by pdf** [metallb/metallb#682]
Continuation of discussion starting https://github.com/metallb/metallb/pull/593#issuecomment-662861953

One proposal in the original discussion was to rely on some sort of magic key pattern (appending a hyphenated numeric suffix), but this offers poor readability and makes for complex parsing.

Instead, I'd propose simply making both `peer-autodiscovery.from-annotations`, and `peer-autodiscovery.from-labels` array keys. As the label/annotation keys are user-defined, any encoding scheme for those becomes an exercise for the user, based on whatever makes sense in their environment, but the configmap structure remains quite clear.

The currently proposed example:

```yaml
    peer-autodiscovery:
      # (optional) Default values to use for all discovered peers.
      defaults:
        my-asn: 100
        peer-asn: 200
        peer-address: 10.0.0.1
        peer-port: 1179
        hold-time: 180s
      # Tells MetalLB to discover BGP peers by looking for annotations on the
      # Node object. One of 'from-annotations', 'from-labels' must be specified.
      from-annotations:
        my-asn: example.com/my-asn
        peer-asn: example.com/peer-asn
        peer-address: example.com/peer-address
        peer-port: example.com/peer-port
        src-address: example.com/src-address
        hold-time: example.com/hold-time
        router-id: example.com/router-id
      # Tells MetalLB to discover BGP peers by looking for labels on the Node
      # object. One of 'from-annotations', 'from-labels' must be specified.
      from-labels:
        my-asn: example.com/my-asn
        peer-asn: example.com/peer-asn
        peer-address: example.com/peer-address
        peer-port: example.com/peer-port
        src-address: example.com/src-address
        hold-time: example.com/hold-time
        router-id: example.com/router-id
```

Becomes:

```yaml
    peer-autodiscovery:
      # (optional) Default values to use for all discovered peers.
      defaults:
        my-asn: 100
        peer-asn: 200
        peer-address: 10.0.0.1
        peer-port: 1179
        hold-time: 180s
      # Tells MetalLB to discover BGP peers by looking for annotations on the
      # Node object. One of 'from-annotations', 'from-labels' must be specified.
      from-annotations:
      - my-asn: example.com/my-asn
        peer-asn: example.com/peer-asn
        peer-address: example.com/peer-address
        peer-port: example.com/peer-port
        src-address: example.com/src-address
        hold-time: example.com/hold-time
        router-id: example.com/router-id
      # Tells MetalLB to discover BGP peers by looking for labels on the Node
      # object. One of 'from-annotations', 'from-labels' must be specified.
      from-labels:
      - my-asn: example.com/my-asn
        peer-asn: example.com/peer-asn
        peer-address: example.com/peer-address
        peer-port: example.com/peer-port
        src-address: example.com/src-address
        hold-time: example.com/hold-time
        router-id: example.com/router-id
```

Additional documentation may be provided similar to the below, to make it clear that multiple peers are supported, and whilst a possible encoding scheme for labels/annotations might be included in that documentation, I don't believe it matters much what that scheme is:

---

### Multiple node peers

Multiple node peers may be defined by either annotations or labels, simply add add an additional set of parameters under different keys, for example via `from-annotations`:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: bgp
      addresses:
      - 198.51.100.0/24
    peer-autodiscovery:
      from-annotations:
      - my-asn: peer0.example.com/my-asn
        peer-asn: peer0.example.com/peer-asn
        peer-address: peer0.example.com/peer-address
      - my-asn: peer1.example.com/my-asn
        peer-asn: peer1.example.com/peer-asn
        peer-address: peer1.example.com/peer-address
```

With the corresponding node annotations:

```yaml
apiVersion: v1
kind: Node
metadata:
  annotations:
    peer0.example.com/my-asn: 64500
    peer0.example.com/peer-asn: 64501
    peer0.example.com/peer-address: 10.0.0.3
    peer1.example.com/my-asn: 64500
    peer1.example.com/peer-asn: 64502
    peer1.example.com/peer-address: 10.0.0.4
```

The same pattern may also be applied to `from-labels`.

**Comment by deitch** [comment]
Going to comment that while this will work, you will always be stuck with the greatest common multiple. For example, if I have one node with one peer, one with two peers, one with three, then the config will have to include three peers, and metallb needs to be smart about accepting that there only is one peer on the first node, even though the config indicates we have three. 

It also means that "I said three peers in configmap but there only was one in the annotations" is not an error, nor can it be validated as one. Which is fine, but we need to be aware of it. 

It also means that if we ever have four peers, we need to update the configmap, not just the annotations.

It will work fine from a UX perspective, as long as we accept the above. 

That is why my personal preference is algorithmic, ie "auto" discovery: the config tells metallb what pattern in the annotations to use, and it finds any that match the annotations, eg "example.com/my-asn*"

But that is only a preference.

**Comment by pdf** [comment]
I had considered the case of more peers in the configmap than in annotations, and the conclusion I reached is the same as yours - this is not an error, we just accept as many peers as defined. Alternatively, a flag could be introduced to cause this to be an error, if that was at all desirable. Either way, this should really be documented. I believe that generally environments will be homogeneous though, in terms of number of peers per node, but there will always be exceptions.

The reason I lean towards this approach over a templated base is that there's a lot less magic involved, as keys are explicitly defined, and complexity is kept low on the parsing side.

**Comment by deitch** [comment]
> a lot less magic involved, as keys are explicitly defined, and complexity is kept low on the parsing side.

Those a very good reasons to consider the "defined" approach. As I said, it is a preference, and even in most of the scenarios I can dream up, I cannot honestly I expect more than 3 peers. 

Sure, let's keep it simple.

**Comment by rata** [comment]
This completely replaces the `configmap` for BGP mode. I mean, is still there, but competes with it to configure MetalLB.

I don't think using the node object to configure MetalLB is the way to go. I think CRDs might be a better way.

Also, I'd like to plan how it will interact with the configmap we currently have or have clear definitions on how that transition will be.

**Comment by russellb** [comment]
@rata Are you suggesting that #593 should not merge at all?  Otherwise, I don't see this as a very big change from what is proposed.

I agree that we should explore CRDs.

**Comment by pdf** [comment]
> Don't get me wrong, I'd like this. Not sure it makes sense to have ~all MEtalLB config in nodes objects, though. CRDs seems like a better path to explore for that, IMHO.

To be clear, the syntax here was lifted straight from #593 - all this issue proposes is a small tweak to allow more than a single peer to be configured via the the same mechanism described in that issue, by changing the peer configuration from a single entry to an array.

I agree that CRDs are surely worth investigating, however I suggest that _if_ we allow peer configuration via node annotations/labels, we should allow _multiple_ peer configuration by same.

**Comment by russellb** [comment]
> > Don't get me wrong, I'd like this. Not sure it makes sense to have ~all MEtalLB config in nodes objects, though. CRDs seems like a better path to explore for that, IMHO.
> 
> To be clear, the syntax here was lifted straight from #593 - all this issue proposes is a small tweak to allow more than a single peer to be configured via the the same mechanism described in that issue, by changing the peer configuration from a single entry to an array.
> 
> I agree that CRDs are surely worth investigating, however I suggest that _if_ we allow peer configuration via node annotations/labels, we should allow _multiple_ peer configuration by same.

+1

**Comment by johananl** [comment]
> Going to comment that while this will work, you will always be stuck with the greatest common multiple. For example, if I have one node with one peer, one with two peers, one with three, then the config will have to include three peers, and metallb needs to be smart about accepting that there only is one peer on the first node, even though the config indicates we have three.

@deitch I'm OK with stating that autodiscovery is intended for homogeneous worker pools. IMO it's 100% valid and expected that an automated mechanism needs to have a certain state in order to work properly. We can't solve *all* use cases, so we should aim at addressing the large majority of them when adding a generic feature.

That said, I *think* we may be able to address heterogeneous clusters through smart utilization of node selectors. In an extreme case, the user could select "a group of 1 nodes", although this is likely a rare use case.

> It also means that "I said three peers in configmap but there only was one in the annotations" is not an error, nor can it be validated as one. Which is fine, but we need to be aware of it.

The way I see it, failing to discover a node peer is never an error. MetalLB should simply say "I have a valid *discovery* config, however I couldn't find the annotations/labels I need so I'm not creating a peer for this node". This is fine. We do log such cases to help the user understand why a peer wasn't created, but it's not an error.

> It also means that if we ever have four peers, we need to update the configmap, not just the annotations.

True. However, I want to point out that having to change the **discovery config** is likely a much more rare case then having to change the **BGP config**. The former is relevant when your network _architecture_ changes, i.e. when you start having 3 ToR switches per rack instead of 2 in your data center. The latter is relevant when a node gets replaced, when a NIC gets reconfigured etc. So, I don't see users constantly having to change their autodiscovery config, and in any case they would have to do that much less compared to static peers.

> That is why my personal preference is algorithmic, ie "auto" discovery: the config tells metallb what pattern in the annotations to use, and it finds any that match the annotations, eg "example.com/my-asn*"

I'm reluctant to going the algorithmic route here if we can achieve a similar effect using a simpler solution. When conceiving this idea, my intention with "auto" in "autodiscovery" was "auto as in the user doesn't have to set the IP address for each node in the config map".

**Comment by johananl** [comment]
> I don't think using the node object to _~completely_ configure MetalLB is the way to go, as this proposes IIUC. I think CRDs might be a better way to change MetalLB configuration. Also, this completely replaces the `configmap` for BGP mode. I mean, is still there, but competes with it to configure MetalLB.
> 
> I'd like to plan how it will interact with the configmap we currently have or have clear definitions on how that transition will be.
> 
> Don't get me wrong, I'd like this. Not sure it makes sense to have _~all_ MEtalLB config in nodes objects, though. CRDs seems like a better path to explore for that, IMHO.
> 
> Am I missing something?

@rata and I have discussed this offline. To clarify, we don't intend for the autodiscovery feature to *replace* the ConfigMap-based static peer config but rather to complement it. While we would love to see a CRD-based solution and agree that custom resources are a better place to store config compared to `Node` objects, realistically speaking switching to CRDs isn't going to happen in a matter of a few weeks or even a few months and is rather a long term idea.

That said, we would like to see *some* solution which alleviates the need to statically configure every peer in the ConfigMap in the near future. The autodiscovery feature is my attempt at converging on such a solution. While not ideal, I am willing to work towards merging a solution based on node annotations first, and at a later stage rethink this if/when we move to CRDs down the road.

**Comment by deitch** [comment]
@johananl I don't think there is much I need to respond on your [comment here](https://github.com/metallb/metallb/issues/682#issuecomment-671960933). I am on board with everything you described.

I could write nice long comments, if you _really_ wanted. 😄

**Comment by rata** [comment]
Cool, all in the same page now!

**Comment by johananl** [comment]
One more thought which could potentially help with heterogeneous clusters and make the whole solution a big more flexible (but also a bit more complex):

Is the following too crazy?

```yaml
peer-autodiscovery:
  # Config A
  - node-selectors:
    - match-labels:
        node-pool: pool1 # Nodes in this pool have 2 ToR switches
    defaults:
      hold-time: 30s
    from-annotations:
    - my-asn: peer0.example.com/my-asn
      peer-asn: peer0.example.com/peer-asn
      peer-address: peer0.example.com/peer-address
    - my-asn: peer1.example.com/my-asn
      peer-asn: peer1.example.com/peer-asn
      peer-address: peer1.example.com/peer-address

  # Config B
  - node-selectors:
    - match-labels:
        node-pool: pool2 # Nodes in this pool have 3 ToR switches
    defaults:
      hold-time: 30s
    from-annotations:
    - my-asn: peer0.example.com/my-asn
      peer-asn: peer0.example.com/peer-asn
      peer-address: peer0.example.com/peer-address
    - my-asn: peer1.example.com/my-asn
      peer-asn: peer1.example.com/peer-asn
      peer-address: peer1.example.com/peer-address
    - my-asn: peer2.example.com/my-asn
      peer-asn: peer2.example.com/peer-asn
      peer-address: peer2.example.com/peer-address

```

It's basically taking the suggestion by @pdf a step further and allowing not only multiple peers to be discovered but also specifying multiple autodiscovery configs for different groups of nodes.
