### ISSUE TITLE
Enhancement; Controller support for the updated K8s dual-stack API (v1.20)

### ISSUE THREAD

**Issue by uablrek** [metallb/metallb#698]
### Background

Metallb controller supports the current dual-stack API in K8s where separate services for ipv4 and ipv6 must be defined, example;
```
apiVersion: v1
kind: Service
metadata:
  name: mserver-ipv6
spec:
  ipFamily: IPv6
  selector:
    app: mserver
  ports:
  - port: 5001
  type: LoadBalancer
  loadBalancerIP: "1000::"
```
The update in K8s v1.20 will allow definition of a dual-stack service, example;
```
apiVersion: v1
kind: Service
metadata:
  name: svc-preferdual-lb
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: mconnect-daemonset
  ports:
  - port: 5001
  type: LoadBalancer
```
Here `PreferDualStack` means that on a dual-stack cluster the service shall have both ipv4 and ipv6 addresses.

### Controller updates

The controller already handles pools containing both address families. When a loadBalancerIP is assigned the controller checks the family of the `clusterIP` in the service and assigns a loadBalancerIP of the same family. Since the controller never examines the `ipFamily` field (which will disappear in v1.20) the controller is **still compatible** with the new API if two single-stack services are used.

What needs to be updated is that the controller must check the new `clusterIPs` (plural) field if it exists and assign loadBalancerIPs of both families if appropriate;
```
$ kubectl get svc svc-preferdual-lb -o json | jq .spec
{
  "clusterIP": "12.0.34.137",
  "clusterIPs": [
    "12.0.34.137",
    "fd00:4000::2e7a"
  ],
  "externalTrafficPolicy": "Cluster",
  "ipFamilies": [
    "IPv4",
    "IPv6"
  ],
  "ipFamilyPolicy": "PreferDualStack",
  "ports": [
    {
      "nodePort": 32278,
      "port": 5001,
      "protocol": "TCP",
      "targetPort": 5001
    }
  ],
  "selector": {
    "app": "mconnect-daemonset"
  },
  "sessionAffinity": "None",
  "type": "LoadBalancer"
}
```

### Backward compatibility

When an updated controller (for the new API) is deployed in an old cluster the `clusterIPs` will not be set (empty or nil) and the controller shall resort to examine the `clusterIP` field.

### spec.loadBalancerIP

The `spec.loadBalancerIP` field is not (yet?) updated by the new API. For a dual-stack service the user most likely want to define load-balancer IPs for both families. A `spec.loadBalancerIPs` array is proposed; https://github.com/kubernetes/enhancements/pull/1992.

### Implementation

Implementation _can_ start right away if @khenidak development branch is used as base but is a bit difficult. It is simpler to wait until it is merged.

I plan to create a PR for this a.s.a.p and my gut feeling is that it will not be too much updates in controller code. Test is another matter, it *will* take some time. Unit-tests must use the new API and must be executed with K8s `master` of >=v1.20,

### Speakers

As when dual-stack was first supported it is best to separate controller and speaker updates. The L2 speaker may (again) work out of the box if it handles all enties in the `status.loadBalancer.ingress` array.

### References

* https://github.com/kubernetes/kubernetes/pull/91824
* https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20180612-ipv4-ipv6-dual-stack.md
