### ISSUE TITLE
0.9.3 Speaker pod consumes TONS of network io

### ISSUE THREAD

**Issue by evanrich** [metallb/metallb#700]
MetalLB: 0.9.3
K8s version: 1.18.6
network addon kube-router
iptables

I've noticed that there seems to be a TON of network I/O coming from my k8s cluster to my NAS, more than I would expect, so I started looking into some of the dashboards I have and noticed that the speaker pod for Metallb seems to be generating a TON of IO, but almost no logging.  FWIW, metalb is working just fine, but i'm seeing almost gigabit levels of traffic.:

![image](https://user-images.githubusercontent.com/518320/90556096-2f44f080-e14d-11ea-9386-ff0308b00c65.png)

speaker pod seems to be receiving between 15-30MBps, and transmitting at 105-117MBps, or gigabit levels., yet logging shows almost nothing.

Metallb config:
```
apiVersion: v1
data:
  config: |
    peers:
    - peer-address: 192.168.1.1
      peer-asn: 64512
      my-asn: 64512
      password: "eiv@QkxAS1$u&W@syy7@!m"
    address-pools:
    - name: default
      protocol: bgp
      addresses:
      - 192.168.50.0/23
      bgp-advertisements:
      - aggregation-length: 23
      avoid-buggy-ips: true
```

Looking at the last 7 days, seems this is now the new normal:
![image](https://user-images.githubusercontent.com/518320/90556333-9d89b300-e14d-11ea-8345-a24116bfc333.png)

Again, nothing wrong with metallb that i can tell, BGP works great, just wondering why it needs to generate GB level traffic.  Isn't the speaker pod just for announcing new routes?
