### ISSUE TITLE
MetalLB Layer2 mode does not consider the manually specified external IP

### ISSUE THREAD

**Issue by rahul-kr4604** [metallb/metallb#702]
**Description:** I specify the external IP to the manifest of service, the specified IP is within the range of MetalLB IP pool range specified in configMap. Though external IP appears as the specified IP but the service is not accessible.
I restarted the controller after making changes to the configMap. 

Service manifest:

```
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx
  externalIPs:
    - 192.168.200.92
  type: LoadBalancer
```

configMap manifest:

```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
       - 192.168.200.90-192.168.200.99
      auto-assign: true
```

Note: Default value of 'auto-assign' is 'true.'

The created service: 
```
[core@localhost ~]$ oc get svc
NAME    TYPE           CLUSTER-IP       EXTERNAL-IP      PORT(S)        AGE
nginx   LoadBalancer   172.30.248.240   192.168.200.92   80:30662/TCP   31s
```

The above 'nginx' service  is not accessible at external IP  "192.168.200.92".
