### ISSUE TITLE
MetalLB allows duplicate BGP peers in the configuration

### ISSUE THREAD

**Issue by johananl** [metallb/metallb#705]
MetalLB allows configuring the same BGP peer twice:

```yaml
peers:
- my-asn: 42
  peer-asn: 42
  peer-address: 1.2.3.4
- my-asn: 42
  peer-asn: 42
  peer-address: 1.2.3.4
```

Applying such a configuration to MetalLB results in a rapidly-flapping BGP session. I've discovered this while working on #593 and have a simple fix ready. I'll open a PR soon.

## Open Questions

- Which parameters exactly do we consider when determining that two peers are duplicates? To emphasize the point, two peers with a differing remote ASN would still result in two TCP sessions between the speaker and the remote peer, which is likely undesirable.
