### ISSUE TITLE
LoadBalancer service is not accessible using external IP, when endpoints (with a pod inside the cluster) is created manually. 

### ISSUE THREAD

**Issue by rahul-kr4604** [metallb/metallb#717]
I have created a LoadBalancer service and also create an endpoint. Here endpoint is associated with a pod which is available inside the cluster.
LoadBalancer gets an external IP and service also considers the manually created endpoint, but no node is selected as announcing node and service is not accessible.
The pod (which is associated with the endpoint) is available at the node where speaker pod is also available.   

**Problem:** Service is not accessible

**Expectation:** Though endpoint created manually, if it targets a valid pod, then service should be accessibe.

**Endpoint**

```
apiVersion: v1
kind: Endpoints
metadata:
  name: grafana-service
subsets:
  - addresses:
      - ip: 10.128.2.180
    ports:
      - port: 8080
```

**Service**

```
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  ports:
  - port: 80
    protocol: TCP
  type: LoadBalancer
```

**Describe service**
```
$ oc describe svc grafana-service
Name:                     grafana-service
Namespace:                metallb
Labels:                   <none>
Annotations:              Selector:  <none>
Type:                     LoadBalancer
IP:                       172.30.125.185
LoadBalancer Ingress:     192.168.200.96
Port:                     <unset>  80/TCP
TargetPort:               80/TCP
NodePort:                 <unset>  32323/TCP
Endpoints:                10.128.2.180:8080
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type    Reason       Age   From                Message
  ----    ------       ----  ----                -------
  Normal  IPAllocated  12s   metallb-controller  Assigned IP "192.168.200.96" 
```
