### ISSUE TITLE
Kubernetes 1.19.x - No Load-balancing

### ISSUE THREAD

**Issue by icpenguins** [metallb/metallb#720]
## Details
I recently upgraded to Kubernetes 1.19.0. The upgrade said it completed successfully. The configuration was working as expected before the upgrade.

I saw no traffic getting load-balanced. I then upgraded flannel to `quay.io/coreos/flannel:v0.13.0-rc2`. I rebooted the entire cluster after the upgrade. I see no load-balanced traffic for a UDP service.

I then upgraded to Kubernetes 1.19.2 and re-applied the MetalLB manifest. I have seen no change and continue to see no load-balancing and all load is going to the master node.

I found a link in Kubernetes for someone else who had an issue with the 1.19 upgrade, although it appeared to resolve itself after a reboot (link [Source IP Not Preserved](https://github.com/kubernetes/kubernetes/issues/94563))

## Environment
- Unbiquiti EdgeOs v2.0.8-hotfix.1
- Kubernetes 1.19.2
  - kube-proxy `ipvs` enabled using `strictARP:true`
- Flannel 0.13.0.-rc2

## Service Description
```bash
Name:                     syslog-forwarder
Namespace:                {redacted}
Labels:                   app={redacted}
Annotations:              metallb.universe.tf/address-pool: main-static
                          metallb.universe.tf/allow-shared-ip: set-10-2-1-15
Selector:                 app={redacted}
Type:                     LoadBalancer
IP:                       10.96.0.15
IP:                       10.2.1.15
LoadBalancer Ingress:     10.2.1.15
Port:                     unifi  5140/UDP
TargetPort:               5140/UDP
NodePort:                 unifi  31213/UDP
Endpoints:                10.1.0.190:5140,10.1.1.176:5140,10.1.2.176:5140
Port:                     edgemax  5142/UDP
TargetPort:               5142/UDP
NodePort:                 edgemax  31471/UDP
Endpoints:                10.1.0.190:5142,10.1.1.176:5142,10.1.2.176:5142
Session Affinity:         None
External Traffic Policy:  Local
HealthCheck NodePort:     32207
Events:
  Type    Reason        Age                  From                Message
  ----    ------        ----                 ----                -------
  Normal  nodeAssigned  19m (x11 over 112m)  metallb-speaker     announcing from node "k8s-work1"
  Normal  IPAllocated   19m                  metallb-controller  Assigned IP "10.2.1.15"
  Normal  nodeAssigned  18m (x9 over 108m)   metallb-speaker     announcing from node "k8s-work2"
  Normal  nodeAssigned  18m (x2 over 18m)    metallb-speaker     announcing from node "k8s-work1"
  Normal  nodeAssigned  18m (x5 over 18m)    metallb-speaker     announcing from node "k8s-master"
  Normal  nodeAssigned  18m (x2 over 18m)    metallb-speaker     announcing from node "k8s-work2"
```

**Comment by Aoana** [comment]
Since MetalLB does not perform any actual loadbalancing it would be good to clarify if this is an Metallb issue or not.

You obviously have an externalIP assigned so I assume the controller is working fine. 

Q1: where are the metallb speakers running in your cluster?

Q2: where is your udp endpoint(s) running?
Since you are using externaltrafficpolicy:Local its important.

Q3: are you running L2 or BGP?

**Comment by icpenguins** [comment]
@Aoana I appreciate the questions; here are the details. Please let me know there is anything else you need.

I understand that the router should be handling the load-balancing with ECMP. EdgeOS v1.7.0 and above is supposed to support this functionality using round-robin (link [EdgeRouter ECMP](https://help.ui.com/hc/en-us/articles/205231820-EdgeRouter-Equal-Cost-Multi-Path-ECMP-Routing)).

The externalIP works fine, traffic just holds an affinity to a pod rather than spreading out.

A1: I am running 3 nodes (k8s-(master|work1|work2) configured with the MetalLB example Daemonset ([example](https://raw.githubusercontent.com/metallb/metallb/main/manifests/metallb.yaml) so the speakers are running on all nodes.

A2: My UDP endpoints are also configured as a Daemonset and run on all nodes.

```bash
Name:           syslog-forwarder
Selector:       app={redacted}
Node-Selector:  <none>
Labels:         app={redacted}
Annotations:    deprecated.daemonset.template.generation: 14
Desired Number of Nodes Scheduled: 3
Current Number of Nodes Scheduled: 3
Number of Nodes Scheduled with Up-to-date Pods: 3
Number of Nodes Scheduled with Available Pods: 3
Number of Nodes Misscheduled: 0
Pods Status:  3 Running / 0 Waiting / 0 Succeeded / 0 Failed
```

A3: My IP address poll is configured as BGP

### MetalLB config

```yaml
    - name: main
      protocol: bgp
      addresses:
      - 10.2.1.0/24
      auto-assign: false
      bgp-advertisements:
      - aggregation-length: 32
        localpref: 100
```
## Router Details

### BGP Summary

```bash
BGP router identifier 10.0.0.1, local AS number 64512
BGP table version is 155
1 BGP AS-PATH entries
0 BGP community entries
3  Configured ebgp ECMP multipath: Currently set at 3
3  Configured ibgp ECMP multipath: Currently set at 3

Neighbor                 V   AS   MsgRcv    MsgSen TblVer   InQ   OutQ    Up/Down   State/PfxRcd
10.0.0.10                4 64512 38069      38028     155      0      0  01:02:03               2
10.0.0.11                4 64512 38049      38022     155      0      0  01:01:49               5
10.0.0.12                4 64512 38059      38029     155      0      0  01:01:29               4

Total number of neighbors 3

Total number of Established sessions 3
```

### BGP Route

```bash
...@ER-4:~$ show ip route bgp
IP Route Table for VRF "default"
B    *> 10.2.0.2/32 [200/0] via 10.0.0.12, bond0.1000, 00:13:13
     *>             [200/0] via 10.0.0.11, bond0.1000, 00:13:13
B    *> 10.2.1.2/32 [200/0] via 10.0.0.12, bond0.1000, 00:13:13
     *>             [200/0] via 10.0.0.11, bond0.1000, 00:13:13
B    *> 10.2.1.3/32 [200/0] via 10.0.0.11, bond0.1000, 01:15:07
B    *> 10.2.1.4/32 [200/0] via 10.0.0.12, bond0.1000, 00:13:13
     *>             [200/0] via 10.0.0.11, bond0.1000, 00:13:13
     *>             [200/0] via 10.0.0.10, bond0.1000, 00:13:13
B    *> 10.2.1.15/32 [200/0] via 10.0.0.12, bond0.1000, 00:13:13
     *>              [200/0] via 10.0.0.11, bond0.1000, 00:13:13
     *>              [200/0] via 10.0.0.10, bond0.1000, 00:13:13
```

**Comment by Aoana** [comment]
Q4: Can you supply full configmap used? This seems to be jut outlining the addresspool and not the configured BGP peers. 

VIP 10.2.1.15 has gotten announcements from 3 neighbors so metallb has done what i can..
Are you sure you have BGP multipath enabled?

**Comment by icpenguins** [comment]
@Aoana Please find the full configmap below. I have validated that BGP multipath is enabled as seen in the above `BGP Summary` output. I also agree that MetalLB couldn't control the traffic coming from the load balancer. However, when I have configured another EdgeOS router as a BGP peer in the past, I would not see the question marks `?` next to the BGP `Path` section.

```bash
....@ER-4:~$ show ip bgp
BGP table version is 167, local router ID is 10.0.0.1
Status codes: s suppressed, d damped, h history, * valid, > best, i - internal, l - labeled
              S Stale
Origin codes: i - IGP, e - EGP, ? - incomplete

    Network          Next Hop            Metric    LocPrf       Weight Path
*>i 10.2.0.2/32      10.0.0.11            0        100          0        ?
* i                  10.0.0.12            0        100          0        ?
*>i 10.2.1.2/32      10.0.0.11            0        100          0        ?
* i                  10.0.0.12            0        100          0        ?
*>i 10.2.1.3/32      10.0.0.11            0        100          0        ?
*>i 10.2.1.4/32      10.0.0.10            0        100          0        ?
* i                  10.0.0.12            0        100          0        ?
* i                  10.0.0.11            0        100          0        ?
*>i 10.2.1.15/32     10.0.0.10            0        100          0        ?
* i                  10.0.0.12            0        100          0        ?
* i                  10.0.0.11            0        100          0        ?
*>  192.168.1.0      0.0.0.0                       100          32768    i
*   192.168.5.0      0.0.0.0                       100          32768    i
*   192.168.150.0    0.0.0.0                       100          32768    i
*   192.168.200.0/29 0.0.0.0                       100          32768    i
```

### Configmap
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
    - # The target IP address for the BGP session.
      peer-address: 10.0.0.1
      peer-asn: 64512
      my-asn: 64512
      hold-time: 120s
      node-selectors:
      - # Match by label=value
        # Match by 'key OP values' expressions
        match-expressions:
        - key: kubernetes.io/arch
          operator: In
          values: [amd64, arm]
    address-pools:
    - name: dmz
      protocol: bgp
      addresses:
      - 10.2.0.0/24
      auto-assign: false
      bgp-advertisements:
      - aggregation-length: 32
        localpref: 100
    - name: main
      protocol: bgp
      addresses:
      - 10.2.1.0/24
      auto-assign: false
      bgp-advertisements:
      - aggregation-length: 32
        localpref: 100
    bgp-communities:
      no-export: 65535:65281
```
