### ISSUE TITLE
Minimum CPU/Memory resource requirement for MetalLB deployment.

### ISSUE THREAD

**Issue by harii9** [metallb/metallb#729]
Dear Team,

We want to know the minimum CPU and Memory requirement of MetalLB deployed on the Openshift cluster. From the MetalLB configuration file it looks like the below limit is set for the controller and speaker pod:

```
resources:
    limits:
      cpu: 100m
      memory: 100Mi
```
