### ISSUE TITLE
Support for dual-stack services in the speaker

### ISSUE THREAD

**Issue by uablrek** [metallb/metallb#731]
In K8s v1.20.0 it will be possible to define dual-stack services (see also https://github.com/metallb/metallb/issues/698);
```
apiVersion: v1
kind: Service
metadata:
  name: svc-preferdual-lb
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: mconnect-daemonset
  ports:
  - port: 5001
  type: LoadBalancer
```
The `controller` will assign two load-balancer addresses (from the same pool) when https://github.com/metallb/metallb/pull/727 is merged;
```
$ kubectl get svc svc-preferdual-lb -o json | jq .status
{
  "loadBalancer": {
    "ingress": [
      {
        "ip": "10.0.0.2"
      },
      {
        "ip": "1000::1"
      }
    ]
  }
}
```
Currently the speaker only handles one address and must be extended to handle two.

### Implementation

Implementation can start right away! No need to wait for K8s v1.20.0 or https://github.com/metallb/metallb/pull/727.

Ipv6 is supported for L2 only so BGP must wait for now. Most updates are probably in code common for L2 and BGP.

### Backward compatibility

Single-stack addresses are handles like before and there is no API update for `status.loadBalancer.ingress` so backward compatibility should not be a problem.

### Testing

E2e testing requires a dual-stack environment. The function is however not super complex so perhaps manual testing is sufficient from start.
