### ISSUE TITLE
metallb.universe.tf/allow-shared-ip

### ISSUE THREAD

**Issue by orenzp** [metallb/metallb#788]
Hi
I setup MetalLB for my RPI 4 cluster, I'm running metallb/controller:v0.9.5 using the manifest installation from the MetalLB installation page.
I'm trying to set my pihole to use metallb so i can run both UDP and TCP services on the same IP Address, But when the 2 services are created only one get the shared IP and the other is stuck at pending with this error:
failed to allocate IP for "pihole/pihole-tcp": can't change sharing key for "pihole/pihole-tcp", address also in use by pihole/pihole-udp
Does anyone know what cloud be the issue? from what I understand it supposes to work without any issues.

**Comment by johananl** [comment]
Hi there. If you could share your config it would make it much easier to help you :slightly_smiling_face:

**Comment by johananl** [comment]
FWIW I am able to share an IP using the following:

```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 172.17.0.250-172.17.0.252
```

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard
  labels:
    app: kuard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuard
  template:
    metadata:
      labels:
        app: kuard
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:blue
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kuard
  annotations:
    metallb.universe.tf/allow-shared-ip: foo
spec:
  selector:
    app: kuard
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: kuard-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: foo
spec:
  selector:
    app: kuard
  ports:
  - protocol: UDP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
```

Result:

```
kubectl get svc | grep kuard
kuard        LoadBalancer   10.96.68.41     172.17.0.250   8080:32234/TCP   7m25s
kuard-udp    LoadBalancer   10.96.228.227   172.17.0.250   8080:30974/UDP   7m25s
```

**Comment by orenzp** [comment]
Hi @johananl 
Thanks for the replay, here is my config. Looks exactly like yours.

MetalLB Config File:
```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.100.102.2-10.100.102.9
```


Service resources for UDP and TCP:
```
apiVersion: v1
kind: Service
metadata:
  name: pihole-tcp
  labels:
    app: pihole
    chart: pihole-1.7.20
    release: pihole
    heritage: Helm
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: pihole
spec:
  type: LoadBalancer
  loadBalancerIP: 10.100.102.4
  externalTrafficPolicy:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
    - port: 53
      targetPort: dns
      protocol: TCP
      name: dns
  selector:
    app: pihole
    release: pihole
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-udp
  labels:
    app: pihole
    chart: pihole-1.7.20
    release: pihole
    heritage: Helm
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: pihole
spec:
  type: LoadBalancer
  loadBalancerIP: 10.100.102.4
  externalTrafficPolicy: Local
  ports:
    - port: 53
      targetPort: dns-udp
      protocol: UDP
      name: dns-udp
    - port: 67
      targetPort: client-udp
      protocol: UDP
      name: client-udp
  selector:
    app: pihole
    release: pihole
```

**Comment by champtar** [comment]
`externalTrafficPolicy` is empty for `pihole-tcp`

**Comment by orenzp** [comment]
> `externalTrafficPolicy` is empty for `pihole-tcp`

No I just feel stupid. Thanks @champtar that did the trick.
I read about `externalTrafficPolicy:` but didn't think it related to this situation.

**Comment by champtar** [comment]
I would not have bet that it was the issue either, but that was the only thing that felt wrong.

**Comment by craigcabrey** [comment]
sorry for resurrecting this old thread, but I've hit this issue as well. from what I can tell, my configuration looks fine:

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    metallb.universe.tf/allow-shared-ip: ingress-nginx-v6
  name: ingress-nginx-controller-v6
  namespace: ingress-nginx
spec:
  type: LoadBalancer
  loadBalancerIP: [snip]::100
  externalTrafficPolicy: Cluster
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv6
  ports:
    - appProtocol: http
      name: http
      port: 80
      protocol: TCP
      targetPort: http
    - appProtocol: https
      name: https
      port: 443
      protocol: TCP
      targetPort: https
    - name: 25565-tcp
      port: 25565
      protocol: TCP
      targetPort: 25565-tcp
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    metallb.universe.tf/allow-shared-ip: ingress-nginx-v6
  name: ingress-nginx-controller-udp-v6
  namespace: ingress-nginx
spec:
  type: LoadBalancer
  loadBalancerIP: [snip]::100
  externalTrafficPolicy: Cluster
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv6
  ports:
    - name: 27015-udp
      port: 27015
      protocol: UDP
      targetPort: 27015-udp
    - name: 27016-udp
      port: 27016
      protocol: UDP
      targetPort: 27016-udp
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
```

but I get the mysterious "can't change sharing key" error:
```
$ kubectl describe svc ingress-nginx-controller-udp-v6 -n ingress-nginx
Name:                     ingress-nginx-controller-udp-v6
Namespace:                ingress-nginx
Labels:                   app.kubernetes.io/component=controller
                          app.kubernetes.io/instance=ingress-nginx
                          app.kubernetes.io/name=ingress-nginx
                          app.kubernetes.io/part-of=ingress-nginx
                          metallb.universe.tf/allow-shared-ip=ingress-nginx-v6
Annotations:              <none>
Selector:                 app.kubernetes.io/component=controller,app.kubernetes.io/instance=ingress-nginx,app.kubernetes.io/name=ingress-nginx
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv6
IP:                       2001:cafe:42:1::749
IPs:                      2001:cafe:42:1::749
IP:                       2605:a601:aa28:f904::100
Port:                     27015-udp  27015/UDP
TargetPort:               27015-udp/UDP
NodePort:                 27015-udp  32414/UDP
Endpoints:                <none>
Port:                     27016-udp  27016/UDP
TargetPort:               27016-udp/UDP
NodePort:                 27016-udp  31701/UDP
Endpoints:                <none>
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type     Reason            Age   From                Message
  ----     ------            ----  ----                -------
  Warning  AllocationFailed  11m   metallb-controller  Failed to allocate IP for "ingress-nginx/ingress-nginx-controller-udp-v6": can't change sharing key for "ingress-nginx/ingress-nginx-controller-udp-v6", address also in use by ingress-nginx/ingress-nginx-controller-v6
```

any insights? thanks!
