### ISSUE TITLE
Metallb not assign an ipv6 adress on Kubernetes Service v1.20.2 arm64

### ISSUE THREAD

**Issue by Trackhe** [metallb/metallb#799]
after update from 1.19 to 1.20
i test it with
```
kind: Service
apiVersion: v1
metadata:
  name: test
  namespace: default
  annotations:
    metallb.universe.tf/allow-shared-ip: test
  labels:
    k8s-app: testnginx
spec:
  ipFamilyPolicy: SingleStack
  ports:
    - name: test1
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    k8s-app: testnginx
  type: LoadBalancer
  loadBalancerIP: fd11:1111:1111:1111::1
  ipFamily: IPv6
```
if i define a lbip the service is not going to deploy.
if i dont define an lbip the service become an ipv4 adress.
if i change ipFamilyPolicy dualstack and dont define an lbip i become an ipv4 and:
```
spec:
  ports:
    - name: test1
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32458
  selector:
    k8s-app: testnginx
  clusterIP: 10.200.75.37
  clusterIPs:
    - 10.200.75.37
    - 'fd00:2::1:0:0:4b1d'
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
    - IPv6
  ipFamilyPolicy: PreferDualStack
status:
  loadBalancer:
    ingress:
      - ip: 192.168.178.201
```
i use metallb v0.9.5 with
```
kubectl get configmap kube-proxy -n kube-system -o yaml | \
sed -e "s/strictARP: false/strictARP: true/" | \
sed -e "s/mode: ""/mode: "ipvs"/" | \
kubectl apply -f - -n kube-system 
```
and calico 3.14 with activated for dualstack.

config:
```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.178.200-192.168.178.254
      - fd11:1111:1111:1111::/108
```

I used my step by step guide.
https://github.com/Trackhe/Raspberry64bitKubernetesServerDualstack
