### ISSUE TITLE
helm chart won't respect prometheus port

### ISSUE THREAD

**Issue by skoef** [metallb/metallb#843]
I wanted to try the newly added helm chart from #658 and ran into an issue with the readinessProbe on both the controller and speaker pods. The readinessProbe checks port `metrics` which is hardcoded to `7472`. The pods start without `--port=7472` so will listen on port 80 by default and the pods never reach ready state.

I tried this with a checkout of 92d6860a67695a176f5d7c1762d188b5d8144883 (0.10.0 pre-release) on kubernetes 1.18.

I was asked to mention @gclawes on Slack.

**Comment by champtar** [comment]
You need to force the images to main to test the charts because right now the chart point to 0.9.6 which doesn't include #826
```
controller:
  image:
    tag: main
    pullPolicy: Always

speaker:
  image:
    tag: main
    pullPolicy: Always
```

We could still improve the chart to make the prometheus port configurable
