### ISSUE TITLE
BGP routes keeps refreshing

### ISSUE THREAD

**Issue by gallart** [metallb/metallb#880]
* Version of MetalLB : 0.10.0
* Kubernetes env : k3s multi-nodes

I have deployed a simple Metallb configuration on a lightweight 3-nodes K3S Cluster with a BGP configuration :

```
apiVersion: v1
kind: ConfigMap
metadata:
    namespace: metallb-system
    name: config
data:
  config: |
    peers:
    - peer-address: x.x.x.x
      peer-asn: xxxxxxxx
      my-asn: 65001
    address-pools:
    - name: default
      protocol: bgp
      addresses:
      - 1.2.3.4/32
```

BGP Session established and stable.

The problem is that MetalLb keeps pushing/unpushing the route every 3 seconds :

```
B>* 1.2.3.4/32 [20/0] via 10.10.50.14, eth1, weight 1, 00:00:01
```

As you can see, from the router, the route-age is never stable.
The consequence is that the public-IP is "unreachable" randomly.

On the metallb pods side, I have this looping :

```
{"caller":"main.go:49","event":"startUpdate","msg":"start of service update","service":"ingress-nginx/ingress-nginx-controller","ts":"2021-06-10T08:04:55.926403769Z"}
{"caller":"service.go:114","event":"ipAllocated","ip":"1.2.3.4","msg":"IP address assigned by controller","service":"ingress-nginx/ingress-nginx-controller","ts":"2021-06-10T08:04:55.926569663Z"}
{"caller":"main.go:88","event":"serviceUpdated","msg":"updated service object","service":"ingress-nginx/ingress-nginx-controller","ts":"2021-06-10T08:04:55.936011529Z"}
{"caller":"main.go:90","event":"endUpdate","msg":"end of service update","service":"ingress-nginx/ingress-nginx-controller","ts":"2021-06-10T08:04:55.93607857Z"}
{"caller":"main.go:49","event":"startUpdate","msg":"start of service update","service":"ingress-nginx/ingress-nginx-controller","ts":"2021-06-10T08:04:55.936951983Z"}
{"caller":"main.go:75","event":"noChange","msg":"service converged, no change","service":"ingress-nginx/ingress-nginx-controller","ts":"2021-06-10T08:04:55.937435869Z"}
{"caller":"main.go:76","event":"endUpdate","msg":"end of service update","service":"ingress-nginx/ingress-nginx-controller","ts":"2021-06-10T08:04:55.93747686Z"}
```

Nginx-ingress is the only service requiring an external IP on the cluster.

Thanks
