### ISSUE TITLE
Getting flooded by logs

### ISSUE THREAD

**Issue by mnorrsken** [metallb/metallb#899]
Getting flooded by these logs, several lines per second, getting about 800 per minute. Reverting to 0.9.6 reduces logs to the normal ~2 lines per minute. Its not just the traefik service its all services spamming constantly.
```
Jul 1, 2021 @ 16:22:25.193	alderaan	{"caller":"main.go:199","event":"startUpdate","msg":"start of service update","service":"kube-system/traefik","ts":"2021-07-01T14:22:25.193490733Z"}

Jul 1, 2021 @ 16:22:25.193	alderaan	{"caller":"main.go:256","event":"endUpdate","msg":"end of service update","service":"kube-system/traefik","ts":"2021-07-01T14:22:25.193545362Z"}
```

MetalLB: 0.10.2.  - reverting to 0.9.6 fixed the issue
Kubernetes: v1.20.8+k3s1
Network addons: Flannel, Traefik v2
Kube-proxy in iptables mode i think

```
        config: |
          address-pools:
          - name: default
            protocol: layer2
            addresses:
            - 192.168.1.193-192.168.1.224
          - name: manual
            protocol: layer2
            addresses:
            - 192.168.1.161-192.168.1.190
            - 192.168.1.225-192.168.1.229
            auto-assign: false
```
