### ISSUE TITLE
Superfluous "serviceAnnounced" events in logs

### ISSUE THREAD

**Issue by johananl** [metallb/metallb#901]
Lately I've noticed I'm getting the following event in the logs as part of the "normal" reconcile loop, i.e. when there are no changes to the service:

```
{"caller":"main.go:287","event":"serviceAnnounced","ip":"147.75.101.87","msg":"service has IP, announcing","pool":"default","protocol":"bgp","service":"httpbin/httpbin","ts":"2021-07-02T16:30:22.476711892Z"}
```

I am pretty sure we don't want to log this unless there was a change to the service's status as far as the speaker is concerned. We should look into what change has introduced this.

Reproduced with speaker at `v0.10.2` with the following config:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
    - peer-address: 10.80.51.140
      peer-asn: 65530
      my-asn: 65000
      node-selectors:
      - match-labels:
          kubernetes.io/hostname: johannes-test1-pool-1-worker-0
    - peer-address: 10.80.51.142
      peer-asn: 65530
      my-asn: 65000
      node-selectors:
      - match-labels:
          kubernetes.io/hostname: johannes-test1-pool-1-worker-1
    address-pools:
    - name: default
      protocol: bgp
      addresses:
      - 147.75.32.61/32
```
