### ISSUE TITLE
Support for metallb.universe.tf/address-pool annotation for Ingress object types

### ISSUE THREAD

**Issue by damonjbeasley** [metallb/metallb#908]
Currently the metallb.universe.tf/address-pool annotation is only supported for Service object types. It would be beneficial to add this annotation to Ingress object types as well. Something like the following:

```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: internal
  annotations:
    metallb.universe.tf/address-pool: private
spec:
  rules:
    - host: internal.example.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: internal-service-name
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: internet-facing
  annotations:
    metallb.universe.tf/address-pool: public
spec:
  rules:
    - host: example.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-name
                port:
                  number: 8080
```
