### ISSUE TITLE
MetalLB not respecting service ExternalIPs

### ISSUE THREAD

**Issue by aaronspruit** [metallb/metallb#924]
After a node update/restart last night some of the metalLB externalIPs are no longer properly listening.  After a lot of digging in and attempting to see what was going on, it appears as if it's only listening on the next available IP in the defined range instead of the one defined in the Service definition.

I am unable to access port 53 on the 170 IP address (doing an nslookup), but I am on the 161 address.  If I remove the TCP service and just have the UDP service, the results are the same.  Interestingly, other services that have an ExternalIP address defined continue to work fine for both the automatically assigned IP and the service-defined ExternalIP.  It's as thought something is "stuck" with this specific service.  I have tried to delete and remove the services multiple times, restart the nodes, etc. to no avail.  The controller and the pod w/ the service are on the same node, and the speaker is actively announcing (looks similar to functioning LBs).

- Version of MetalLB: 0.10.2 via manifest files (not helm)
- Version of K8s: microk8s v1.21.1
- No additional network addons

Service definition:
```
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns-udp-service
  namespace: pihole
spec:
  type: LoadBalancer
  externalIPs:
    - "192.168.0.170"
  externalTrafficPolicy: Local
  selector:
    app: pihole
  ports:
    - name: dns-udp
      protocol: UDP
      port: 53
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-service
  namespace: pihole
spec:
  selector:
    app: pihole
  ports:
    - name: http
      protocol: TCP
      port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns-tcp-service
  namespace: pihole
spec:
  type: LoadBalancer
  externalIPs:
    - "192.168.0.170"
  externalTrafficPolicy: Local
  selector:
    app: pihole
  ports:
    - name: dns
      protocol: TCP
      port: 53
```
Services in kubectl
```
NAME                     TYPE           CLUSTER-IP       EXTERNAL-IP                   PORT(S)        AGE
pihole-service           ClusterIP      10.152.183.227   <none>                        80/TCP         171d
pihole-dns-tcp-service   LoadBalancer   10.152.183.51    192.168.0.162,192.168.0.170   53:30738/TCP   2m40s
pihole-dns-udp-service   LoadBalancer   10.152.183.85    192.168.0.161,192.168.0.170   53:32125/UDP   23m
```
Announce assignment in controller
```
controller
[Jul 21, 2021 3:58:24 PM GMT-7]
{"caller":"main.go:49","event":"startUpdate","msg":"start of service update","service":"pihole/pihole-dns-udp-service","ts":"2021-07-21T22:58:24.247889336Z"}
controller
[Jul 21, 2021 3:58:24 PM GMT-7]
{"caller":"service.go:114","event":"ipAllocated","ip":"192.168.0.161","msg":"IP address assigned by controller","service":"pihole/pihole-dns-udp-service","ts":"2021-07-21T22:58:24.248158713Z"}
controller
[Jul 21, 2021 3:58:24 PM GMT-7]
{"caller":"main.go:88","event":"serviceUpdated","msg":"updated service object","service":"pihole/pihole-dns-udp-service","ts":"2021-07-21T22:58:24.281644049Z"}
controller
[Jul 21, 2021 3:58:24 PM GMT-7]
{"caller":"main.go:90","event":"endUpdate","msg":"end of service update","service":"pihole/pihole-dns-udp-service","ts":"2021-07-21T22:58:24.281837416Z"}
controller
[Jul 21, 2021 3:58:24 PM GMT-7]
{"caller":"main.go:49","event":"startUpdate","msg":"start of service update","service":"pihole/pihole-dns-udp-service","ts":"2021-07-21T22:58:24.283661902Z"}
controller
[Jul 21, 2021 3:58:24 PM GMT-7]
{"caller":"main.go:75","event":"noChange","msg":"service converged, no change","service":"pihole/pihole-dns-udp-service","ts":"2021-07-21T22:58:24.283890311Z"}
controller
[Jul 21, 2021 3:58:24 PM GMT-7]
{"caller":"main.go:76","event":"endUpdate","msg":"end of service update","service":"pihole/pihole-dns-udp-service","ts":"2021-07-21T22:58:24.283908748Z"}
controller
[Jul 21, 2021 4:19:27 PM GMT-7]
{"caller":"main.go:49","event":"startUpdate","msg":"start of service update","service":"pihole/pihole-dns-tcp-service","ts":"2021-07-21T23:19:27.985210222Z"}
controller
[Jul 21, 2021 4:19:27 PM GMT-7]
{"caller":"service.go:114","event":"ipAllocated","ip":"192.168.0.162","msg":"IP address assigned by controller","service":"pihole/pihole-dns-tcp-service","ts":"2021-07-21T23:19:27.985528665Z"}
controller
[Jul 21, 2021 4:19:28 PM GMT-7]
{"caller":"main.go:88","event":"serviceUpdated","msg":"updated service object","service":"pihole/pihole-dns-tcp-service","ts":"2021-07-21T23:19:28.012371676Z"}
controller
[Jul 21, 2021 4:19:28 PM GMT-7]
{"caller":"main.go:90","event":"endUpdate","msg":"end of service update","service":"pihole/pihole-dns-tcp-service","ts":"2021-07-21T23:19:28.012460531Z"}
controller
[Jul 21, 2021 4:19:28 PM GMT-7]
{"caller":"main.go:49","event":"startUpdate","msg":"start of service update","service":"pihole/pihole-dns-tcp-service","ts":"2021-07-21T23:19:28.025825011Z"}
controller
[Jul 21, 2021 4:19:28 PM GMT-7]
{"caller":"main.go:75","event":"noChange","msg":"service converged, no change","service":"pihole/pihole-dns-tcp-service","ts":"2021-07-21T23:19:28.026194931Z"}
controller
[Jul 21, 2021 4:19:28 PM GMT-7]
{"caller":"main.go:76","event":"endUpdate","msg":"end of service update","service":"pihole/pihole-dns-tcp-service","ts":"2021-07-21T23:19:28.026728457Z"}
```
Configmap
```
address-pools:
- name: default
  protocol: layer2
  addresses:
  - 192.168.0.160-192.168.0.199
```
