### ISSUE TITLE
Services with same sharing key and pod selector not co-located

### ISSUE THREAD

**Issue by starcraft66** [metallb/metallb#940]
Hey, I'm having a problem with IP address co-location using the `metallb.universe.tf/allow-shared-ip`  annotation. My services all have the same sharing key, they define different ports, and they all point to the exact same pod selector. They use `externalTrafficPolicy: Local` because the source ip of traffic must be preserved but this should be okay according to the docs since the pod selectors are identical.

My config:
```
apiVersion: v1
kind: Service
metadata:
  name: traefik-v4-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: "traefik-v4"
spec:
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: https
    port: 443
    targetPort: websecureudp
    protocol: UDP
  selector:
    app.kubernetes.io/name: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-v6-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: "traefik-v6"
spec:
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv6
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: https
    port: 443
    targetPort: websecureudp
    protocol: UDP
  selector:
    app.kubernetes.io/name: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-v4
  annotations:
    metallb.universe.tf/allow-shared-ip: "traefik-v4"
spec:
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    targetPort: web
    protocol: TCP
  - name: https
    port: 443
    targetPort: websecure
    protocol: TCP
  selector:
    app.kubernetes.io/name: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-v6
  annotations:
    metallb.universe.tf/allow-shared-ip: "traefik-v6"
spec:
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv6
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    targetPort: web
    protocol: TCP
  - name: https
    port: 443
    targetPort: websecure
    protocol: TCP
  selector:
    app.kubernetes.io/name: traefik
```

Output of `k get svc -n traefik`
```
NAME                   TYPE           CLUSTER-IP                    EXTERNAL-IP                PORT(S)                      AGE
traefik                LoadBalancer   10.233.5.133                  10.224.0.2                 80:30466/TCP,443:30918/TCP   191d
traefik-dashboard      ClusterIP      2607:fa48:6ed8:8a54:2::1f29   <none>                     80/TCP                       190d
traefik-forward-auth   ClusterIP      2607:fa48:6ed8:8a54:2::fb3e   <none>                     80/TCP                       190d
traefik-prometheus     ClusterIP      2607:fa48:6ed8:8a54:2::79a    <none>                     9100/TCP                     190d
traefik-v4             LoadBalancer   10.233.48.97                  10.224.0.3                 80:31934/TCP,443:32128/TCP   190d
traefik-v4-udp         LoadBalancer   10.233.35.60                  10.224.0.1                 443:31739/UDP                8m24s
traefik-v6             LoadBalancer   2607:fa48:6ed8:8a54:2::8d77   2607:fa48:6ed8:8a54:3::1   80:32078/TCP,443:32003/TCP   190d
traefik-v6-udp         LoadBalancer   2607:fa48:6ed8:8a54:2::a289   2607:fa48:6ed8:8a54:3::    443:30329/UDP                8m24s
```

As you can see, traefik-v4 and traefik-v4-udp should be colocated but they got assigned different IP addresses. Same with the traefik-v6 and traefik-v6-udp services.

Env:
- k8s 1.20.2
- metallb 0.10.2
