### ISSUE TITLE
Shared Layer 2 IPs should not be announced by multiple nodes

### ISSUE THREAD

**Issue by wzrdtales** [metallb/metallb#968]
Reopen of #315 

# What is happening?

Multiple nodes try to claim the IP, which results in an unstable connection.

# Why is this happening?

The layer 2 ip was shared between two services in two different namespaces. One is pointing to a specific port, the other one is pointing to the ingress. To reproduce just create two namespaces with two different services and share the ip.

# What should happen?

The shared ip should be recognized at that by the speaker in reliable fashion and not being used duplicated.

**Comment by fedepaol** [comment]
Hi @wzrdtales , just to understand better:
When you say that the ip is shared between the services, are you setting the same `loadBalancerIP` manually or are you using the `metallb.universe.tf/allow-shared-ip` annotation?

Would you mind sharing the services / pools definitions to avoid missing details in translation?
Thanks!

**Comment by wzrdtales** [comment]
both, since both have to be defined

**Comment by wzrdtales** [comment]
```yaml
spec:
  clusterIP: 10.43.25.93
  clusterIPs:
  - 10.43.25.93
  externalTrafficPolicy: Cluster
  loadBalancerIP: anonymized
  ports:
  - name: ssh
    nodePort: 30226
    port: 22
    protocol: TCP
    targetPort: 2222
  selector:
    app: gitlab-shell
    release: gitlab-prod
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 60
  type: LoadBalancer
```

```yaml
spec:
  clusterIP: 10.43.232.168
  clusterIPs:
  - 10.43.232.168
  externalTrafficPolicy: Cluster
  loadBalancerIP: anonymized
  ports:
  - name: http
    nodePort: 31453
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 32283
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: ingress-nginx
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 60
  type: LoadBalancer
```


This is the config applied
