### ISSUE TITLE
Endless stream of nodeAssigned events after updating to MetalLB 0.10

### ISSUE THREAD

**Issue by mologie** [metallb/metallb#978]
Hi, I am using MetalLB under Talos (0.11) with K8s 1.21. The cluster has been running on MetalLB 0.9.6 for months w/o issues. I have just attempted to update to 0.10 but found that it misbehaves as explained in this ticket.

The problem:

In 0.9.6 I would see a single "nodeAssigned" event per LB; in 0.10.2 I see a flood of them, roughly one per LB every 2 seconds, which generates hundreds of events every minute.

LBs themselves continue to work, but clearly something is not right.

My configuration/environment:

* MetalLB 0.9.6 (working) and 0.10.2 (nodeAssigned spam)
* Installation method: by manifest
* L2 mode
* kube-proxy in iptables mode (Talos default)
* Talos 0.11.5 with K8s 1.21.3 under Linux 5.10.52
* Calico CNI 3.19.0

My config:

```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
      - name: ingress-public
        protocol: layer2
        addresses:
          - 10.99.99.122/32
        auto-assign: false
      - name: ingress-foo
        protocol: layer2
        addresses:
          - 10.99.99.123/32
        auto-assign: false
      - name: ingress-internal
        protocol: layer2
        addresses:
          - 10.4.99.0/32
        auto-assign: false
      - name: default
        protocol: layer2
        addresses:
          - 10.4.99.1-10.4.99.31
```

Special cluster settings: The `MixedProtocolLBService=true` api-server feature gate is set, and one LB on the cluster serves both TCP and UDP. The issue appears to be unrelated to this setting however.

Instead of updating I have also tried to delete the metallb-system namespace and recreate it from scratch with no change.

If you believe that this issue is not due to a configuration/cluster at my end I would appreciate your input. I can dedicate some time to diagnosing and fixing this issue w/ code contributions if needed.
