### ISSUE TITLE
helm option for priorityClassName

### ISSUE THREAD

**Issue by jpuskar** [metallb/metallb#995]
Hi,
It would be great if the helm chart allowed priorityClassName to be set for the controller and speakers.

e.g.
```yaml
spec:
  template:
    spec:
      priorityClassName: system-node-critical
```

Here's an example from another chart:
https://github.com/jetstack/cert-manager/blob/master/deploy/charts/cert-manager/templates/webhook-deployment.yaml#L44
